- package.json
- src/components/auth/auth.service.ts
- src/core/core.module.ts
- src/core/database/indexer/create-indexes.decorator.ts
- src/core/database/indexer/index.ts
- src/core/database/indexer/indexer.constants.ts
- src/core/database/indexer/indexer.module.ts
- src/core/index.ts
- yarn.lock
Indexing can be implemented via the `OnIndex` decorator
```ts
@Injectable()
class FooService {
@OnIndex()
createIndexes() {
return [
'CREATE CONSTRAINT userIdExists ON (n:User) ASSERT EXISTS(n.id)',
'CREATE CONSTRAINT userIdUnique ON (n:User) ASSERT n.id IS UNIQUE',
];
}
}
```
They can also run db queries directly
```ts
@OnIndex()
async createIndexes({ db }: OnIndexParams) {
await db.query().raw('...').run();
}
```
> DB indexing lifecycle via decorator & discovery

- src/components/location/location.resolver.ts
- src/components/location/location.service.ts
Fixes #125 
Updates:
1. Switch to passing `ISession` as opposed to `token` as the secondary arg in the Location Service methods. This is for consistency with other more recently-created services, and also for type safety as a token is simply a string
2. Switch the delete method to utilize `propertyUpdater` (this is the only method that appears applicable for generics at the moment since this is an incomplete service that's utilizing mock data
> switching to generic for delete method in the location service

- tsconfig.json
Closes #138
Simply adding three remaining settings in `tsconfig.json` so that we can close out #138.
There were no additional errors as a result of this update. :D
> TS Strict Mode (PR 2/2)

- .github/CODEOWNERS
- package.json
- src/core/core.module.ts
- src/core/database/cypher.factory.ts
- src/core/logger/formatters.ts
- tsconfig.build.json
- Fix db connections not being closed.
There is logic builtin to `cypher-query-builder` will close db connections when node exits, but this wasn't doing anything for tests.
Now we close db connections on a Nest Lifecycle.
Now we don't have to `--forceExit` on Jest 🎉 
- Actually fix build location that I meant to fix in d6fa0d4
- Fix error formatter
Stack frame doesn't always have a file name, even though it says it always should 🤦‍♂
Accounting for null.
- Potentially fix db error handling
I'm not convinced this was handling awaiting the error correctly.
https://github.com/SeedCompany/cord-api-v3/blob/8841f7110495c887e5afcb31e0f6459440205030/src/core/database/cypher.factory.ts#L49-L51
Looking into driver code further, their [promise logic wraps their observer …
> Various bugfixes

- Dockerfile
- docker-compose.yml
- package.json
- scripts/docker-run.sh
- Ensure docker yarn install isn't modifying the lockfile
- Move wait for db command to entrypoint
- This way it happens transparently and different commands can be given easily
- Make compose aware of how to build the cord-api-v3 image
- Now `docker-compose up (--build)` will work without a previous build
- Created `yarn docker:run`
- This allows you to run any command inside of our built docker container with an ephemeral database.
- And it ensures images are pulled & built container is fresh and everything is cleaned up afterwards.
- Created `yarn docker:test` (`docker:run` with test command)
- Which runs tests in docker container with clean db every time
> Docker Compose Enhancements

- src/components/user/user.service.ts
- src/core/database/database.service.ts
Closes #200 
In this PR:
* UserService.create switched to utilize the cypher query builder for the DB insertion
* Removed some debug code from the DB service that got merged in a prior PR
I attempted to use the `db.createNode` generic. This turned out to be a pretty big waste of time that required too much refactoring. Due to the access control props we're setting on the user's base node, I think it justifies utilizing the query builder. Perhaps we can revisit this later if the `db.createNode` proves to be less flexible in other services.
> Switch to using the cypher query builder for the createUser service

- src/components/partnership/partnership.service.ts
- src/components/product/product.service.ts
- src/components/project/project-member/project-member.service.ts
- src/components/user/education/education.service.ts
- src/components/user/unavailability/unavailability.service.ts
- src/core/database/database.service.ts
I apologize for sending a PR that has no direct issue. I was originally working on #178 and found myself working on this refactor as a precursor to that task.
None
* The `DatabaseService.createNode` method (and all dependent methods) are now refactored to utilize the cypher query builder
* All dependent methods of `createNode` switched to `private`
* Eliminated `try / catch` in `createProperty` method that was swallowing DateTime errors which resulted in empty values for all DateTime fields in Neo4J
* ~Created `massagePropertyValue` private method for massaging values before sending them to Neo4J on update and create.~
* This has been removed now that we have the `ParamaterTransformer`
* Eliminated casting of all values to strings in Neo4J. This resolves an issue where arrays were being …
> Refactor create generic to use query builder

- src/components/file/dto/node.ts
- src/components/file/file.service.ts
- src/components/language/dto/language.dto.ts
- src/components/language/language.service.ts
- src/components/location/location.service.ts
- src/components/organization/dto/organization.ts
- src/components/organization/organization.service.ts
- src/components/partnership/dto/create-partnership.dto.ts
- src/components/partnership/dto/partnership.dto.ts
- src/components/partnership/partnership.service.ts
- src/components/product/dto/product.dto.ts
- src/components/product/product.service.ts
- src/components/project/dto/project.dto.ts
- src/components/project/project-member/dto/project-member.dto.ts
- src/components/project/project-member/project-member.service.ts
- src/components/project/project.service.ts
- src/components/user/education/dto/education.dto.ts
- src/components/user/education/education.service.ts
- src/components/user/unavailability/dto/unavailability.dto.ts
- src/components/user/unavailability/unavailability.service.ts
- src/core/database/cypher.factory.ts
- src/core/database/database.service.ts
Previously the generic, `TObject`, was not inferred with `createNode`. So this generic was meaningless without explicitly defining it (`createNode<Foo>(...)`).
I changed it to pass in `type` so it can automatically be inferred.
We also use this `type` we also default the `baseNodeLabel` and `aclEditProp` (unless `false`)
---
I also abstracted the session matching query boilerplate to its own function
> createNode infer generic with type param

- src/components/authentication/authentication.dto.ts
- src/components/authentication/authentication.resolver.ts
- src/components/authentication/authentication.service.ts
- src/components/authentication/session.pipe.ts
- test/utility/create-session.ts
* Convert the `createSession` mutation to the `session` query
* Return a nullable `user` object in `session` query, for the currently-logged-in user
> Convert createSession mutation to session query

- src/app.module.ts
- src/core/config/config.service.ts
- src/core/core.module.ts
- Move graphql setup to `CoreModule`
- Apply CORS config to Apollo server
It was missed previously with the `express.use()` call in `main.ts`
- Always return current origin for CORS to comply with fetch credentials="include" mode
- Change the emitted schema file to the standard graphql extension.
Will need to change frontend symlink to match.
> GraphQL CORS & Tweaks

- src/components/authentication/authentication.dto.ts
- src/components/authentication/authentication.resolver.ts
- src/components/authentication/authentication.service.ts
- src/components/budget/budget.service.ts
- src/core/core.module.ts
- src/core/exception.filter.ts
- src/core/graphql.config.ts
- src/core/validation.pipe.ts
- src/main.ts
- test/engagement.e2e-spec.ts
- test/file.e2e-spec.ts
- test/language.e2e-spec.ts
- test/partnership.e2e-spec.ts
- test/product.e2e-spec.ts
- test/project.e2e-spec.ts
- test/utility/create-app.ts
- test/utility/expect-not-found.ts
- test/utility/index.ts
- test/utility/login.ts
We've been pretty loose with error handling so far. Now that are starting to exercise the API on the frontend we need to better about "what's gone wrong".
I've customized the error handling layer so more helpful for GraphQL responses.
This should still be pretty painless. Let's look at some examples.
As far as raw input goes, GraphQL's schema validation goes a long way in determining the request is well formed.
Decorators from the `class-validator` library can take it one step further. For rules that should always be applied and don't need extra info / business logic. 
Here's some examples:
```tsx
class DTO {
@IsEmail()
email: string;
@MinLength(5)
name: string;
}
```
These are encouraged as a first step for multiple reasons:
- They are simple one-liners
- They are ran automatically
- …
> Error Handling 🔎

- src/common/index.ts
- src/common/validators/email.validator.ts
- src/common/validators/index.ts
- src/common/validators/validateBy.ts
- src/components/authentication/authentication.dto.ts
- src/components/authentication/authentication.resolver.ts
- src/components/user/dto/check-email.dto.ts
- src/components/user/dto/create-user.dto.ts
- src/components/user/user.resolver.ts
- forgot password & check email resolvers were not checking for valid email address
- Switch to custom `IsEmail` decorator to change the default error message
- Added same `ValidateBy` helper that `class-validator` lib uses internally. This should help make more custom decorators in future
> Fix email validation

- src/common/firstLettersOfWords.test.ts
- src/common/firstLettersOfWords.ts
- src/common/index.ts
- src/components/language/language.resolver.ts
- src/components/organization/organization.resolver.ts
- src/components/project/internship-project.resolver.ts
- src/components/project/translation-project.resolver.ts
As a fallback to pictures, which haven't even been implemented yet, we want to show the first letters of words. Like _CF_ for _Carson Full_. This regex implementation is smarter than "first letter after space", as you can see in the tests. But it requires unicode property escapes which aren't supported in all browsers. The polyfill, [xregexp](https://github.com/slevithan/xregexp), is [127KB](https://bundlephobia.com/result?p=xregexp@4.3.0) which is huge. In short, it's much easier to do this server side with native implementation and provide via API.
- Need to determine how and when to combine the 4 name properties. There might be a discussion pending around that as well.
- Waiting on refactor. `Location` union needs to be converted to a `Locatable` interface and hopefully this lazy …
> Avatar Letters for resources

- src/common/util.ts
- src/components/language/language.service.ts
- src/core/database/cypher.factory.ts
- src/core/database/errors.ts
- src/core/database/index.ts
- src/core/index.ts
Neo4j throws these generic errors which is super unhelpful for handling programmatically. 
This wraps it to provide a proper inheritance tree (incomplete) for the errors and stores dynamic data in properties of the error.
The first, biggest use case for this is uniqueness constraint failures. Previously we never even bothered to check the error message, which would've been really verbose anyways. Now it's really easy:
```tsx
if (e instanceof UniquenessError) {
e.label // the label that failed
e.value // the duplicated value
}
```
To take it a step further, these uniqueness errors automatically get logged so we don't have to do that in our concrete services.
I updated `LanguageService` to handle this error, as an example.
> DB Error Handling

- src/core/database/database.service.ts
- test/organization.e2e-spec.ts
A root SG member can create baseNode, as root user is member of RSG, and RSG has permission to Root Permission with read and edit  rights to its baseNode and its properties. 
(reqUser)<-[:member]-[:RSG]-[:Permission]-[:basenode]->(:BaseNode)-[:property]->(:Property)
> root sg member can create node 

- src/components/user/user.service.ts
- test/file.e2e-spec.ts
rogue node is removed while creating user
> user create rogue node removed

- package.json
- src/app.module.ts
- src/components/timezone/index.ts
- src/components/timezone/timezone.dto.ts
- src/components/timezone/timezone.module.ts
- src/components/timezone/timezone.resolver.ts
- src/components/timezone/timezone.service.ts
- src/components/user/dto/user.dto.ts
- src/components/user/user.module.ts
- src/components/user/user.resolver.ts
- test/authentication.e2e-spec.ts
- test/user.e2e-spec.ts
- test/utility/fragments.ts
- test/utility/register.ts
- yarn.lock
Create timezone APIs that are sourced from the latest [`moment-timezone`](https://github.com/moment/moment-timezone/) data which maintains a json file of the IANA database.
This allows the frontend to not have to bundle this data and send to every client, when it will very rarely be used.
I also changed the User.timezone property to be a TimeZone object instead of a string.
> Timezone APIs

- src/components/engagement/engagement.service.ts
- test/engagement.e2e-spec.ts
resolves #661
merged ceremony, project and language connection into query.  
added secondary queries for testing of validity of project and language inputs.  
added second test for ceremonies on internship engagements.
> create language engagement refactor query

- .eslintrc.yml
- package.json
- src/components/budget/budget.module.ts
- src/components/budget/budget.resolver.ts
- src/components/budget/budget.service.ts
- src/components/budget/handlers/create-project-default-budget.handler.ts
- src/components/budget/handlers/index.ts
- src/components/budget/handlers/sync-budget-records-to-funding-partners.handler.ts
- src/components/file/file.module.ts
- src/components/file/handlers/attach-project-root-directory.handler.ts
- src/components/file/handlers/detach-project-root-directory.handler.ts
- src/components/file/handlers/index.ts
- src/components/partnership/events/index.ts
- src/components/partnership/events/partnership-created.event.ts
- src/components/partnership/events/partnership-deleted.event.ts
- src/components/partnership/events/partnership-updated.event.ts
- src/components/partnership/partnership.service.ts
- src/components/project/events/index.ts
- src/components/project/events/project-created.event.ts
- src/components/project/events/project-deleted.event.ts
- src/components/project/events/project-updated.event.ts
- src/components/project/project.resolver.ts
- src/components/project/project.service.ts
- src/core/core.module.ts
- src/core/events/event-bus.service.ts
- src/core/events/event-handler.decorator.ts
- src/core/events/events.module.ts
- src/core/events/index.ts
- src/core/index.ts
- yarn.lock
Services can dispatch events that other services can listen/subscribe to in a decoupled way. This allows parts of the application to respond to _indirect_ mutations.
I've implemented some of our first ones as examples:
- [On project creation](https://github.com/SeedCompany/cord-api-v3/blob/7dc7cb2a0fccf2bfe5a7d5aceb8f2445f45dfeb1/src/components/project/project.service.ts#L757)
- [create root directory](https://github.com/SeedCompany/cord-api-v3/blob/3b51dacde61d6593aa7bc601024c5664df4b3f17/src/components/file/handlers/attach-project-root-directory.handler.ts)
- On partnership mutation (created/updated/deleted)
- [sync budget records](https://github.com/SeedCompany/cord-api-v3/blob/bfa19efa3c75e741ee402d29dc20ce184522d5a1/src/components/budget/handlers/sync-budget-records-to-funding-partner …
> Event Handling

- src/common/exceptions/duplicate.exception.ts
- src/common/exceptions/exception.ts
- src/common/exceptions/index.ts
- src/common/exceptions/input.exception.ts
- src/common/exceptions/not-implemented.exception.ts
- src/common/exceptions/unauthenticated.exception.ts
- src/common/exceptions/unauthorized.exception.ts
- src/common/index.ts
- src/common/not-implemented.error.ts
- src/components/authentication/authentication.service.ts
- src/components/user/user.service.ts
- src/core/database/errors.ts
- src/core/exception.filter.test.ts
- src/core/exception.filter.ts
- src/core/validation.pipe.ts
This is an addendum to #414 
The problem currently is there's not an easy way to give _custom_, _statically-typed_ info in exceptions (beyond a custom code).
It's true that NestJS' `HttpExceptions` accept really anything and we do send that back to the client. However, that flexibility is really the problem. They allow for anything so it's hard to be consistent on the error creation side (without subclass) and hard on the receiving side, whether that's formatting for client or catching the exception somewhere else in the codebase.
See [exception.filter.test.ts](https://github.com/SeedCompany/cord-api-v3/blob/d92f857ddccaa653547ac80dfbbbf0f839c3d413/src/core/exception.filter.test.ts) for all the different ways the exceptions can be created. 
Custom codes are _too_ easy to mess up. …
> [RFC] Error Handling Again

- src/components/partnership/partnership.service.ts
- src/components/project/project.service.ts
- src/core/events/event-bus.service.ts
- src/core/events/events.module.ts
Fixes #703 
Turns out you cannot _replace_ a provider. NestJS just ignores these attempts which is annoying.
So instead of importing `CqrsModule` we are declaring its services ourselves to get around this.
This isn't that much more work, and it does give us more control.
I also changed `IEventBus` to a class so it can be injected without the `@Inject` decorator.
> Fix our EventBus not applying

- src/core/exception.filter.test.ts
- src/core/exception.filter.ts
Discovered in #701 
Problem is if errors change and become more specific they are suddenly not handled on the consumption side.
For example if we are handling creating a user with a duplicate email address as an `Input` error and then the API decides to create a `DuplicateException` extending `InputException then that comes back as `Duplicate` with no relation to `Input` even though they could at worst, be handled in the same way.
This changes `code` to `codes` that is a hierarchy of the exceptions classes (as codes).
So in the example above the error response would go from
```tsx
codes: ['Input']
```
to
```tsx
codes: ['Duplicate', 'Input']
```
So if API consumer was checking for `Input` in the array that will still work. They now have the option to handle `Duplicate`  in a more specific …
> Expose exception chain to API consumers

- src/components/user/user.service.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/733
Fix user.service `readOne` returns null values even if requesting user has canReadUsers permission.
> Issue: 733 - Fix user readOne returns null values

- src/common/id-field.ts
- src/common/index.ts
- src/common/validators/index.ts
- src/common/validators/short-id.validator.ts
- Adds validator for _shortid_
- Adds `IdField` decorator as a shortcut for GQL ID Field with _shortid_ validation.
Next step is to apply below everywhere:
```diff
- @Field(() => ID, { ... })
+ @IdField({ ... })
```
> IdField decorator

- src/common/id.arg.ts
Fixes #777
Supersedes #779 
Applies the `@IsShortId` validation decorator to the id values specified by `@IdArg` decorator.
> Update IdArg decorator to validate value is a short id

- src/components/file/bucket/filesystem-bucket.ts
- src/components/file/bucket/local-bucket.ts
- src/components/file/local-bucket.controller.ts
- test/utility/create-file.ts
Fixes an issue where files uploaded to the "filesystem bucket" (for dev purposes) could not be opened directly or after download. This turned out to be due to us converting the incoming `Buffer` to a `string` and writing/reading it as such.
- Update `upload()` method of `local-bucket` controller to leave request body as `Buffer` instead of converting to a `string`
- Update `readFile()` and `writeFile()` methods of `filesystem-bucket` to read/write file as `Buffer`
- Update `FakeAwsFile` type to set `Body` property type to `Buffer`
- Update `generateFakeFile()` method in `test/utility/create-file` to generate `Buffer` for the `content` property instead of a `string`
> Fix corrupted files in filesystem bucket

- src/components/user/dto/create-person.dto.ts
- src/components/user/dto/update-user.dto.ts
@sethmcknight Says that having email optional for people isn't necessary.
We have no reason not to allow changing email currently.
Open to comments about why we shouldn't do this.
> Require email when creating person and allow updating

- src/components/budget/dto/list-budget.dto.ts
- src/components/engagement/dto/list-engagements.dto.ts
- src/components/organization/dto/list-organization.dto.ts
- src/components/partnership/dto/list-partnership.dto.ts
- src/components/product/dto/list-product.dto.ts
- src/components/project/dto/list-projects.dto.ts
- src/components/project/project-member/dto/list-project-members.dto.ts
- src/components/user/education/dto/list-education.dto.ts
- src/components/user/unavailability/dto/list-unavailabilities.dto.ts
- test/budget.e2e-spec.ts
- test/education.e2e-spec.ts
- test/partnership.e2e-spec.ts
- test/unavailability.e2e-spec.ts
Those lists can be determined by relationships on the owning objects
`budgets.filters.projectId` -> `project.budgets`
> Remove ID filters from API

- src/common/luxon.graphql.ts
- src/common/name-field.ts
- src/common/transform.decorator.ts
Fixes #903 
- nulls are accepted now
- Invalid ISO strings are returned as validation errors instead of server errors
> Fix date input validation

- src/common/exceptions/index.ts
- src/common/exceptions/input.exception.ts
- src/common/exceptions/not-found.exception.ts
- src/common/exceptions/unauthorized.exception.ts
- src/components/authentication/authentication.service.ts
- src/components/engagement/engagement.service.ts
- src/components/file/file.repository.ts
- src/components/file/file.service.ts
- src/components/organization/organization.service.ts
- src/components/partnership/partnership.service.ts
- src/components/project/project.service.ts
- Update `InputException` to be more flexible with it's creation
- Created `NotFoundException` (extending `InputException`)
- Make `InputException.field` mutable and add a `withField` helper
- Update `FileService/Repository` to use our exception classes
- Updated `createDefinedFile/updateDefinedFile` to accept a `field` key so errors can be thrown with correct info
- Fix project & org checks on create partnership and add their fields to error
This should correct the error shown in #902 to be a user error which is the only problem with that ticket.
Closes #902
> Error Progress

- src/core/core.module.ts
- src/core/exception.filter.ts
- src/core/graphql-logging.plugin.ts
- src/core/graphql.config.ts
- src/core/logger/formatters.ts
- Exceptions from requests (90%) now logged
- Stacktraces for both GQL responses and console logs have:
- No worthless traces like for schema & validation errors
- Frames are limited to and relative to our src files
Examples shown below
Previous exceptions are logged to console. This can help identify what actually went wrong while still giving the requestor a sane default/unknown error message. (This should also reduce the need to both log the exception in addition to re-throwing a different one)
Here's what a "server" error looks like:
We can see from this message that we need to handle this error as a `DuplicateException`.
We actually already do handle this in _master_ I just commented it out for screenshot.
Here's that logic: …
> Error Logging

- src/common/secured-property.ts
- src/components/partnership/dto/partnership.dto.ts
- src/components/product/dto/product-medium.ts
- src/components/product/dto/product-methodology.ts
- src/components/product/dto/product-purpose.ts
- src/components/project/project-member/dto/role.dto.ts
- src/components/scripture/dto/scripture-range.dto.ts
- src/components/user/user.service.ts
TS enums are weird because they are objects but also only certain strings.
Due to this we need to handle them separately from other object types so that types can be inferred correctly.
The good news is the types can be inferred so the new code is still easy to use.
> Refactor SecuredEnumList out of SecuredPropertyList to fix types

- src/common/secured-property.ts
- src/components/scripture/dto/scripture-range.dto.ts
We've been pretty lax about whether secured values can actually be null or not. Because if you can't read the value then we send back null, which means we can't represent in schema whether this is a null for security or null because it can be.
With this we are step closer to define that ambiguity. Now we have the option to add `nullable: true` when calling `SecuredProperty/Enum`, which will add `null` as a possible type to the value property in TS. I also added nullable variants to the common scalar secured objects - i.e. `SecuredStringNullable` (I'm not thrilled about the name)
I know in GQL schema both `SecuredString` & `SecuredStringNullable` will be identical. But we can still use this convention to know client-side when a null is intended or not and we can use null server side as …
> Update SecuredProperty/Enum to handle nullable

- src/components/organization/organization.service.ts
- src/components/partnership/partnership.service.ts
Refactors org readOne just like Languages. The `property` method in partnership services wasn't being used anymore so removed.  The `permission` method was using the wrong cypher alias for the Partnership node
> fix(organization.service.ts): refactor readOne

- src/components/engagement/dto/engagement.dto.ts
- src/components/engagement/engagement.service.ts
Following Language ReadOne refactor.  
For the `startDate` and `endDate` values we check if `canRead` is true on a ternary, but since the engagement type doesn't allow a `null` value I had to evaluate to `undefined`.  Please double check my Typescript line 923
```
const startDate = canReadStartDate
? props.startDateOverride ?? project.mouStart.value
: undefined;
```
> Refactor Engagement ReadOne

- src/components/partnership/partnership.service.ts
The readOne function was missing the fallback to project mouStart and project mouEnd.
This pull request adds the business rule back in.
Closes #1045
> added fallback to project mouStart and project mouEnd

- src/components/project/project-member/project-member.service.ts
- test/project-member.e2e-spec.ts
Couldn't add the same user as project member after deleting it because wasn't looking for the `active` tag on existing project members
> Bugfix: add project member after delete

- src/components/budget/budget-record.resolver.ts
- src/components/budget/budget.service.ts
- src/components/budget/dto/budget-record.dto.ts
- test/project.e2e-spec.ts
Added missing organization secured property to budget service method readOneRecord. 
'organizationId' was being set incorrectly which was resulting in null responses to API queries.
Updated budget record DTO and resolver to call organization id string 'organization' instead of 'organizationId'.
This matches the naming convention in the partnership DTO and resolver.
Closes #1082
> Fix budgetRecord.organization

- src/core/validation.pipe.ts
Add failed constraints to validation error stacktrace
Before:
After:
@zkhin Does this help?
> Improve validation errors

- src/components/budget/budget.service.ts
Closes #1108 
Setting the initial `amount` property of a `budgetRecord` to `null` will indicate that it has not yet been set by the user.
> Initial `budgetRecord.amount` set to `null` instead of `0`

- src/common/secured-property.ts
- src/components/budget/dto/budget-record.dto.ts
- src/components/budget/dto/update-budget.dto.ts
Second half of #1108 
This updates GQL schema to reflect that amount can be a float or null.
> Change budget record amount to be a nullable float

- src/components/product/product.service.ts
- src/components/scripture/reference.ts
- src/core/database/database.service.ts
The unused `sr` node alias was causing a duplicate variable error when multiple scripture references were made
> Create multiple scripture references verride bug

- src/components/scripture/scripture-reference.service.ts
- test/film.e2e-spec.ts
- test/literacy.e2e-spec.ts
- test/product.e2e-spec.ts
- test/song.e2e-spec.ts
- test/story.e2e-spec.ts
Product scriptures were returning unsorted so the tests failed.
Sorted the returned results and check with `expect.arrayContaining` to match array items.
> Failing tests product scriptures

- src/components/file/file.repository.ts
- src/components/product/product.service.ts
- src/components/user/unavailability/unavailability.service.ts
- src/core/database/database.service.ts
Removed the old update property methods that searched by ACL connections.  Also refactored create unavailability because that was using the old create service with ACL connections.
Next will remove the old create service, will do that on a separate PR that includes refactoring file nodes create and file nodes read
> Remove old update property methods with acl

- src/core/config/config.service.ts
- src/core/email/aws-ses.factory.ts
We can't assume it will be setup with the same region as code is being ran in.
Part of fix for https://github.com/SeedCompany/cord-field/issues/448
> Make SES region configurable

- src/components/product/product.service.ts
- src/components/scripture/scripture-reference.service.ts
- test/product.e2e-spec.ts
Have input checks for updating product scripture references (override) based on product type.
Have `scriptureRefService.update` take care of accepting `null` override values and setting the isOverride tag to false
> Update product scripture references

- src/components/authentication/authentication.service.ts
- test/authentication.e2e-spec.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1213
@CarsonF Cannot reproduce the issue on backend. As you can see in this case, it passes all the reset password workflow (https://github.com/SeedCompany/cord-api-v3/blob/363826e9c396eab800a46afb5c590f25c76e046c/test/authentication.e2e-spec.ts#L29~L89)
> Authentication reset password test case

- src/components/admin/admin.service.ts
Cannot create project for admin because on create we automatically assign the creator **ProjectManager** on that project, but the root user doesn't have that role available (created without roles).  We recently added the role validation on adding a team member. Now on creating the admin user we give all roles
> Cannot create project

- src/components/user/dto/create-person.dto.ts
Added default **ProjectMember** role on create person.  This will give new non-root users ability to create project.  Will be removed once the roles features are implemented.
> Cannot create person

- src/components/language/dto/language.dto.ts
- src/components/language/language.module.ts
- src/components/language/language.resolver.ts
- src/components/language/language.service.ts
Pull language sponsorStartDate field in its own resolver.
Also moved acl permissions out of language.projects list read, hardcoded to `true` until Roles services are done
> Language sponsor start date and projects permissions

- src/components/partner/partner.service.ts
- src/components/search/dto/search-results.dto.ts
- src/components/search/search.module.ts
- src/components/search/search.service.ts
created `readOnePartnerByOrgId` that finds the partner connected to this org id.  The the hydrator calls `readOnePartnerByPartnerIdOrOrgId`, calls both `partner.readOnePartnerByOrgId` and `partner.readOne`.  This pattern allows us to keep `partner.readOne` unchanged and consistent with the other service readOnes.
> Partner search

- src/components/ceremony/ceremony.service.ts
- src/components/ceremony/handlers/create-engagement-default-ceremony.handler.ts
The Role refactor exposed 2 existing issues
1. On create LanguageEngagement, the returned engagement doesn't include the ceremonyId that was created by the event handler.  This was never found because we never needed the ceremony after creating a langEngagement
2. On Ceremony readOne, the type value was returned from the parseSecuredProperties function.  But now with the new roles refactor the type property doesn't get a Permission node because according to the dto it's not a secured property, so now it's values are always undefined.  This wasn't found because we manually gave it a Permission Node in the old create process
> Ceremony readOne fix type property

- src/components/project/query.helpers.ts
Don't have the active property on the Node itself, only on the relation
> Remove active true on property node match

- src/components/scripture/books.ts
Some abbreviations found in v2 data weren't accounted for.
> Add book abbreviations

- src/components/location/location.service.ts
Replace `FieldRegionName` with `LocationName` while creating location
> Fix location name duplication

- src/components/budget/handlers/sync-budget-records-to-funding-partners.handler.ts
- test/partnership.e2e-spec.ts
- test/project.e2e-spec.ts
This fixes a bug where the fiscal year is calculated as being the same as the year of the date, which is not the case.
> Use fiscalYears function for budget records

- src/components/engagement/engagement.service.ts
- test/engagement.e2e-spec.ts
- test/utility/create-engagement.ts
The old update mentor only worked a mentor already existed because it used a hard match.  Now using optional match to set the old to inactive.
Same pattern for location
> Cannot add mentor to internship engagement

- .eslintrc.yml
- src/components/authorization/dto/powers.ts
- src/components/language/language.service.ts
- src/components/user/user.service.ts
- src/core/database/database.service.ts
- src/core/database/query.helpers.ts
- test/language.e2e-spec.ts
Following the steps defined in the ticket description.  To use `deleteNodeNew` will need to pass in all the baseNode labels, and a dictionary of all of its unique property relations and those property node labels.
> Refactor delete

- src/components/budget/budget.module.ts
- src/components/budget/handlers/sync-budget-records-to-funding-partners.handler.ts
- src/components/partnership/events/partnership-updated.event.ts
- src/components/partnership/partnership.service.ts
- src/components/project/project.service.ts
- CRITICAL: Fixed records being deleted for _ALL_ organizations for a fiscal year (instead of the one partnership changing)
- Only sync records if budget status is _pending_
- Determine budget based on project's _current_ budget (instead of first one found)
- Throw errors if any field cannot be read (instead of silently failing)
- Refactored code to be more linear, thus easier to follow
I reordered methods in handler before changing logic so check this [diff](https://github.com/SeedCompany/cord-api-v3/compare/4ffe4e1..72a12c8) for the actual logic changes
> Refactor & Fix Budget Record Sync

- package.json
- src/common/validators/index.ts
- src/common/validators/iso-3166-1-alpha-3.validator.ts
- src/components/location/dto/create-location.dto.ts
- src/components/location/dto/iso-country.dto.ts
- src/components/location/dto/location-type.enum.ts
- src/components/location/dto/location.dto.ts
- src/components/location/dto/update-location.dto.ts
- src/components/location/location.resolver.ts
- test/utility/create-location.ts
- yarn.lock
- Alpha 3 codes are now confirmed against the actual list. Note that `abc` will no longer work.
- Alpha 3 field now allows null on update to remove previous value
- New (lazy) field `isoCountry` on `Location` looks up the alpha 3 code and provides the entry (name, 2-letter/3-letter/numeric code).
- New `isoCountries` query provides list from our API
> ISO 3166-1 validation & lookup

- src/core/database/cypher.factory.ts
- src/core/database/query.overrides.ts
Added `Query.logIt` to log the query.
All of our queries are already logged on the `database:query` channel at a _debug_ level. This level is ignored by default to not spam the log.
This method works by changing the log level of that query. By default it bumps the level from _debug_ to _notice_.
So you need to make sure if you've changed your `logging.yml` file to allow that channel to at least the _notice_ level for it work properly.
Example:
```tsx
const createFile = this.db
.query()
.call(matchRequestingUser, session)
.call(createBaseNode, input.id, ['FileVersion', 'FileNode'], props)
.return('node.id as id')
.logIt()
.asResult<{ id: string }>();
const result = await createFile.first();
```
@michaelmarshall @SeedCompany/external Let me know if you think this is helpful.
> Query.logIt

- src/components/partnership/partnership.service.ts
The input exception was throwing the wrong input field.  Now a proper message is passed to the client 
However, @CarsonF this does bring up a different issue.  On the form if a user selects a partner ( that has no financial reporting types), selects managing, selects a fin reporting type, gets the error, then switches the radio to the other fin type and gets the same error again.  There's no way "out" of this except to select a different type, partner, or close the dialog. 
Maybe we change the field from radio to the enumfield so the can toggle on an off the selection, or if we're really clever we read what financial reporting types are available and only show that option (then it'll have to be a enum button because a radio doesn't make sense for single options).
> Fix input exception

- src/components/user/user.service.ts
- test/project.e2e-spec.ts
When user creates a new `baseNode`, the auth service runs`mergeSecurityGroupForRole` then `addAllUsersToSgByTheUsersGlobalRole` , which gives the project the security groups then adds the users with matching roles to these security groups.  However, any new user created after that doesn't get added to those existing SGs.  Running `authorizationService.roleAddedToUser` at the end of `user.create` adds the new user to the existing SGs and seems to fix it.  `roleAddedToUser` is currently part of user.update
> On create user add the user to the existing SGs

- src/components/admin/admin.service.ts
- src/components/project/project.service.ts
- test/project.e2e-spec.ts
reverting PR 1448. https://github.com/SeedCompany/cord-api-v3/pull/1448
it caused admins not being able to list projects. I assume it breaks for other global role holders. we'll need to think through how to do this.
> Project list bug

- src/components/authorization/roles/administrator.role.ts
- src/components/authorization/roles/consultant-manager.role.ts
- src/components/authorization/roles/consultant.role.ts
- src/components/authorization/roles/controller.role.ts
- src/components/authorization/roles/field-operations-director.role.ts
- src/components/authorization/roles/financial-analyst.role.ts
- src/components/authorization/roles/fundraising.role.ts
- src/components/authorization/roles/intern.role.ts
- src/components/authorization/roles/leadership.role.ts
- src/components/authorization/roles/liason.role.ts
- src/components/authorization/roles/marketing.role.ts
- src/components/authorization/roles/mentor.role.ts
- src/components/authorization/roles/project-manager.role.ts
- src/components/authorization/roles/regional-communications-coordinator.role.ts
- src/components/authorization/roles/regional-director.role.ts
- src/components/authorization/roles/staff-member.role.ts
- src/components/authorization/roles/translator.role.ts
- src/components/engagement/dto/create-engagement.dto.ts
- src/components/engagement/dto/engagement.dto.ts
- src/components/engagement/dto/update-engagement.dto.ts
- src/components/engagement/engagement.service.ts
- src/components/engagement/model/langauage-engagement.model.db.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1491
@michaelmarshall Please update the schema/cord-procedures with this new field.
> Add historicGoal to language engagement

- src/components/project/project.service.ts
- test/project.e2e-spec.ts
Use a subquery to get the translation project sensitivity value, and use that value in the sorting.
Full query: 
```
MATCH (requestingUser:User { id: 'h6iPkJ7AfXz' })<-[:member]-(:SecurityGroup)-[:permission]->(perms:Permission)-[:baseNode]->(node:Project)
WITH distinct(node) as node, requestingUser
MATCH (node)
MATCH (node)
MATCH (requestingUser)<-[:user]-(projectMember)<-[:member]-(node)
WITH collect(distinct node) as nodes, count(distinct node) as total
unwind nodes as node
call {
with node
optional match (node)-[:engagement { active: true }]->(:LanguageEngagement)-[:language { active: true }]->
(:Language)-[:sensitivity { active: true }]->(sensitivityProp:Property)
WITH *, case sensitivityProp.value
when null then 3
when 'High' then 3
when 'Medium' then 2
when 'Low' then 1
end as …
```
> Sort project sensitivity including translation project

- logging.example.yml
- package.json
- src/core/config/config.service.ts
- src/core/core.module.ts
- src/core/exception.filter.test.ts
- src/core/exception.filter.ts
- src/core/logger/buffer-logger.service.ts
- src/core/logger/exception-logger.ts
- src/core/logger/formatters.ts
- src/core/logger/index.ts
- src/core/logger/level-matcher.provider.ts
- src/core/logger/level-matcher.ts
- src/core/logger/logger.decorator.ts
- src/core/logger/logger.module.ts
- src/core/logger/nest-logger-adapter.service.ts
- src/core/logger/proxy-logger.service.ts
- src/main.ts
- yarn.lock
The main goal of this PR is to handle logging nicer for our deployed environments.
I spent a lot of time connecting up a direct connection to AWS cloudwatch via a winston transport, so we could send json instead of strings. It turns out the AWS API only accepts strings, _but_ it automatically parsing json strings.
This led to the discovery of that (json parsing) also working for stdout which ECS automatically forwards to cloudwatch.
This saves effort, complexity, and performance so I'm glad I found it - just wish I didn't take the hard route lol.
Previously the logs looked like this
Now they look like this
And more importantly they can be queried in CloudWatch Insights
I believe that the logger should be injected via DI to allow for flexibility & customization, however this creates a gap …
> Logging for deployed application (CloudWatch)

- src/components/budget/budget.service.ts
- src/components/ceremony/ceremony.service.ts
- src/components/engagement/engagement.service.ts
- src/components/field-region/field-region.service.ts
- src/components/field-zone/field-zone.service.ts
- src/components/file/file.repository.ts
- src/components/film/film.service.ts
- src/components/funding-account/funding-account.service.ts
- src/components/language/language.service.ts
- src/components/literacy-material/literacy-material.service.ts
- src/components/location/location.service.ts
- src/components/organization/organization.service.ts
- src/components/partner/partner.service.ts
- src/components/partnership/partnership.service.ts
- src/components/product/product.service.ts
- src/components/project/project.service.ts
- src/components/song/song.service.ts
- src/components/story/story.service.ts
- src/components/user/user.service.ts
- src/core/database/database.service.ts
- test/zone.e2e-spec.ts
It looks like the Engagement and User service's `Create` needs to be refactored, they are using a different create style ```...property('realFirstName', input.realFirstName, 'user'),``` vs `createBaseNode`
@michaelmarshall The workflow delete, and most of the entire service looks to be very old.  Does the delete need to be refactored similarly?
> Refactor delete all services

- src/components/engagement/dto/update-engagement.dto.ts
- src/components/engagement/handlers/set-initial-end-date.handler.ts
- src/components/project/dto/update-project.dto.ts
- src/components/project/handlers/set-initial-mou-end.handler.ts
- test/engagement.e2e-spec.ts
- Set initial end date if the project/engagement is in-dev (instead of active)
- Set initial end date regardless of whether it was previously set or not
- Set initial end date to null if end date is null (if in-dev)
- Ensure logic is using real by checking `canRead` & throwing
- Ignore status on creation (helps migration logic)
> Fix initial end handling

- package.json
- src/components/admin/admin.service.ts
- src/components/authorization/authorization.service.ts
- src/core/database/cypher.factory.ts
- src/core/database/database.service.ts
- src/core/database/index.ts
- src/core/database/indexer/indexer.module.ts
- src/core/database/transaction.ts
- src/core/database/transactional.decorator.ts
At a high level, this adds a `@Transactional()` decorator to run method inside of transactions.
```tsx
@Injectable()
class Foo {
@Transactional()
async doThing() {
await this.db.query().matchNode('n').return('n').run();
await this.doOtherThing();
}
@Transactional()
doOtherThing() {
try {
await this.db.query().matchNode('n').return('n').run();
} catch (e) {
throw new ServerException('Failed to do other thing', e);
}
}
}
```
- Database calls work exactly the same way.
- `doOtherThing` when called from `doThing` uses the existing transaction from the `doThing` call instead of creating a new one. If `doOtherThing` is called directly it will create it's own transaction (assuming there isn't one already up the call stack).
- Transaction is rolled-back when an exception is thrown. This doesn't …
> Database Transactions v2

- src/core/database/database.service.ts
- src/core/database/indexer/indexer.module.ts
Move reading server info outside of transaction that's modifying schema.
This makes it compatible with neo4j <4.1.5
https://neo4j.com/release-notes/neo4j-4-1-4/
> Fix compatibility with Neo4j <4.1.5 (indexing transactions)

- src/components/admin/admin.service.ts
- src/components/authentication/authentication.module.ts
- src/components/authentication/authentication.service.ts
- src/components/authentication/crypto.service.ts
- src/components/budget/budget.service.ts
- src/components/language/ethnologue-language/ethnologue-language.service.ts
- src/components/language/language.service.ts
- src/components/partnership/partnership.service.ts
- src/components/product/product.service.ts
- src/components/project/project.service.ts
- src/components/user/unavailability/unavailability.service.ts
- src/core/config/config.service.ts
- src/core/database/query.helpers.ts
I was unable to reproduce the issue in #710. However, this PR should help with maybe the actual issue.
Now an existing root user's email/password in DB is updated to match the app's configuration on boot. This makes things simpler for users as their app config will always be right (previously it was wrong/ignored when the user was created by another app configuration). 
**Breaking change:** The root user is now identified by a `RootUser` label instead of the email address.
Another problem was a misspelling in the existing user query, however I think this was never previously encountered as there was a duplicate existing user check. I removed the duplicate check and fixed the misspelling.
I'm not a fan of setting the root user ID and then using it in other places in the app. It is a global …
> Improve root user experience

- src/components/file/dto/upload.dto.ts
- src/components/file/file.service.ts
This is a workaround for v2 migration.
The files for in the v2 bucket do not have their content-type set correctly for whatever reason. It's not a problem because the v2 API is told directly what the mime type is and it's saved in the database.
There's no way to retroactively update this metadata on the S3 objects. So we'll just continue this for the migrated files because it's the simplest path forward.
> Allow file mime type to be defined by API instead of uploaded file

- src/components/engagement/engagement-status.resolver.ts
- src/components/engagement/engagement.rules.ts
- src/components/engagement/engagement.service.ts
- src/components/project/project.rules.ts
There's no need to lookup the project id of the engagement just to then look up its current step later. It can be be looked up directly in one query.
> Consolidate query for determining project current step for engagement status rules

- src/components/language/ethnologue-language/ethnologue-language.service.ts
They don't seem to be used and the labels are not specific
> Remove labels from ethnologue properties

- src/components/engagement/pnp-extractor.service.ts
- i.e. `Math.max(...[])` doesn't work, but `Math.max([...[]])` does (returns `0`)
> Math.max returns -Infinity when you try to spread an empty array

- src/components/engagement/engagement.service.ts
- src/components/partnership/partnership.service.ts
- src/components/project/project-member/project-member.service.ts
- test/engagement.e2e-spec.ts
- test/partnership.e2e-spec.ts
- Fix engagement, partnership, project member uniqueness checks not accounting for deleted nodes
- Merge node existence & relationship uniqueness to same query and return better error messages to consumer
Related to #1646
> Fix uniqueness check not accounting for deleted nodes

- src/components/project/handlers/set-initial-mou-end.handler.ts
- src/core/database/database.service.ts
- Created `DatabaseService.updateProperties` which is similar to `sgUpdateProperties` without the permission checks
- Deprecated `sgUpdateProperties`. Call is forwarded to `updateProperties` meaning they are all unsecured now.
- Removed `sgUpdateProperty`.
> Unsecure updates

- src/components/authorization/dto/role.dto.ts
Waiting on https://github.com/SeedCompany/cord-api-v3/issues/1694 to be closed. After it's closed we should run the following queries in the db to verify no users or project members have the role of `Development`.
These are the queries I ran to verify the roles didn't exist in the db:
`match(u:User)-[r:roles{active:true}]-({value:""}) return count(u)`
```
match(u:ProjectMember)-[r:roles{active:true}]-(rn)
where any(x in rn.value where x = "")
return count(u)
```
> Remove obsolete roles

- src/components/authentication/authentication.resolver.ts
- src/components/authentication/session.pipe.ts
- src/core/config/config.service.ts
`SameSite=none` means it works in 3rd party.
This was the default but needs to be explicit now.
Browser have changed the default to be 1st party.
Specifying `SameSite` requires `Secure=true` (HTTPS).
This is needed for Apollo Studio.
> Allow session cookie in 3rd party

- src/components/authorization/authorization.service.ts
- test/user.e2e-spec.ts
We were getting a deadlock in production trying to update user roles, because the code to modify the user runs in a transaction and its uncommitted when we ask the db to update security groups for that user. The transaction in progress locks the user node and then the security group query, which uses apoc.periodic.iterate (which uses separate transactions), waits for that lock to be released.
Unfortunately I was unable to reproduce this deadlock locally.
This is the cause of #1729
> Fix user role update deadlock

- src/components/project/handlers/set-department-id.handler.ts
- src/components/project/project.service.ts
- test/project.e2e-spec.ts
- Create new dept ids at xxx11 and up to avoid colliding with historic ids in intacct
- Select randomized new dept id from list of unused ids in the acceptable range –– this will prevent duplicate dept ids stemming from simultaneous requests in the vast majority of cases
> Fix duplicate department IDs

- src/components/project/handlers/step-changed-notification.handler.ts
- src/components/project/project.rules.ts
Fixes #1746 
- Add optional notifiers to individual project transitions so we can say notify these additional people when going "from step to this step"
- Notify `projects@tsco.org` when going from _PendingFinanceConfirmation_ to _Active_
> Project Transition Notifiers

- src/components/budget/budget.service.ts
- src/components/ceremony/ceremony.service.ts
- src/components/engagement/engagement.service.ts
- src/components/field-region/field-region.service.ts
- src/components/field-zone/field-zone.service.ts
- src/components/file/file.repository.ts
- src/components/film/film.service.ts
- src/components/funding-account/funding-account.service.ts
- src/components/language/language.service.ts
- src/components/literacy-material/literacy-material.service.ts
- src/components/location/location.service.ts
- src/components/organization/organization.service.ts
- src/components/partner/partner.service.ts
- src/components/partnership/partnership.service.ts
- src/components/product/product.service.ts
- src/components/project/project-member/project-member.service.ts
- src/components/project/project.service.ts
- src/components/song/song.service.ts
- src/components/story/story.service.ts
- src/components/user/unavailability/unavailability.service.ts
- src/components/user/user.service.ts
- src/core/database/database.service.ts
- src/core/database/query/deletes.ts
- src/core/database/query/index.ts
- Removed old `deleteNode` query
- Renamed `deleteNodeNew` to `deleteNode`. Change signature to just take the single argument.
- Split off delete query logic into separate function. I'd like to leverage this to be able to do multiple deletes at once. This could be useful in several places like syncing budget records or periodic reports where multiple deletes could happen at once. i.e. matching via custom logic and then forwarding to the delete query fragment.
> Finish deletes refactor

- src/components/budget/budget.service.ts
- src/components/ceremony/ceremony.service.ts
- src/components/engagement/engagement.service.ts
- src/components/field-region/field-region.service.ts
- src/components/field-zone/field-zone.service.ts
- src/components/film/film.service.ts
- src/components/funding-account/funding-account.service.ts
- src/components/language/language.service.ts
- src/components/literacy-material/literacy-material.service.ts
- src/components/location/location.service.ts
- src/components/organization/organization.service.ts
- src/components/partner/partner.service.ts
- src/components/partnership/partnership.service.ts
- src/components/product/product.service.ts
- src/components/project/project-member/project-member.service.ts
- src/components/project/project.service.ts
- src/components/song/song.service.ts
- src/components/story/story.service.ts
- src/components/user/education/education.service.ts
- src/components/user/user.service.ts
- src/core/database/query/lists.ts
Refactor `calculateTotalAndPaginateList` to use the resource classes instead of `securedProperties` for determining sorting.
This is just a stepping stone to remove the need for `securedProperties` everywhere.
We still need to refactor lists to not use _SecurityGroups_ in DB.
I'd like to separate sorting from pagination from hydration as well.
> Remove list securedProperties usage in lists

- package.json
- src/common/date-filter.input.ts
- src/common/index.ts
- src/common/luxon.graphql.ts
- src/common/retry.ts
- src/common/temporal/calendar-date.ts
- src/common/temporal/date-interval.spec.ts
- src/common/temporal/date-interval.ts
- src/common/temporal/date-time.ts
- src/common/temporal/duration.ts
- src/common/temporal/index.ts
- src/common/temporal/interval.ts
- src/common/util.ts
- src/core/config/config.service.ts
- src/core/database/transaction.ts
- yarn.lock
Most of this PR is `DateInterval` which is a range for `CalendarDates`
Our end dates are inclusive. This is different from Luxon's `Interval` where the end point is _not_ inclusive. This is a problem when trying to do date math because we consider a `CalendarDate` to just be midnight of that day.
So when we say March 1st to March 3rd, we _mean_ the interval is 3 days and ends at the end of the day of the 3rd, but Luxon's `Interval` interprets it as 2 days long.
To have Luxon's math work correctly, which works with date times, the end date time needs to be midnight of the 4th. However since we omit the time the fact that this is range is inclusive of 3rd at 23:59:59 but not 4th at midnight is lost.
So `DateInterval` hides all this. You give it the start and end date (1st - 3rd) and all …
> DateInterval

- src/components/engagement/engagement.rules.ts
Allow engagement to transition to finalizing completion when the project is finalizing completion
When the project changes to finalizing completion, our event handler tries to move the engagements
to this as well, but was blocked here.
#1823
> Fix engagement finalizing completion transition

- src/core/database/query.overrides.ts
- src/core/database/subquery.override.ts
Add support for subqueries. These include support for parameters and can be nested.
```ts
.unwind([0, 1, 2], 'x')
.subQuery((sub) => sub
.with('x')
.return('x * 10 as y')
)
.return(['x', 'y'])
```
Compiles to
```cql
UNWIND [0, 1, 2] AS x
CALL {
WITH x
RETURN x * 10 AS y
}
RETURN x, y
```
I'd prefer to have named the method `call` but we've already used that. This is the motivation behind #1843.
Possibly in the future we'll rename. It would need to have an overload for sub queries and for calling procedures.
> Implement sub queries in query builder

- src/components/post/dto/create-post.dto.ts
- src/components/post/dto/post.dto.ts
- src/components/post/dto/shareability.dto.ts
- src/components/post/dto/update-post.dto.ts
- src/components/post/post.service.ts
Fixes #1852
* Must be merged along with its frontend counterpart (https://github.com/SeedCompany/cord-field/pull/829), as this is a breaking change to the frontend
* The existing `Post` nodes in the DB _shouldn't have to be cleared_ as a result of this update. But worth keeping an eye out for any odd behavior relating to this.
> convert post shareable boolean to shareability enum

- src/app.module.ts
- src/common/exceptions/not-implemented.exception.ts
- src/common/fiscal-year.ts
- src/components/engagement/dto/engagement.dto.ts
- src/components/engagement/engagement.module.ts
- src/components/engagement/engagement.repository.ts
- src/components/engagement/engagement.service.ts
- src/components/periodic-report/events/index.ts
- src/components/periodic-report/events/periodic-report-uploaded.event.ts
- src/components/periodic-report/periodic-report-engagement-connection.resolver.ts
- src/components/periodic-report/periodic-report.module.ts
- src/components/periodic-report/periodic-report.repository.ts
- src/components/periodic-report/periodic-report.resolver.ts
- src/components/periodic-report/periodic-report.service.ts
- src/components/progress-summary/dto/index.ts
- src/components/progress-summary/dto/progress-summary.dto.ts
- src/components/progress-summary/handlers/extract-pnp-file-on-upload.handler.ts
- src/components/progress-summary/handlers/index.ts
- src/components/progress-summary/progress-extractor.service.ts
- src/components/progress-summary/progress-report-connection.resolver.ts
- src/components/progress-summary/progress-summary-engagement-connection.resolver.ts
- src/components/progress-summary/progress-summary.module.ts
- src/components/progress-summary/progress-summary.repository.ts
This moves parsing and storing of pnp progress summary data from
```
LanguageEngagement -> PnpData
``` 
to 
```
ProgressReport -> ProgressSummary
```
Backwards compatibility is maintained for reading. However, new files uploaded to engagement.pnp no longer have their summary data parsed. Instead this is only done for progress report files. 
--- 
Wait to merge & deploy until after Blake's pnp migration is ran.
> Progress Report Summary

- src/components/periodic-report/periodic-report.repository.ts
CQB doesn't like empty string for missing label, but rather undefined.
Better to match BaseNode label anyways.
> Fix latest report submitted query

- src/components/product/dto/product-medium.ts
- Remove `OBSTrainers` per Seth. We have no instances of this value in the db.
> Rename product medium OralTranslation > TrainedStoryTellers

- src/components/periodic-report/periodic-report.repository.ts
- src/components/periodic-report/periodic-report.service.ts
- `getLatestReportSubmitted`
- Doesn't need an additional `readOne` query
- `getCurrentReportDue`
- Doesn't need a `Project.readOne` query to determine previous period
- Doesn't need an additional `readOne` query
- `getNextReportDue`
- Now looks ahead to the next report that is due in the future, even if that's passed the current period timeframe.
Fixes #1931
- Doesn't need an additional `readOne` query
This removes 3 db queries on the project overview page.
> Periodic Report query improvements

- src/core/database/cypher.factory.ts
- src/core/database/query-augmentation/index.ts
- src/core/database/query-augmentation/interpolate.ts
- src/core/database/query-augmentation/log-it.ts
I patched `Query.interpolate()` so that all temporal and null/undefined values are rendered correctly.
For example, and abbreviated create project query looked like this previously.
The `createdAt` DateTime was exploded, rendering all its properties.
The `mouEnd`'s value is null but this was just left un-rendered, leaving invalid cypher.
```cql
CREATE (node:Project:TranslationProject:BaseNode { createdAt: { ts: 1624204968472, _zone: {  }, loc: { locale: 'en-US', numberingSystem: , outputCalendar: , intl: 'en-US', weekdaysCache: { format: {  }, standalone: {  } }, monthsCache: { format: {  }, standalone: {  } }, meridiemCache: , eraCache: {  }, specifiedLocale: , fastNumbersCached:  }, invalid: , weekData: , c: { year: 2021, month: 6, day: 20, hour: 11, minute: 2, second: 48, millisecond: …
```
> DB Query Debugging

- src/common/index.ts
- src/common/secured-date.ts
- src/common/secured-property.ts
- src/components/engagement/engagement.resolver.ts
- src/components/partnership/partnership.resolver.ts
- src/components/project/project.resolver.ts
Added
- `Project.mouRange`
- `Partnership.mouRange`
- `Partnership.mouRangeOverride`
- `Engagement.dateRange`
- `Engagement.dateRangeOverride`
This will help the UI where we show these fields as a single field
> Date Range GQL fields

- src/core/database/database.service.ts
- test/engagement-changeset-aware.e2e-spec.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1984
Instead of creating a new relationship prop, I would like to add a new `check` before update property in the changeset.
```
if (changeset) {
const result = await this.db
.query()
.match([
node('changeset', 'Changeset', { id: changeset }),
relation('out', '', 'changeset', { active: true }),
node('node', label, { id }),
])
.return('node.id')
.first();
if (result) {
changeset = undefined;
}
}
```
We could put this logic in the parent method(`updateProperties`) so that it could be called only once.
> Fix edit objects created in changeset

- src/core/database/database.service.ts
- src/core/database/query-augmentation/subquery.ts
- src/core/database/query/create-relationships.ts
- src/core/database/query/deletes.ts
- src/core/database/query/match-project-based-props.ts
- src/core/database/query/matching.ts
This adds an optional parameter to `subQuery()` to import variables.
```diff
- query.subQuery((sub) => sub
-   .with('node')
+ query.subQuery('node', (sub) => sub
```
Importing vars is a common use case and this is shorter.
Downside is it deviates more from the Neo4j doc examples. Weirdly though this `with` clauses used as the import into the sub query is different from normal `with` clauses. It can't do anything other than plainly reference an existing variable; no `as` aliasing or function calls allowed.
Thoughts?
> Sub query import vars shortcut

- src/core/database/query-augmentation/SubClauseCollection.ts
- src/core/database/query-augmentation/foreach.ts
- src/core/database/query-augmentation/index.ts
- src/core/database/query-augmentation/subquery.ts
This can be used with the body as raw strings or with query builder
```ts
.forEach('n', 'nodes(p)', 'SET n.marked = true')
// FOREACH (n IN nodes(p) | SET n.marked = true)
.forEach('year', 'years', (year) => year
.merge(node('y', 'Year', { year: variable('year') }))
)
// FOREACH (year in years |
//   MERGE (y:Year { year: year })
// )
```
Both this and subquery will be formatted as a single line if the body is a single line and less than 80 characters.
```ts
query.subQuery((sub) => sub.return(['null as changeset', '{} as changedProps']))
// CALL { RETURN null as changeset, {} as changedProps }
```
> Query.forEach

- src/components/language/language.repository.ts
- src/components/language/language.service.ts
- src/components/user/user.repository.ts
- src/components/user/user.service.ts
- src/core/database/query/lists.ts
- src/core/database/results/lists.ts
My cypher-fu is stronger now 😎 
This deprecates ~`calculateTotalAndPaginateList()`~ for `paginate()`
- Always returns a single row.
`.first()` is used now instead of having to call via ~`runListQuery()`~ which handled the "no matches" case.
- Doesn't involve sorting.
For simplicity's sake & separation of concerns this doesn't give a sorter option or call the `defaultSorter`.
`defaultSorter` can easily be called explicitly before calling `paginate()`.
- (Best for last) Allows hydrating each item in the requested page. This allows for a single DB query for data instead of "ID list then readOne for each ID".
I've updated user list (8424773) to use new abstractions. This represents the best case scenario as it is 1 call to the database.
Steps:
1. `UserRepository` provides a `hydrate` fragment …
> New Paginate fragment

- src/components/engagement/dto/engagement.dto.ts
- src/components/engagement/engagement.module.ts
- src/components/engagement/engagement.repository.ts
- src/components/engagement/engagement.service.ts
- src/components/engagement/product-connection.resolver.ts
- src/components/product-progress/dto/progress-report.dto.ts
- src/components/product-progress/product-progress.repository.ts
- src/components/product-progress/product-progress.service.ts
- src/components/product/dto/producible.dto.ts
- src/components/product/dto/product.dto.ts
- src/components/product/product.module.ts
- src/components/product/product.repository.ts
- src/components/product/product.service.ts
- src/components/project/engagement-connection.resolver.ts
- src/components/project/project.module.ts
We now expose a `Product`'s `engagement` on it, and an `Engagement`'s `project` on it. So now only the product ID is needed in a GQL query to also retrieve the project & engagement.
I also found that I needed to revert making `ProductProgress` a `Resource`, which has an `id` and `createdAt`. Both of these properties are generated lazily when progress is reported. Therefore it's possible for us to query for progress and receive "empty containers" which will not have these two properties. We want to return these containers even when no `StepProgress` exists to show that it exists. For example, product A has these X reports which it can report progress on. Or vise-versa report B has these Y products it can report progress on.
Anyways that's a breaking change, but it's not live yet. I've left …
> Project.engagement.project resolvers & revert ProductProgress being a Resource

- src/components/product-progress/dto/progress-report.dto.ts
- src/components/product-progress/product-progress.repository.ts
- src/components/product-progress/product-progress.service.ts
- src/core/database/query/matching.ts
Change ProductProgress.steps to include null placeholders.
Also ensured steps are ordered appropriately.
It's much easier to filter out nulls on consumption rather
than having to compose the list based on product's steps & defaulting there.
This just makes more sense.
Because of this id & createdAt have to be excluded. Related to #2039
> ProductProgress.steps null placeholders

- src/components/search/search.repository.ts
- src/components/search/search.service.ts
- src/core/database/database.service.ts
- src/core/database/query-augmentation/interpolate.ts
- src/core/database/query.helpers.ts
- src/core/database/query/cypher-expression.ts
- test/project-workflow.e2e-spec.ts
Rewrite search query to use a full text index instead of scanning with regex.
It was previously incorrectly querying all Security Groups as well without even checking for `read`.
Now it correctly only looks for `read` perms for the nodes that have been matched by the full text index.
This should be a much smaller set to further improve performance.
A later iteration can replace SecurityGroup logic once a sane strategy is determined.
> Full text search

- src/components/authorization/model/resource-map.ts
- src/components/file/directory.resolver.ts
- src/components/file/dto/node.ts
- src/components/file/file.repository.ts
- src/components/file/file.resolver.ts
- src/components/file/file.service.ts
- src/core/database/database.service.ts
DB query reduction:
- `getFileNode`: 2 -> 1
- `getParents`: N+1 -> 1
- `listChildren`: N+1 -> 1
This refactor also brings the queries inline with the rest of the codebase and the queries are more readable.
> Refactor file queries to use subqueries

- src/components/authentication/authentication.repository.ts
- src/components/file/file.repository.ts
- src/core/database/query/matching.ts
- Create index for FileNode IDs
- Update authentication queries so bound variables containing sensitive info are masked
- Change `matchProps` to not use bound parameter for changeset active condition
> Couple DB query tweaks

- src/components/language/language.resolver.ts
- src/components/project/engagement-connection.resolver.ts
- src/components/project/index.ts
- src/components/project/project.loader.ts
- src/components/project/project.module.ts
- src/components/project/project.repository.ts
- src/components/project/project.resolver.ts
- src/components/project/project.service.ts
- src/core/data-loader/index.ts
- src/core/data-loader/loader.decorator.ts
- src/core/data-loader/object-view-aware.loader.ts
- src/core/data-loader/ordered-data-loader.ts
- src/core/data-loader/single-item.loader.ts
- Added abstraction for `DataLoaders` for `ObjectView` aware objects
- Added `DataLoader.primeAll` shortcut so list results can manually prime cache easily. See 1aa0189 for example.
- Created `ProjectLoader` based on this abstraction & using all new changes.
> Data Loaders part 2

- package.json
- src/common/mask-secrets.ts
- src/core/config/config.service.ts
- src/core/core.module.ts
- src/core/database/cypher.factory.ts
- src/core/database/database.module.ts
- src/core/database/query-augmentation/log-it.ts
- src/core/graphql/graphql-logging.plugin.ts
- src/core/graphql/graphql-tracing.plugin.ts
- src/core/graphql/graphql.config.ts
- src/core/graphql/graphql.module.ts
- src/core/graphql/index.ts
- src/core/index.ts
- src/core/tracing/index.ts
- src/core/tracing/sampler.ts
- src/core/tracing/tracing.module.ts
- src/core/tracing/tracing.service.ts
- src/core/tracing/xray-sampler.ts
- src/core/tracing/xray.middleware.ts
- test/utility/create-graphql-client.ts
- yarn.lock
This was originally driven by the need to upgrade to Apollo Server v3 which has support for [`graphql-ws`](https://github.com/enisdenjo/graphql-ws), a newer subscription implementation.
[v3 removed its built in-tracing plugin](https://www.apollographql.com/docs/apollo-server/migration/#tracing). We used this to [log resolver durations](https://github.com/SeedCompany/cord-api-v3/blob/f9c6a6dede2e02fa70aa7220cb97f3ced5095bef/src/core/graphql/graphql-logging.plugin.ts#L53-L69), a crude way of tracking performance.
We really need to have this info as we are optimizing our DB queries. With this built in plugin gone I looked for other solutions.
The first being Apollo Studio, which conveniently still has integrated tracing support via a different avenue. To access this info in Studio you need …
> Integrate AWS X-Ray

- src/components/file/directory.resolver.ts
- src/components/file/dto/node.ts
- src/components/file/file.repository.ts
- src/components/file/file.resolver.ts
Added these fields to `Directory` which will benefit CORD UI & DOMO.
```gql
type Directory {
"""
The `DateTime` a file was most recently modified in this directory or any subdirectories
"""
modifiedAt: DateTime!
"""
The user who uploaded the most recent file in this directory or any subdirectories
"""
modifiedBy: User!
"""
The total size in bytes of all files under this directory and all its subdirectories
"""
size: Int!
"""
The total number of files under this directory and all its subdirectories
"""
totalFiles: Int!
"""
The first file created in this directory or any subdirectories.
This can be useful to determine the "first modified date" of a directory.
"""
firstFileCreated: File
}
```
`modifiedAt/By` ignores actual directory nodes under the current directory. i.e. If I create a …
> Expose more directory aggregate data

- src/components/language/dto/first-scripture.dto.ts
- src/components/language/dto/index.ts
- src/components/language/dto/language.dto.ts
- src/components/language/internal-first-scripture.resolver.ts
- src/components/language/language.module.ts
- src/components/language/language.repository.ts
- src/components/language/language.resolver.ts
This is allows this to be more easily accessed without having to go through all of the language's projects and all of the project's engagements.
Can be accessed like
```gql 
fragment Example on Language {
firstScripture {
canRead
value {
hasFirst
...on InternalFirstScripture {
engagement {
id
}
}
}
}
}
```
> Add Language.firstScripture

- src/components/product/product.service.ts
Since `getAvailableSteps` came about we also use product type to determine in some cases.
These don't always need the methodology, like for Other products.
Supersedes #2255
Fixes #2249
> Fix product logic incorrectly requiring methodology

- src/components/periodic-report/periodic-report-parent.resolver.ts
- src/components/periodic-report/periodic-report.module.ts
- src/components/periodic-report/progress-report-parent.resolver.ts
This will help with the push to change to only need a single ID to lookup reports
> Expose periodic report's parent relation

- src/components/product/handlers/extract-products-from-pnp.handler.ts
- src/components/product/product-extractor.service.ts
- src/components/product/product.service.ts
- We'd give up previously when we finding multiple rows of same book. Now we create products for these rows as long as there's not any other products for these books that haven't already been matched to existing total verses.
- We also still handle a single row that has changed the total verse count, but now this works with multiple rows of the same book as long as the other rows have matched their totals exactly.
So `[14 verses of Mark, 20 verses of Mark]` can change to `[14 verses of Mark, 30 verses of Mark]`.
> Fix product extraction not creating when there are multiple new products

- src/components/product/migrations/SplitScriptureSpanningBooks.migration.ts
- src/core/database/migration/migration-discovery.service.ts
- src/core/database/migration/migration-runner.service.ts
Previously it was only checking a product contained a range that spanned multiple books, i.e. `[Genesis-Exodus]`. But we never allowed that so products actually had `[Genesis, Exodus]`. Updated query condition to check for if the product has any ranges in the current book and any ranges out of the current book.
I found 658 more products that need to be split. I bumped the version of the migration so it runs again.
I also updated the runner to log migration errors and log if it finished with errors instead of incorrectly assuming success.
> Fix split scripture spanning multiple books migration

- src/components/engagement/dto/list-engagements.dto.ts
- src/components/language/language.resolver.ts
- src/components/project/dto/list-projects.dto.ts
- src/components/project/internship-project.resolver.ts
- src/components/project/project.module.ts
- src/components/project/project.resolver.ts
- src/components/project/translation-project.resolver.ts
Many times we only want to work with translation projects & language engagements. This makes that easier
```gql
query {
translationProjects {
items {
languageEngagements {
items {
language { value {
name { value }
}
}}
}
}
}
}
```
I changed `Language.projects` as well to be a secured translation project list. This is technically a breaking change hence the failure, but in practice we never reference this type directly and the structure hasn't changed in a breaking way. 
```gql
query {
language(id: "") {
projects {
items {
languageEngagements {
total
}
}
}
}
}
```
> Improve project & engagement GraphQL DX for concrete types

- src/app.module.ts
- src/common/index.ts
- src/common/url.field.ts
- src/components/file/file-version.resolver.ts
- src/components/file/file.resolver.ts
I created a URL GQL scalar to allow our schema to be more explicit with the data type being returned. I also added validation for when it is used in inputs (webhooks).
I changed `File/FileVersion.downloadUrl` to a URL scalar. This is considered a breaking change but shouldn't require query changes for consumers.
> URL Scalar

- src/core/database/transformer.ts
This only affects environments not in UTC (so probably only local)
> Fix bug parsing DateTime from DB where UTC was mistaken parsed as local

- src/components/scripture/parser.test.ts
- src/components/scripture/parser.ts
```
Genesis 9:18-28; 19: 31-38
```
Now parses successfully.
> [scripture parser] Allow ranges split by semicolon. Handle superfluous spacing better.

- src/common/xlsx.util.ts
- src/components/pnp/findStepColumns.ts
- src/components/pnp/index.ts
- src/components/pnp/isGoalRow.ts
- src/components/pnp/planning-sheet.ts
- src/components/pnp/pnp.ts
- src/components/pnp/progress-sheet.ts
- src/components/product-progress/handlers/extract-pnp-progress.handler.ts
- src/components/product-progress/step-progress-extractor.service.ts
- src/components/product/handlers/extract-products-from-pnp.handler.ts
- src/components/product/product-extractor.service.ts
- src/components/progress-summary/handlers/extract-pnp-file-on-upload.handler.ts
- src/components/progress-summary/progress-summary.extractor.ts
- Created OO wrapper around XLSX. This allows traversal much more expressively and should be easier to read.
Objects for `WorkBook, Sheet, Row, Column, Range, Cell`
- Decoupled extraction logic from cell addresses. This helps with current variations between OBS & Written PnPs. And it should help in future if we need to handle different revisions of the PnP without having to bother the extraction business logic.
- Added support for named ranges & reference them were possible instead of hardcoded columns/rows. This also helps with differences between OBS & Written variants and will hopefully help normalize revisions too.
- Named ranges used: `ProgDraft`, `VE`, `PrcntFinishedYears`, `Q1-4Column`.
> PnP / XLSX Refactor

- src/common/temporal/date-interval.ts
- src/components/engagement/dto/engagement.dto.ts
- src/components/periodic-report/dto/create-periodic-report.dto.ts
- src/components/periodic-report/handlers/abstract-periodic-report-sync.ts
- src/components/periodic-report/handlers/sync-periodic-report-to-project.handler.ts
- src/components/periodic-report/handlers/sync-progress-report-to-engagement.handler.ts
- src/components/periodic-report/migrations/RemoveDuplicatePeriodicReports.migration.ts
- src/components/periodic-report/migrations/index.ts
- src/components/periodic-report/periodic-report.repository.ts
- src/components/periodic-report/periodic-report.service.ts
- src/core/database/query-augmentation/pattern-formatting.ts
- src/core/database/query/create-node.ts
- src/core/database/query/create-property.ts
Fixes #2326
- (fce34bd) Don't create reports if they "shouldn't" exist, but do.
- A report could be pre-existing for a handful of reasons.
- Had a file attached, so it was never deleted
- Date range was changed before financial reporting period was set,
when the period is set, the previous range doesn't account for all former changes.
- Transient errors?
- (11d3d79) Fix periodic report deletes match on both start & end dates, not just start
- 1/1-3/1 != 1/1-1/31
- This matters for financial reports which can switch between periods
- (c0f9784) Fix attempting to remove quarterly reports when financial report period is initially set & set to quarterly
- (a113d01, e568c67) Delete reports outside the current project/engagement range on sync
- There could be a previous date change that wasn't …
> Fix several periodic report sync problems

- src/components/product-progress/handlers/extract-pnp-progress.handler.ts
- src/components/product/product.repository.ts
- src/components/product/product.service.ts
Always match products of story name/scripture refs when extracting pnp progress.
This keeps pnpIndex logic isolated to just product creation/planning extract.
This allows products to be created via UI and then matched to progress extract later.
It also allows products created before this pnpIndex logic was added to still work
with progress extraction.
This partially reverts 652d046.
> Fix product progress extraction to be independent of pnp row index

- package.json
- src/common/fields.pipe.ts
- src/common/index.ts
- src/components/periodic-report/progress-report-parent.resolver.ts
- src/components/project/engagement-connection.resolver.ts
- yarn.lock
- Created `Fields` pipe to grab info for fields requested out of GraphQL's resolve info.
- Created `IsOnlyId` pipe to simplify above to a boolean if only the object's `id` is requested.
- Skip going back to the DB for these relations if we don't need extra info:
- `ProgressReport.engagement`
- `Engagement.project`
> Fields Pipe & Id Shortcut

- patches/cypher-query-builder.patch
- yarn.lock
```ts
.where({ 'node.id': inArray(ids) })
```
This adds a bound parameter, `$id`, whose value is the `ids` list.
However, I noticed that there was a duplicated `$id2` parameter as well in the sent query.
It turns out these values are bound as parameters on `Query.build`.
This makes `Query.build` impure, which is unexpected.
We run the query build a couple times in our abstraction layers (for logging, tracing, etc.)
I patched this library "bug" by memoizing the parameter binding per parameter bag.
The parameter bag only changes with changes to the query.
> Fix bound parameters in where clauses being duplicated

- src/components/periodic-report/dto/list-periodic-reports.dto.ts
- src/components/periodic-report/periodic-report-engagement-connection.resolver.ts
- src/components/periodic-report/periodic-report-project-connection.resolver.ts
- src/components/periodic-report/periodic-report.repository.ts
- src/components/periodic-report/periodic-report.resolver.ts
- src/components/periodic-report/periodic-report.service.ts
- src/components/product-progress/product-connection.resolver.ts
- src/components/product-progress/product-progress-by-product.loader.ts
- src/components/product-progress/product-progress-by-report.loader.ts
- src/components/product-progress/product-progress.module.ts
- src/components/product-progress/product-progress.repository.ts
- src/components/product-progress/product-progress.service.ts
- src/components/product-progress/progress-report-connection.resolver.ts
- src/components/progress-summary/dto/progress-summary.dto.ts
- src/components/progress-summary/progress-report-connection.resolver.ts
- src/components/progress-summary/progress-summary-engagement-connection.resolver.ts
- src/components/progress-summary/progress-summary.loader.ts
- src/components/progress-summary/progress-summary.module.ts
- src/components/progress-summary/progress-summary.repository.ts
- src/core/data-loader/ordered-data-loader.ts
- src/core/database/query/cypher-functions.ts
- Added `periodicReports` query to list reports unrestricted from a single parent.
- Load multiple progress summaries at once (with all periods).
This takes DB queries from `O(3n)` to `O(1)` (when all 3 periods are requested).
- Load progress list for multiple reports at once. `O(n)` to `O(1)`
- Load progress list for multiple products at once. `O(n)` to `O(1)`
> Report list query & progress optimization

- src/core/database/cypher.factory.ts
- src/core/database/indexer/indexer.module.ts
- src/core/database/query-augmentation/log-it.ts
Allow viewing DB queries executed to be viewed at a glance.
Set `database:query` to _debug_ level
```yaml
levels:
database:query: debug
```
View queries ran by introspected name with their given parameters:
> DB query logging (at a glance)

- src/common/context.type.ts
- src/common/exceptions/index.ts
- src/common/exceptions/service-unavailable.exception.ts
- src/common/util.ts
- src/components/authentication/session.interceptor.ts
- src/components/authentication/session.resolver.ts
- src/core/core.module.ts
- src/core/exception.filter.ts
- src/core/graphql/graphql.config.ts
- src/core/logger/formatters.ts
- src/core/timeout.interceptor.ts
- src/core/tracing/xray.middleware.ts
We are still not responding correctly when our responses take too long. ALB gives up and returns generic HTML response. Which our clients then fail to parse as JSON and give up.
This now listens for the response timeout event and throws an exception (which we log & convert same as we do all exceptions).
This should allow us to give correct error response when a timeout happens. Assuming `HTTP_SOCKET_TIMEOUT` env var is less than ALB timeout.
Related to #2381
> Timeout Responses

- src/components/engagement/product-connection.resolver.ts
- src/components/periodic-report/periodic-report.resolver.ts
- src/components/product/dto/product.dto.ts
- src/components/product/product.repository.ts
- src/components/product/product.resolver.ts
Added stubbed `changeset` arg for product & report queries.
```gql
product(id: "", changeset: "")
periodicReport(id: "", changeset: "")
```
Caller can pass these in now, which we'll ignore until we implement it.
Expose project relation on product, so caller need to go through engagement.
```gql
product {
project { ... }
}
```
> Some GQL schema tweaks

- src/common/fiscal-year.ts
- src/common/xlsx.util.ts
- src/components/pnp/planning-sheet.ts
- src/components/pnp/progress-sheet.ts
- src/components/product-progress/step-progress-extractor.service.ts
Fixes #2376 
Exclude step progress if:
- it's completed outside of the project date range
- it's not planned.
This shouldn't make a logical difference as those cells should be undefined anyways, but better safe than sorry.
> Exclude extracting irrelevant step progress

- src/core/database/database.module.ts
- src/core/database/transactional-mutations.interceptor.ts
Previously attempted this manually in #1630 but it was blocked and got stale.
This on the other hand is much cleaner.
> Automatically run all gql mutations in neo4j transactions

- src/components/periodic-report/periodic-report.repository.ts
- src/core/database/dto.repository.ts
Allow DtoRepository to accept a different dto shape from the resource class
Useful for interface repos that work with concretes
> Allow DtoRepository to define concrete shape from interface DTO

- src/components/project/dto/project.dto.ts
- src/components/project/project.repository.ts
- src/components/project/project.resolver.ts
The UI currently shows the total engagements of each project in the project list. To get that number we were listing the engagements for each project. Thus the query was `O(n+1)`.
This changes that to `O(1)` by fetching the total number in the project hydrate query, and if that's the only property requested use it instead of calling the engagement list query.
This does ignore permissions, but I think we previous determined this was ok for just the total count.
> Optimize project list for UI O(n) -> O(1) via engagements.total

- src/common/validators/exactLength.ts
- src/components/language/dto/create-language.dto.ts
- src/components/language/dto/update-language.dto.ts
Add `ExactLength` validator to ensure that properties like `code`, `provisionalCode` and `registryOfDialectsCode` have the proper length.
> Add ExactLength validator

- src/common/name-field.ts
Now this works correctly:
```ts
@NameField({ nullable: true })
address?: string | null;
```
- GQL type is correct calculated to be `String` (nullable)
- If field is nullable: Treat null & empty strings as null
- Previously null was converted to undefined, so it was never persisted to DB
- If field is required: Treat null & empty strings as validation errors
- Previously null was converted to undefined, so it was ignored instead of a validation error
Also made the validation error message cleaner
```diff
- $property must be longer than or equal to 1 characters
+ Cannot be empty
```
Related to  #1747 #2468
> Fix @NameField to handle nullable

- src/core/graphql/graphql-tracing.plugin.ts
- src/core/tracing/xray.middleware.ts
I tried to set up the middleware, so that requests always have a (root) segment.
This way the tracing functions could operate normally and if tracing was not
enabled for the request then the trace data would just be discarded.
This line however seems to be failing while debugging locally
https://github.com/SeedCompany/cord-api-v3/blob/40fa9424c8a4a78f87492550a4c61e129bfee4e0/src/core/tracing/xray.middleware.ts#L63-L63
Ideally this shouldn't happen. I think in the end though it's better to ignore
and move than fail. AWS still runs correctly, so that's really all that matters.
> Don't fail request if there's no tracing segment

- package.json
- src/app.module.ts
- src/common/index.ts
- src/common/rich-text.scalar.ts
- src/common/scalars.ts
- src/core/core.module.ts
- src/core/database/parameter-transformer.service.ts
- src/core/database/transformer.ts
- src/core/graphql/graphql.config.ts
- src/core/scalars.resolver.ts
- yarn.lock
- Unify how scalars are registered & move enumeration to common/
- Ensure usage in schema to prevent compilation errors ("unstable", deprecated queries)
- Define `RichText` scalar, which is a special JSON object
- Store RichText as a string in the database
This happens transparently in practice
> `RichText` scalar & Dynamic scalar registration

- src/components/budget/budget.loader.ts
- src/components/ceremony/ceremony.loader.ts
- src/components/changeset/changeset.loader.ts
- src/components/engagement/engagement.loader.ts
- src/components/ethno-art/ethno-art.loader.ts
- src/components/field-region/field-region.loader.ts
- src/components/field-zone/field-zone.loader.ts
- src/components/file/file-node.loader.ts
- src/components/film/film.loader.ts
- src/components/funding-account/funding-account.loader.ts
- src/components/language/language.loader.ts
- src/components/location/location.loader.ts
- src/components/organization/organization.loader.ts
- src/components/partner/partner.loader.ts
- src/components/partnership/partnership.loader.ts
- src/components/periodic-report/periodic-report.loader.ts
- src/components/post/post.loader.ts
- src/components/product-progress/product-progress-by-product.loader.ts
- src/components/product-progress/product-progress-by-report.loader.ts
- src/components/product/product.loader.ts
- src/components/progress-summary/progress-summary.loader.ts
- src/components/project-change-request/project-change-request.loader.ts
- src/components/project/project-member/project-member.loader.ts
- src/components/project/project.loader.ts
- src/components/story/story.loader.ts
- src/components/user/education/education.loader.ts
- src/components/user/unavailability/unavailability.loader.ts
- src/components/user/user.loader.ts
- src/core/resources/index.ts
- src/core/resources/loader.registry.ts
Previously we had no way of associating a resource with a loader for it; one had to explicitly reference `UserLoader` to get users.
Now we "assign" resources to the loader while registering them.
I'll build upon this in a later PR, but I wanted to get this codebase wide change in separately.
> @LoaderFactory()

- src/components/changeset/changeset-aware.resolver.ts
- src/components/changeset/changeset.repository.ts
- src/components/changeset/changeset.resolver.ts
- src/core/database/query/match-project-based-props.ts
This allows every (changeset aware) resource to ask for their own difference which will return only the changes for their sub tree.
This is still a flat list, so re-creating the sub-tree client side is not possible yet. More to come.
> ChangesetAware.changesetDiff

- package.json
- src/core/email/templates/base.tsx
- src/core/email/templates/forgot-password.template.tsx
- src/core/email/templates/frontend-url.tsx
- src/core/email/templates/project-step-changed.template.tsx
- tsconfig.json
- yarn.lock
New JSX runtime doesn't require React to be wholesale imported just to use JSX syntax. Instead it's handled at the compiler level where the runtime dictates how to transform to raw JS.
New React 18 types don't have `children` implicitly included on component props & FC is deprecated/removed. Adjust our types for these changes.
`mjml-react` is waiting on official React 18 support, but it's only a formality. Manually resolve its dependency as if it did.
This also bumps a lot of `aws-sdk` v3 packages (~3.40.0 -> 3.160.0)
> Bump React to 18 & new JSX runtime

- .eslintrc.yml
- .yarnrc.yml
- nest-cli.json
- package.json
- test/jest-e2e.json
- test/jest-security.json
- tools/jest-ts-transformer-keys.js
- tools/ts-node-register.js
- tools/ts-transformer-keys.js
- tsconfig.json
- yarn.lock
`core/` & `common/` can now be referenced with absolutely with the `~` prefix. This is helpful since all of the codebase uses these.
Now using ts-patch to apply TS transformer plugins via tsconfig.json instead of needing to specify them at every entrypoint (nest, jest, ts-node, etc.)
> Path Aliases & Unified TS plugins

- src/components/authorization/model/resource-map.ts
- src/components/authorization/policy/builder/resource-granter.ts
- src/components/changeset/dto/changeset-diff.dto.ts
- src/components/comments/comment.service.ts
- src/components/post/post.service.ts
- src/components/post/postable.resolver.ts
- src/components/search/dto/search-results.dto.ts
- src/components/search/search.service.ts
- src/core/database/query/create-relationships.ts
- src/core/resources/index.ts
- src/core/resources/loader.registry.ts
- src/core/resources/map.ts
- src/core/resources/resource-map-holder.ts
- src/core/resources/resource-resolver.service.ts
- src/core/resources/resource.decorator.ts
- src/core/resources/resource.loader.ts
- src/core/resources/resources.host.ts
We have a `ResourceMap` object & type to declare what resources are available in the system. This is used in several places both at a type level and programmatically, like for the new Policy builder.
However, the [current map](https://github.com/SeedCompany/cord-api-v3/blob/06efba6a8c82e72e531e5b7423b26506b092ac44/src/components/authorization/model/resource-map.ts#L58-L61) has some downsides.
- All resources have to take an additional step outside of their module to add themselves to this map
- This can cause import problems on bootstrap as any (value) reference to this map causes all the other resources to need to be loaded.
This migrates to a different approach.
Now all resources need to do is declare a decorator (naturally)
```ts
@RegisterResource() // 🎉 
@ObjectType()
export class …
```
> Declare Resources Dynamically

- src/common/calculated.decorator.ts
- src/common/index.ts
- src/common/resource.dto.ts
- src/components/authorization/policy/executor/policy-executor.ts
- src/components/ceremony/dto/ceremony.dto.ts
- src/components/engagement/dto/engagement.dto.ts
- src/components/language/dto/language.dto.ts
- src/components/partnership/dto/partnership.dto.ts
- src/components/periodic-report/dto/periodic-report.dto.ts
We have several fields/lists that are "calculated" by the API. We use a secured property/list interface to be consistent and to expose whether you `canRead` the thing. But this interface also has `canEdit/canCreate/canDelete`, these don't make sense here but need to be set to a boolean. Obviously false is the natural choice, as true wouldn't make sense. We don't provide a mutation for these cases either.
Previously if we were using the authorization system we'd have to manually override the results to set false.
https://github.com/SeedCompany/cord-api-v3/blob/afa6f4f3ff542264419b5eca016650ee26b9f0d3/src/components/partnership/partnership.service.ts#L170-L177
https://github.com/SeedCompany/cord-api-v3/blob/afa6f4f3ff542264419b5eca016650ee26b9f0d3/src/components/periodic-report/periodic-repo …
> Calculated decorator

- src/components/authorization/assignable-roles.granter.ts
- src/components/authorization/authorization.module.ts
- src/components/authorization/dto/beta-features.ts
- src/components/authorization/dto/role.dto.ts
- src/components/authorization/policies/by-feature/project-change-requests-beta.policy.ts
- src/components/authorization/policies/by-role/administrator.policy.ts
- src/components/authorization/policies/by-role/leadership.policy.ts
- src/components/authorization/policies/util.ts
- src/components/authorization/policy/builder/allow-all.helper.ts
- src/components/authorization/policy/builder/as-normalized.helper.ts
- src/components/authorization/policy/builder/child-relationship-granter.ts
- src/components/authorization/policy/builder/granter.decorator.ts
- src/components/authorization/policy/builder/inherit-resource.helper.ts
- src/components/authorization/policy/builder/perm-granter.ts
- src/components/authorization/policy/builder/policy.decorator.ts
- src/components/authorization/policy/builder/prop-granter.ts
- src/components/authorization/policy/builder/resource-granter.ts
- src/components/authorization/policy/granters.factory.ts
- src/components/authorization/policy/granters.ts
- src/components/authorization/policy/index.ts
- src/components/authorization/policy/policy.factory.ts
- src/components/authorization/policy/policy.module.ts
With this new policy system, and even more so with the old system, we have constraints that we have to fit within. We have resources & edges ("edges" meaning properties or relations), each have their set of actions and their fallback rules.
There are times however, when we need to be able to express more within this system.
e..g "Which roles can be assigned to `User.roles`?" 
A path that revealed itself was to create helper "resources" to define the answers to the specific permission questions.
They would define edges that would provide granular points to grant permissions for.
These still have to fit within our constraints above, so essentially this meant that we'd overlay a different meaning on top of the what system expresses.
What does this mean?... ⬇️ 
Well `AssignableRoles` was …
> Custom Resource Policy Granters

- src/common/exceptions/unauthorized.exception.ts
- src/common/resource.dto.ts
- src/common/util.ts
- src/components/authorization/dto/assignable-roles.ts
- src/components/authorization/dto/beta-features.ts
- src/components/authorization/policies/conditions/member.condition.ts
- src/components/authorization/policies/conditions/sensitivity.condition.ts
- src/components/authorization/policy/conditions/aggregate.condition.ts
- src/components/authorization/policy/executor/policy-dumper.ts
- src/components/authorization/policy/executor/policy-executor.ts
- src/components/authorization/policy/lazy-record.ts
- src/components/authorization/policy/policy.module.ts
This adds a service to dump our privileges to an xlsx file.
```
$ yarn repl
> await $(PolicyDumper).write()
```
Also cleaned up a few things & made most sets returned readonly.
> Policy Dumper

- src/common/weak-map-cache.ts
- src/components/authorization/policy/executor/policy-executor.ts
- src/components/user/user.service.ts
- src/core/logger/level-matcher.provider.ts
- src/core/logger/level-matcher.ts
- src/core/resources/resources.host.ts
- src/repl.ts
- test/utility/create-app.ts
I added logic so that some input could be piped into REPL which will be ran and then REPL will exit.
```bash
$ echo '$(PolicyDumper).write()' | yarn repl
```
In reality, it's not REPL at all, but it uses same context/syntax.
---
In doing this I needed some output from the app, but the bootstrap logging was getting in the way. So I wrote, 
```ts
LOG_LEVELS='*=error' yarn repl
```
But it wasn't working because another entry in my `logger.yml` was being matched first. 
So I updated the logic so that ENV levels always take precedence of over `logger.yml` and that takes precedence over `ConfigService.logging` defaults.
---
Renamed `CachedOnArg` to `CachedForArg`. And changed it to use a strong map by default with the option to be weak.
So this is how the old logic works
```ts
@CachedForArg({ …
```
> REPL, LevelMatcher, CachedForArg tweaks 

- src/components/authorization/dto/role.dto.ts
- src/components/authorization/policies/conditions/member.condition.ts
- src/core/database/query/match-project-based-props.ts
The logic in the old system was a user with X role "scoped" to project membership. As the new auth system unwound this logic, it makes more sense to completely separate these concepts. Policies are only considered if the user has the role globally and then if they are a member at all they get X permissions. I've confirmed this with @sethmcknight so here it is.
To facilitate this I added a `member:true` to the `ScopedRole` type and returned it in [`matchProjectScopedRoles`](https://github.com/SeedCompany/cord-api-v3/compare/improve/member-condition#diff-2a99be5f26d1bb73f22d61738715b3c13760d0601500a7f14f1074fa05e0f7a3).
When executing the condition in cypher it's easier too since we can just check for a path existence.
---
I also fixed the stack trace for trailing condition errors when …
> Change `member` condition to ignore roles

- src/common/exceptions/index.ts
- src/common/exceptions/invalid-id-for-type.exception.ts
- src/components/authorization/authorization.service.ts
- src/components/comments/comment.service.ts
- src/components/comments/commentable.resolver.ts
- src/components/post/post.service.ts
- src/core/resources/resources.host.ts
- Add GQL query `commentable`, to load a `Commentable` resource
This is better for UI instead of `commentThreads` query as the the list will always be automatically associated with the parent object; instead of having to manually sync changes to the cached queries for `commentThreads`.
- Throw a new client error (`InvalidIdForType`) when resource id given is not a `Commentable` resource.
Previously, a server schema error was thrown, but this is a client problem.
Other changes:
- Migrate `CommentService` to use `Privileges`
- Update `ResourcesHost.getInterfaces` to use GQL schema when it's available (web server, not CLI/REPL)
- Change `ResourcesHost.getByName` to return an `EnhancedResource`
> Commentable GQL Query + more

- src/components/authorization/policies/conditions/owner.condition.ts
- src/components/authorization/policies/conditions/sensitivity.condition.ts
- src/components/authorization/policy/object.type.ts
- src/components/progress-report/workflow/progress-report-workflow.granter.ts
This limitation was artificial and in practice irrelevant.
Our current usage of context is mainly `sensitivity`, `scope`, which are not secured.
If we needed other secured properties in the future, we could create an internal property to house this value to pass around and use internally.
Odds are even the secured properties that could be needed, like `Project.step`, will still be readable in every place that matters.
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3489703307) by [Unito](https://www.unito.io)
┆Link To Item: https://seed-company-squad.monday.com/boards/3451697530/pulses/3489703307
> Allow secured objects to be used as context for Privileges

- src/core/database/query-augmentation/condition-variables.ts
If a query has a variable with the same name as a parameter, the parameter is not bound.
```ts
.query()
// add bound parameter $variant
.raw('', { variant: "foo" })
// Convert bound parameter to whatever cypher calls a local variable in the query.
.with('$variant as variant')
// Use var to do logic
.matchNode('n', { variant: variable('variant') }) // MATCH (n { variant: variant })
```
Without this PR, the query would not have the `$variant` parameter bound and sent.
Change `Variable` to print `value` instead of `name`.
The `name` is the bound parameter name, prefixed with `$`.
It is actually mutable to keep it unique in the context of the whole query.
This should be allowed & ignored, as variables are stripped out instead of
being turned into bound parameters.
The `value` is always the …
> Fix cypher variable clobbering named parameter

- src/common/index.ts
- src/common/role.dto.ts
- src/common/variant.dto.ts
- src/components/authorization/dto/role.dto.ts
- src/components/authorization/index.ts
- src/components/authorization/model/resource-map.ts
- src/components/authorization/policies/conditions/member.condition.ts
- src/components/authorization/policies/conditions/owner.condition.ts
- src/components/authorization/policies/conditions/sensitivity.condition.ts
- src/components/authorization/policies/conditions/variant.condition.ts
- src/components/product-progress/dto/index.ts
- src/components/product-progress/dto/product-progress.dto.ts
- src/components/product-progress/dto/product-progress.input.ts
- src/components/product-progress/dto/variant-progress.dto.ts
- src/components/product-progress/handlers/extract-pnp-progress.handler.ts
- src/components/product-progress/migrations/AddVariantToProgress.migration.ts
- src/components/product-progress/product-connection.resolver.ts
- src/components/product-progress/product-progress-by-product.loader.ts
- src/components/product-progress/product-progress-by-report.loader.ts
- src/components/product-progress/product-progress.module.ts
- src/components/product-progress/product-progress.repository.ts
- src/components/product-progress/product-progress.service.ts
- src/components/product-progress/progress-report-connection.resolver.ts
- src/components/progress-report/dto/community-stories.dto.ts
- src/components/progress-report/dto/hightlights.dto.ts
- src/components/prompts/dto/prompt-list.dto.ts
- src/components/prompts/dto/prompt-response.dto.ts
- src/components/prompts/prompt-variant-response.repository.ts
- src/components/prompts/prompt-variant-response.service.ts
This is a pretty rough short-term addition. Adds essentially a unique `StepProgress` for each progress variant.
We are assuming `ProgressReport.pnpFile` is only one variant. We are assuming summaries are only available for this variant as well.
I think I've maintained API compatibility, which was a soft goal since this is in production right now.
> Add variants to `ProductProgress`

- src/components/progress-report/workflow/dto/execute-progress-report-transition.input.ts
- src/components/progress-report/workflow/dto/workflow-event.dto.ts
- src/components/progress-report/workflow/progress-report-workflow.repository.ts
- src/components/progress-report/workflow/progress-report-workflow.service.ts
- src/components/progress-report/workflow/resolvers/progress-report-execute-transition.resolver.ts
For the additional notes step on the UI, we needed to allow the API to be aware of the notes object and be able to store them in the DB.
Acceptance criteria:
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3536019095) by [Unito](https://www.unito.io)
> Progress report workflow notes

- src/components/authentication/authentication.repository.ts
SMH that this has taken soon long to be noticed / fixed.
Here's the profiled query (from prod db) that runs to resume the user's session, which happens on EVERY HTTP request.
```diff
- 2,801,240 total db hits in 9,643 ms
+ 1 total db hits in 44 ms
```
(The top left of this graph is the starting point. The other steps below the first 2 are insignificant performance wise).
Before: 
After:
> Create DB indexes for auth tokens

- src/components/authorization/policies/conditions/sensitivity.condition.ts
- src/components/progress-report/dto/community-stories.dto.ts
- src/components/progress-report/dto/hightlights.dto.ts
Here we add a static prop to DTOs to manually mark them as valid for `SensitivityCondition`.
In some cases we dynamically add sensitivity to objects that don't have those props, like `withEffectiveSensitivity`.
But the policies didn't know that the code calling the privileges service were passing this info (sensitivity) since it was dynamic.
With this flag we can communicate that.
There is no check between this flag and the actual caller passing this info, which isn't ideal. But this does allow us to keep using the sensitivity condition in policies only on resources that allow it. In practice the policies reference this manually more times than the service code. So favoring strictness for them vs the service code is a worthy trade.
> Fix CommunityStory & Highlight not allowing sensitivity conditions in policies

- .github/workflows/api-schema.yml
Only specify ref for base case and use default ref for head case. The default ref for pull requests actually creates a merge commit with the base ref.
This is what we want here as the "diff" should be based on new changes going into base, and excluding commits already in base.
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3630679418) by [Unito](https://www.unito.io)
> Fix schema check not including what's already in base ref

- src/core/database/query/create-property.ts
- src/core/database/query/deactivate-property.ts
- src/core/database/query/index.ts
- src/core/database/query/update-properties.ts
- src/core/database/query/update-property.ts
A function to update multiple properties dynamically in a single query.
```ts
.apply(
updateProperties({
resource: User,
changes: {
firstName: 'Carson',
lastName: 'Full',
},
})
)
```
Having this in a query fragment allows all the DB flexibility, via just an ID match with our `DatabaseService.updateProperties`.
For example, the node could match in a different way or _merged/created_ first.
Previously we were not able to achieve above snippet because while properties could be created in the query builder, the generated query referenced these properties explicitly.
```ts
createProperty({
resource: User,
key: 'firstName', // dynamic...kinda
value: 'Carson',
})
```
```cql
CREATE (node)-[:firstName { active: true }]->(:Property { value: 'Carson' })
```
Again, the property key had to be known …
> Add updateProperties query helper

- src/common/role.dto.ts
- src/common/session.ts
- src/components/authentication/authentication.repository.ts
- src/components/authentication/authentication.service.ts
- src/components/authentication/session.interceptor.ts
- src/components/authentication/session.resolver.ts
- src/components/authorization/policy/executor/policy-dumper.ts
- src/components/user/user.service.ts
Closes #2682
Use this header so impersonate a specific user
```http
X-CORD-Impersonate-User: w2mBuPVnkbw
```
Use this header to Impersonate one or more roles
```http
X-CORD-Impersonate-Role: StaffMember, Controller
```
If used with user header the user's roles are added to the ones given here.
In both cases, these are only allowed if the requesting user has permission to "assign" all of the impersonatee's & given roles.
I believe `AssignableRoles` already communicates the restrictions we want here, so I used that.
It's probably worth renaming `assignable` to something else, like maybe `admin`.
> Impersonate roles/users via new HTTP headers

- src/common/url.util.ts
- src/components/file/bucket/local-bucket.ts
- src/core/config/config.service.ts
- src/core/config/environment.service.ts
- src/core/tracing/tracing.module.ts
- src/main.ts
- Replace hardcoded empty `ConfigService.globalPrefix` with pathname of the `HOST_URL` env var
- Convert `ConfigService.hostUrl` to be a URL object
- Fix path joining for `baseUrl`.
Previously, the  scheme's double slash was being messed up.
Also I suspect it didn't work on windows.
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3680083367) by [Unito](https://www.unito.io)
> HOST_URL usage tweaks

- src/components/file/file.service.ts
- src/components/file/files-bucket.factory.ts
- src/components/file/local-bucket.controller.ts
- src/core/config/config.service.ts
- test/file.e2e-spec.ts
- test/utility/create-file.ts
- Drop the `FilesBucketToken` indirection and assume singleton.
It just hasn't been useful.
We can create another token if/when we need another instance.
It was creating a circular dependency with ⬇️ 
- Move `baseUrl` for `LocalBucket` to be determined in factory instead of `ConfigService`.
There's nothing directly configurable about it.
Defined a static class prop for the path prefix as well to DRY registration and usage.
- Changed path prefix from `/file` -> `/local-bucket`
This is more explicit that it's a specific path for the dev feature.
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3680102236) by [Unito](https://www.unito.io)
> Tweak File Bucket Setup 

- src/components/progress-report/variance-explanation/variance-explanation.repository.ts
Turns out it's easier to just carry the null `node` through and allow optional properties, then just default the missing props with a merge.
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3838399505) by [Unito](https://www.unito.io)
> Fix reading partially saved variance explanation

- src/components/progress-report/workflow/transitions.ts
This also controls the order shown in the UI.
Therefore, these should generally flow down.
"back transactions" should come before/above "forward transactions".
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3841285368) by [Unito](https://www.unito.io)
> Reorder progress report transition entries

- src/common/temporal/duration.ts
- src/core/database/cypher.factory.ts
- src/core/database/query-augmentation/index.ts
- src/core/database/query-augmentation/summary.ts
- src/core/logger/formatters.ts
```ts
db.query()
...
.executeAndLogStats()
```
```
[database:results:stats] X.update +15ms { nodesCreated: 1, propertiesSet: 4, labelsAdded: 1 }
```
stats are also returned for programmatic usage. Also `executeAndReturnStats` to use without logging.
```ts
Duration.fromObject({ minutes: 10 });
```
```
[Duration] 10 min
```
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3880051083) by [Unito](https://www.unito.io)
> Cypher Query Summary / Stats

- src/components/prompts/prompt-variant-response.service.ts
If the variant response didn't exist before,
then it wasn't in the array so our new modifiedAt was missed. Now we loop through all variants,
and create the new variant response when needed.
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3929395445) by [Unito](https://www.unito.io)
> Fix `VariantResponse.modifiedAt` on first save

- src/components/progress-summary/progress-summary.extractor.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3939152217) by [Unito](https://www.unito.io)
> Fix progress summary percent/verse equivalent check for numbers like 1.00000001

- src/components/authorization/policies/by-role/marketing.policy.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3967763981) by [Unito](https://www.unito.io)
> Tweaked Progress Report permissions in Marketing Policy.

- src/components/authentication/session.resolver.ts
This allows the UI to correctly know the logged in user, even while impersonating.
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3992616000) by [Unito](https://www.unito.io)
> Expose impersonator user via session when applicable

- src/components/progress-report/dto/progress-report.entity.ts
- src/components/progress-report/workflow/resolvers/progress-report-transitions.resolver.ts
- Removed check for editing status in transitions progress report transitions resolver
- Marked status field as calculated
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3994140486) by [Unito](https://www.unito.io)
> Treat `ProgressReport.status` as calculated

- src/components/authorization/policies/by-role/marketing.policy.ts
Allow viewing of all variants for Team News and Community Stories.
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3999734250) by [Unito](https://www.unito.io)
> Tweaked Marketing Policy for Team News and Community Stories

- src/components/progress-report/migrations/UpdateExplanationReasons.migration.ts
- src/components/progress-report/progress-report.module.ts
- src/components/progress-report/variance-explanation/reason-options.ts
In this PR the following were done:
- Created a migration to update the saved reason values in the database
- Changed the values in the reasons list so the API can send to the UI the appropriate list
This should close #2754 
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/4125434166) by [Unito](https://www.unito.io)
> Explanation of progress migration to update saved reasons

- src/components/authorization/policies/by-role/marketing.policy.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/4149954291) by [Unito](https://www.unito.io)
> Fix marketing access to Progress Report workflow by making status readable

- .github/actions/setup/action.yml
- Dockerfile
- package.json
Apparently alpine is meant for embedded devices, and though it is smaller, there's a performance trade off.
Switching to slim which uses the official glibc instead of the musl implementation.
https://snyk.io/blog/choosing-the-best-node-js-docker-image/
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/4180775743) by [Unito](https://www.unito.io)
> Node 16 -> 18. Alpine -> Slim

- src/components/file/dto/upload.dto.ts
- src/components/file/file.service.ts
- src/components/product/migrations/ReextractPlanningPnps.migration.ts
This avoids an error where a name wasn't specified on the first defined file upload.
This was because we'd try to fetch the file which would be invalid,
because there weren't any versions.
In practice (in UI), the name is always given.
So while this is technically a breaking change,
it should be fine to roll out whenever.
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/4226989640) by [Unito](https://www.unito.io)
> Require filenames on defined file version upload (soft breaking)

- src/components/file/bucket/file-bucket.ts
- src/components/file/bucket/filesystem-bucket.ts
- src/components/file/bucket/local-bucket.ts
- src/components/file/bucket/s3-bucket.ts
- src/components/file/file.service.ts
- src/components/file/files-bucket.factory.ts
- src/core/config/config.service.ts
This fixes a fresh cache url pointing to an invalid s3 url.
This moves the signing expiration from the Bucket layer to the FileService layer. This makes more sense as it's a business decision vs the actual persistence logic.
I also took the opportunity to refactor to use aws-sdk v3 command classes.
Doing it this way with generics is more elegant, as we don't need to explicitly reference actions and their input options in bucket abstraction.
---
In the future, maybe we can set the S3 files to be public if they are in cord, and skip url signing for them. That would allow us to increase our caching duration. Another option would be to put a CDN in front, I think that would allow the CDN to serve the fresh cached file directly instead of redirecting to a stale pre-signed url.
┆Issue is …
> Sync S3 signing expiration with http cache

- src/components/file/bucket/composite-bucket.ts
- src/components/file/bucket/file-bucket.ts
- src/components/file/bucket/index.ts
- src/components/file/bucket/parse-uri.test.ts
- src/components/file/bucket/parse-uri.ts
- src/components/file/bucket/readonly-bucket.ts
- src/components/file/bucket/s3-bucket.ts
- src/components/file/files-bucket.factory.ts
- src/core/config/config.service.ts
This allows more flexibility when a database is moved around while still allowing the files to backed by the original bucket.
```env
FILES_SOURCE=s3://prod-support, s3://prod:readonly
FILES_SOURCE=./files, s3://a-bucket:ro
FILES_SOURCE=memory://, file://./test/fixtures
```
Updated S3 to support paths as well if a unified bucket is desired.
```env
FILES_SOURCE=s3://cord/prod-support, s3://cord/prod:readonly
```
FYI not having any writable sources right now just throws a server error. It's allowed, but probably not handled well.
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/4265290932) by [Unito](https://www.unito.io)
> Handle multiple file bucket sources & allow readonly

- src/components/authorization/policies/by-role/financial-analyst.policy.ts
@CarsonF - We think that this change will solve the issue of an FA not being able to view a Partner that is not attached to a project yet.  This is problematic currently when an FA creates a new Partner and then can't see it.
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/4285173590) by [Unito](https://www.unito.io)
> removed organization property

- src/core/database/cypher.factory.ts
- src/core/database/database.service.ts
- src/core/database/errors.ts
- src/core/graphql/gql-context.host.ts
- src/core/logger/formatters.ts
Connection errors are not related to the db queries making them, so I removed the stack trace from them.
I also stripped out the "routing table" verbiage as it is empty & useless for these connection errors.
```yaml
logger: nest
message: Failed to connect to CORD database
exceptions:
- type: ServiceUnavailableError
message: "Could not perform discovery. No routing servers available. Known
routing table: RoutingTable[database=default database, expirationTime=0,
currentTime=1681238029665, routers=[], readers=[], writers=[]]"
stack: >-
Neo4jError: Could not perform discovery. No routing servers available.
Known routing table: RoutingTable[database=default database,
expirationTime=0, currentTime=1681238029665, routers=[], readers=[],
writers=[]]
: 
at AuthenticationRepository.saveSessionToken …
```
> Improve logging of Neo4j connection errors

- src/common/field-selection.ts
- src/common/fields.pipe.ts
- src/common/index.ts
This was a journey and hopefully this PR description and the new code better describes the actual use cases and when to use the available functionality.
Previously with `Fields` I was limiting the types to filter out any irrelevant types. I do not know why I was doing this, because GQL already enforces that irrelevant types are not spread into a field selection. It turns out I was limiting the types too much, and breaking some use cases.
Like this one
```gql
query {
periodicReport(id: "") {
parent {
id
...on Engagement {
project { id }
}
}
}
}
```
If the report was a `ProgressReport`, the `parent` was [declared](https://github.com/SeedCompany/cord-api-v3/blob/d7583b355396a7e1268df946654e6ca06ff1d62e/src/components/progress-report/dto/progress-report.entity.ts#L38-L39) as a …
> Refactor Fields into FieldSelection to be more flexible

- src/components/partnership/dto/financial-reporting-type.ts
@bryanjnelson @CarsonF ,  The [ticket](https://seed-company-squad.monday.com/boards/3451697530/views/78801638/pulses/4488797704) in Monday says we should notify the DOMO team before merging this into production. The field currently being passed to Domo with the "Funded" or "Field Engaged" values is named FinRptType, so I believe the Hybrid value should do the same and no other changes are needed in the DOMO sets, but let me know if my thinking is wrong.
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/4804165841) by [Unito](https://www.unito.io)
> Added hybrid financial reporting type

- Dockerfile
- src/components/timezone/timezone.service.ts
Fixes #664
Previously, we only cached the data for 5 minutes. This data actually only changes around once a month.
Instead, we will grab it at build and save it to the image. This way it will be automatically fresh as of build time, and we won't rely on GitHub in production.
For dev mode, we will just grab it anytime it doesn't exist on disk.
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/4807021557) by [Unito](https://www.unito.io)
> Change timezone data caching strategy

- src/components/progress-summary/progress-summary.repository.ts
It appears that collecting inside the subquery was not changing the cardinality of the overall result.
Moving out of subquery fixes this.
Regression from f6f06f67a8391e82aec3e33e2a0b1546f5ea80cf
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/4828835696) by [Unito](https://www.unito.io)
> Fix progress summary query

- src/components/comments/comment.service.ts
- src/components/language/dto/language.dto.ts
- src/components/partner/dto/partner.dto.ts
- src/components/post/dto/postable.dto.ts
- src/components/post/postable.resolver.ts
- src/components/project/dto/project.dto.ts
- src/core/resources/resources.host.ts
```ts
getByName('Foo')
```
was not erroring out even though we explicitly know "Foo" is not in the `ResourceMap`.
Splitting the out the `getByDynamicName` method fixes this.
---
Refactored some of the logic in comments service for use in other modules.
---
Sorry @brentkulwicki with some of these stricter types, I couldn't get away without fixing some of the Postable stuff we just talked about.
> Refactor some dynamic resources code

- package.json
- yarn.lock
Idk about this ⬇️ 
> Use UTC interpretation of Date objects for date cells (potentially breaking)
https://git.sheetjs.com/sheetjs/sheetjs/src/branch/master/CHANGELOG.md
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/4806959056) by [Unito](https://www.unito.io)
> Bump xlsx 18.5 -> 20.0

- src/components/authentication/dto/register.dto.ts
- src/components/budget/dto/budget-record.dto.ts
- src/components/budget/dto/budget.dto.ts
- src/components/changeset/dto/changeset.dto.ts
- src/components/comments/dto/commentable.dto.ts
- src/components/engagement/dto/engagement.dto.ts
- src/components/file/dto/node.ts
- src/components/partner/dto/partner.dto.ts
- src/components/partnership/dto/partnership.dto.ts
- src/components/periodic-report/dto/periodic-report.dto.ts
- src/components/product/product.service.ts
- src/components/progress-report/dto/progress-report.entity.ts
- src/components/project-change-request/dto/project-change-request.dto.ts
- src/components/project/dto/project.dto.ts
- src/components/prompts/prompt-variant-response.repository.ts
- src/components/scripture/dto/scripture-reference.dto.ts
- src/core/database/changes.ts
- src/core/validation.pipe.ts
- tsconfig.json
This opts in to the new (and future default) functionality.
This actually tells TS to emit properties at runtime.
This is opt-in because it's a breaking change for places we "override" a property.
We do this to narrow the parent type to a stricter one or just to declare a decorator.
With this new functionality, these spots would actually override the parents initial property.
Technically for us though it doesn't make a difference.
This TS says these are errors unless we give an initial value to these override spots.
Marking them as `declare` means no new runtime property will be emitted, and it's just the parent class's property that will be used. Which makes sense and would be what we want if it actually mattered (if these weren't just shapes).
Because these properties are non emitted to …
> Migrate to new ECMA class fields

- src/common/email-field.ts
- src/common/index.ts
- src/components/authentication/dto/login.dto.ts
- src/components/authentication/dto/passwords.dto.ts
- src/components/user/dto/check-email.dto.ts
- src/components/user/dto/create-person.dto.ts
- src/components/user/dto/update-user.dto.ts
`null` -> `""` with lodash function, which was then an invalid email.
Fixes https://seed-company-squad.monday.com/boards/3451697530/pulses/4579760959
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/4861471586) by [Unito](https://www.unito.io)
> Fix email lower case transform overruling explicit null input

- package.json
- src/app.module.ts
- src/common/url.util.ts
- src/components/file/bucket/local-bucket.ts
- src/components/partnership/partnership.repository.ts
- src/core/config/environment.service.ts
- tsconfig.json
- yarn.lock
With the libs explicit, `got` upgraded, and `highlight.js` gone, we have successfully stripped out the DOM globals.
Which is awesome, because this is not a browser env.
I added a check to ensure we at least get notified if that ever changes (i.e. we add/upgrade a lib that adds them back in).
And I fixed references to global `URL` & `Node`.
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/4877698826) by [Unito](https://www.unito.io)
> No DOM lib

- .eslintrc.cjs
- .vscode/launch.json
- jest.config.ts
- package.json
- src/components/authentication/authentication.service.ts
- src/components/engagement/engagement.service.ts
- src/components/language/language.service.ts
- test/jest-e2e.json
- test/jest-security.json
- test/jest-setup.ts
- tsconfig.build.json
- tsconfig.json
- yarn.lock
- Tests now do not need to call out a specific config file 🎉 
This is much better for IDE integration, as now the IDE can invoke jest for any type of test without breaking on not using the right config flag.
- Config is TS instead of JSON 🎉 
- Yarn scripts are changed to filter to certain files to maintain previous functionality.
- Dropped aliases with easy flags.
```diff
- yarn test:watch
+ yarn test --watch
- yarn test:cov
+ yarn test --coverage
- yarn test:debug
+ yarn test
```
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/4909977957) by [Unito](https://www.unito.io)
> Unify jest config into single TS file

- src/components/authorization/policies/by-role/financial-analyst.policy.ts
- src/components/authorization/policies/by-role/project-manager.policy.ts
- src/components/authorization/policies/by-role/regional-director.policy.ts
- src/components/authorization/policy/executor/policy-executor.ts
Here's an example of something being ignored.
https://github.com/SeedCompany/cord-api-v3/blob/ad02252edfda9eb300e3c15282aceabac3fb661e/src/components/authorization/policies/by-role/consultant-manager.policy.ts#L20-L20
It was falling back to organization object level _read_ instead of using the absence of actions explicitly called out on the `address` property.
> Fix policies incorrectly defaulting to object level action when a property is specifically called out

- package.json
- src/common/search-camel-case.ts
- src/common/util.ts
- src/components/authorization/policy/conditions/aggregate.condition.ts
- src/components/authorization/policy/executor/policy-dumper.ts
- src/components/progress-report/workflow/progress-report-workflow.granter.ts
- src/core/resources/resources.host.ts
- yarn.lock
With REPL
```ts
await $(PolicyDumper).dump('<role>', '<resource>')
```
With CLI
```bash
yarn console policy:dump <role> <resource>
```
- `langEng` -> `LanguageEngagement`
- `VarExp` -> `ProgressReportVarianceExplanation`
- `rcc` -> `RegionalCommunicationsCoordinator`
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/4933361952) by [Unito](https://www.unito.io)
> Add command to print Privileges (Policies) to CLI for queried roles/resources

- src/components/ethno-art/ethno-art.repository.ts
- src/components/ethno-art/ethno-art.service.ts
- src/components/film/film.repository.ts
- src/components/film/film.service.ts
- src/components/product/dto/producible.dto.ts
- src/components/product/dto/product.dto.ts
- src/components/product/product.repository.ts
- src/components/product/product.service.ts
- src/components/prompts/prompt-variant-response.repository.ts
- src/components/story/story.repository.ts
- src/components/story/story.service.ts
- src/core/database/db-type.ts
- src/core/database/dto.repository.ts
- src/core/database/index.ts
Now we have
```
DB Type -> Unsecured Type -> Type
```
This let's us handle DB results separately from the securing/authorization logic.
As we now do with the product's scripture references.
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/4995334605) by [Unito](https://www.unito.io)
> Separate DB Type from Unsecured Type / Refactor Product Scripture Parsing

- src/core/config/config.module.ts
- src/core/core.module.ts
- src/core/exception/exception.normalizer.ts
- src/core/graphql/graphql-logging.plugin.ts
- src/core/graphql/graphql.config.ts
- [Fix ExceptionNormalizer dependency on ~/core](https://github.com/SeedCompany/cord-api-v3/commit/eb49b602744ef931253b8655dc9e5c05e456d84f) 
Part of this is allowing `ConfigService` to be accessed by a string instead of the class ref
- [Unify ApolloServer error handling with our global exception filter](https://github.com/SeedCompany/cord-api-v3/commit/926e813e1241e96800b73f796a731416558e4a05) 
Previously, some paths were not running through our exception filter.
This may have been from the Apollo Server v4 upgrade.
I noticed this with error through from a field resolver.
All error -> output is handled in a unified spot.
Now we check codes instead of regex matching messages, win.
- [Remove error logging from GraphqlLoggingPlugin](https://github.com/SeedCompany/cord-api-v3/commit/d8eff902c …
> Fix Apollo Server v4 error handling

- src/components/post/dto/postable.dto.ts
- src/components/post/post.service.ts
- src/components/post/postable.resolver.ts
- src/core/resources/resources.host.ts
- [Give a better error message when ResourceHost encounters null input](https://github.com/SeedCompany/cord-api-v3/commit/11caf17d7daeec8a460c5d12ec72c00b470236d0)
- [Change how Postable asks for __typename](https://github.com/SeedCompany/cord-api-v3/commit/c95fa372005ba6bf9c3fb51889eda2d3b28ba5fd) 
Stop requiring implementations to declare the `__typename` field.
This apparently was tricky for TS as it was missed in the _Project_ shapes.
This string can also be gotten from GraphQL or `ResourceLoader`,
so it's not always necessary to specify manually.
Instead, we'll change types to only ask for `__typename`
when the `PostableRef` is an actual `Postable` object.
- [Fix regression](https://github.com/SeedCompany/cord-api-v3/commit/6220c2894664d090425468f361c17b14038824d6) from d6790f0 where …
> Fix `Postable.posts` resolution error

- src/components/progress-summary/progress-summary.extractor.ts
Revised the logic so the progress summary will only bypass from being saved to the database if both the planned and actuals are zero.
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5092410564) by [Unito](https://www.unito.io)
> revised logic for progress summary

- src/components/file/file.repository.ts
- src/components/file/file.service.ts
- src/components/file/media/detect-existing-media.migration.ts
- src/components/file/media/media-detector.service.ts
- src/components/file/media/media.module.ts
- src/components/file/media/media.service.ts
I think this ends up being better in every way.
NodeJS doesn't have to worry about piping streams, and the hangs that were occurring there.
Additionally, even when the previous process worked, we got a detected duration of 0. This is some difference with ffprobe.
Input streams would give this, but files/urls are detected correctly.
I upgraded the migration as well to re-detect any existing media that has a duration of 0.
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5095334479) by [Unito](https://www.unito.io)
> Refactor ffprobe to use signed url instead of piped s3 object stream

- Dockerfile
- src/components/file/media/media-detector.service.ts
If `ffprobe` is in `PATH`, then use that as It's more likely that it's to update since it uses
(1st party?) native package manager releases.
The npm one is only manually updated/published.
It'll be good for fallback/dev, but native will be better.
The npm linux version segfaults with urls, so this fixes that.
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5110763105) by [Unito](https://www.unito.io)
> Use native ffprobe

- src/components/file/media/detect-existing-media.migration.ts
- src/components/file/media/media.repository.ts
- src/components/file/media/media.service.ts
I was mistakenly creating multiple media nodes with each migration attempt.
This fixes that by merging, so a media node is only created when needed.
I could've done other ways too, but this seems better as now it's idempotent.
Also dropping duplicate media nodes as well.
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5111740158) by [Unito](https://www.unito.io)
> Unify media saving queries / Fix duplicate media nodes

- src/components/file/dto/node.ts
- src/components/file/events/after-file-upload.event.ts
- src/components/file/file.repository.ts
- src/components/file/file.service.ts
- src/components/file/handlers/attach-project-root-directory.handler.ts
- test/utility/create-directory.ts
Part of work for #2883, pulled out as this logic can stand on its own.
- `FileNode`'s now return the `root` `FileNode` from the DB
- `FileNode`'s now return the _resource_ and _relation_ the _root_ `FileNode` is attached to.
This allows other parts of the application to start doing more complex logic with these files.
For example, authorization has mostly been stubbed. This is the first step in knowing where the file "lives" under, in order to facilitate more fine grain checks.
This change requires `FileNode`'s to not be orphaned. This affects how project's root directories were created. So that has been refactored, and now is one less DB call too.
I also added an event for `AfterFileUpload`, which doesn't relate at all other than being in the file service. It will allow other parts of …
> Add the root node and resource attached to root node to hydrated FileNode

- src/common/create-and-inject.ts
- src/common/index.ts
- src/common/poll.ts
- src/components/file/media/events/can-update-event.ts
- src/components/file/media/media.dto.ts
- src/components/file/media/media.loader.ts
- src/components/file/media/media.module.ts
- src/components/file/media/media.repository.ts
- src/components/file/media/media.service.ts
Part of work for #2883, pulled out as this logic can stand on its own.
The biggest goal of this PR is to allow authorization to the `updateMediaMetadata` mutation to be configurable.
This is a generic mutation, but its objects are nested within other objects whose access is more fine tuned. We've basically ignored this concept so far in the application and assumed good actors...so here's the first step into fixing that.
I tried a few things here, that I'm not completely sure about. Just trying to see how it played out. Happy to receive feedback about it.
The first is [polls](https://github.com/SeedCompany/cord-api-v3/blob/bf2dc3d86341fa53a4410cbb630e8181ceee3782/src/common/poll.ts). We needed event handlers to be communicate values back to the event source. 
My starting point was that …
> Media 1.1 / Polls / Event Injection

- src/components/file/bucket/composite-bucket.ts
- src/components/file/bucket/file-bucket.ts
- src/components/file/bucket/local-bucket.ts
- src/components/file/bucket/readonly-bucket.ts
- src/components/file/bucket/s3-bucket.ts
- src/components/file/local-bucket.controller.ts
This was a known issue, because the `LocalBucketController` was not referencing the `FileBucket` interface but rather checking if the instance was a `LocalBucket`. This wasn't really a problem until I introduced the `CompositeBucket` and `ReadonlyBucket`. With these wrappers in mix, the `instanceof` check fails.
This is resolved by exposing the validation & parsing of signed urls from the `FileBucket` interface.
This allows the wrappers to forward the calls on dynamically.
With both that and the `putObject` methods in the interface, the controller can use those; replacing the `LocalBucket.upload()/download()` calls.
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5196462075) by [Unito](https://www.unito.io)
> Fix local file urls when using multiple file sources

- src/components/authentication/authentication.service.ts
Situation is: caller calls session query with impersonation while not logged in.
Previously we threw an error that the impersonation was unauthorized.
This prevented the caller from ever establishing a session to login with.
Now we will just ignore their impersonation input if they are not logged in.
This allows a session to be established and login to be preformed.
After that point any operations will continue to error out if they are not authorized.
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5203896421) by [Unito](https://www.unito.io)
> Only enable impersonation if logged in

- src/components/authentication/login.resolver.ts
- src/components/authentication/password.resolver.ts
- src/components/authentication/register.resolver.ts
I'd love to use a directive for this, but directives don't come through introspection.
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5204470159) by [Unito](https://www.unito.io)
> Note in schema which operations have sensitive secrets

- src/components/progress-report/media/dto/media-list.dto.ts
- src/components/progress-report/media/resolvers/list.resolver.ts
This list includes variants that are read only.
This list can be used in the UI to provide a unified list, matching existing variants or providing placeholders.
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5234603840) by [Unito](https://www.unito.io)
> Supercede PR Media `uploadableVariants` -> `availableVariants`

- src/core/database/query/deletes.ts
Don't require nodes with relationships pointing to the node being deleted to have `BaseNode` label.
`VariantGroup` doesn't have these so that was causing a bug. But also, this requirement never really made sense. It just never came up until now.
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5237005640) by [Unito](https://www.unito.io)
> Don't require `BaseNode` label when marking relationships as inactive when deleting nodes

- src/components/partner/partner.service.ts
- src/core/database/common.repository.ts
We'll always want to do this, so do it once here.
Using a custom exception class as well, so the consumer can get a list of invalid IDs back programmatically.
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5270307212) by [Unito](https://www.unito.io)
> Move invalid ID validation into updateRelationList method

- src/core/graphql/graphql.module.ts
graphql-upload was being invoked on many hack attempt routes, which are spamming logs with invalid input errors.
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5289496451) by [Unito](https://www.unito.io)
> Limit graphql middleware to graphql routes

- package.json
- src/repl.ts
- yarn.lock
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5351924515) by [Unito](https://www.unito.io)
> Abstract REPL setup complexity in new @seedcompany/nest library

- src/components/scripture/book-difficulty-factor.test.ts
- src/components/scripture/book-difficulty-factor.ts
@atGit2021 did all the hard work of narrowing the `NaN` down to this function returning `undefined`.
```ts
undefined * x == NaN
```
I fixed the Psalms name from [the name change](https://github.com/SeedCompany/libs/commit/3bf0f68fdb98b3f3d47aa4bb7422f6fbdcb4d362), added tests to ensure our book map is exhaustive, and am returning `0` as factor when book cannot be found as a last chance safety check.
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5353627293) by [Unito](https://www.unito.io)
> Fix NaN from missing difficulty of book

- src/components/product/migrations/fix-nan-total-verse-equivalents.migration.ts
- src/components/product/product.module.ts
@CarsonF could you help me with the cypher query?  I'm getting back an empty array, so not sure how to pull ScriptureRange for both the scriptureReferences (Direct Scripture Products) and the scriptureReferencesOverride (Derivative Scripture Products) as a collection.
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5394965702) by [Unito](https://www.unito.io)
> Recalc total verse equivalents saved as NaN

- dbschema/ceremony.esdl
- dbschema/common.esdl
- dbschema/engagement.esdl
- dbschema/language.esdl
- dbschema/migrations/00002.edgeql
- dbschema/project-member.esdl
- dbschema/project.esdl
- dbschema/role.esdl
- dbschema/sensitivity.esdl
- dbschema/user.esdl
- dbschema/z.owned.esdl
- dbschema/z.pinnable.esdl
- dbschema/z.taggable.esdl
- src/core/edgedb/generate.ts
Most parts of these objects are done:
- User
- Project
- Engagement
- Language
- Ceremony
- Project Member
Key points have been worked out:
- How sensitivity & (project) membership can be declared across schema objects for authorization system
- How sensitivity is calculated for translation projects (triggers written)
- Good direction on some conventions, like module organization.
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5419271928) by [Unito](https://www.unito.io)
> EdgeDB CORD Schema Part 1

- .vscode/launch.json
This is a newer version of the config for one of the most popular Jest plugins for VSCode.  This modifies the entry originally placed here about 3 years ago.  😮 
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5429187741) by [Unito](https://www.unito.io)
> Update the vscode/launch.json file with newer settings for Jest extension debug option

- src/core/edgedb/edgedb.module.ts
- src/core/edgedb/edgedb.service.ts
- src/core/edgedb/edgeql.ts
- src/core/edgedb/generate.ts
- src/core/edgedb/index.ts
- src/core/edgedb/reexports.ts
I know the edgedb team pushes for the query builder, and they want it to be as close to EdgeQL syntax as possible. It's certainly closer than what we have with our cypher query builder, but it's not quite there.
This is why I went through the effort of supporting `*.edgeql` query files which could be used in app code.
However, I fear that the query builder will still be favored over these files because small queries can be contained in a block of code rather than a whole exclusive file. This is a bit concerning, because the QB does have rumors of being hard on TS and the aforementioned cypher QB headache.
This is why I'm introducing support for typed query strings inline in TS files...
```ts
import { edgeql, EdgeDB } from '~/core/edgedb';
class Repository {
constructor(private db: EdgeDB) …
```
> Generate typed inline queries using new `edgeql()` wrapper

- dbschema/ceremony.esdl
- dbschema/common.esdl
- dbschema/engagement.esdl
- dbschema/language.esdl
- dbschema/migrations/00005.edgeql
- dbschema/migrations/00006.edgeql
- dbschema/migrations/00007.edgeql
- dbschema/migrations/00008.edgeql
- dbschema/migrations/00009.edgeql
- dbschema/migrations/00010.edgeql
- dbschema/migrations/00011.edgeql
- dbschema/migrations/00012.edgeql
- dbschema/migrations/00013.edgeql
- dbschema/migrations/00014.edgeql
- dbschema/migrations/00015.edgeql
- dbschema/migrations/00016.edgeql
- dbschema/migrations/00017.edgeql
- dbschema/migrations/00018.edgeql
- dbschema/migrations/00019.edgeql
- dbschema/migrations/00020.edgeql
- dbschema/migrations/00021.edgeql
- dbschema/project-member.esdl
- dbschema/project.esdl
- edgedb.toml
This builds upon #2922. It established the pattern for how a project's sensitivity and current user's membership is shared for all types under a project, engagement, products, partnerships, etc.
However, we still have the use case of Languages, Partners, etc. These also use their related project's sensitivity and membership to determine authorization. It's just that they need aggregate multiple projects instead of a single one.
I had `isMember` and `effectiveSensitivity` defined on `Language`, and this is useful when we are looking at a language directly.
```
select Language {*}
filter .effectiveSensitivity <= Sens.Medium
```
This would indeed work for language queries and access policies. So I thought I had the problem solved, though admittedly a bit clumsy for these handful of types …
> EdgeDB Project Context Schema

- dbschema/language.esdl
- dbschema/project.esdl
- dbschema/z.named.esdl
This makes it easy to grab a name from a polymorphic query.
I'm hoping we can rework user to also use this. Producibles & Files can also use this.
```
select Resource {
id,
[is Mixin::Named].name
}
```
I think this will come in handy for Search as well.
Also added some constraints for a trimmed string, so "Foo " becomes "Foo" and "   " becomes null & constraint error.
It's as a function so we could choose to apply it to more places.
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5488033422) by [Unito](https://www.unito.io)
> Move Language/Project name to `Mixin::Named`

- src/components/admin/admin.service.ts
- src/components/authentication/authentication.repository.ts
- src/components/authentication/authentication.service.ts
- src/core/config/config.service.ts
- src/core/database/cypher.factory.ts
- src/core/database/database.service.ts
- src/core/database/errors.ts
- src/core/database/indexer/indexer.module.ts
- src/repl.ts
Many of these improvements are just restoring functionality that regressed with recent neo4j upgrades.
I changed REPL to not wait for neo4j indexes or admin setup. This is almost never needed.
I changed the root admin session to be lazily loaded, so REPL can start without it.
This will load the root user ID when the DB connection becomes available.
If trying to access `session.userId` before DB connection is established / ID is loaded an error is thrown.
`await session` will wait for the ID to be populated, but FYI you could be waiting for forever.
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5493631409) by [Unito](https://www.unito.io)
> Improve DX with webserver and REPL when neo4j connection is not available

- src/core/database/abstract-transactional-mutations.interceptor.ts
- src/core/database/database.module.ts
- src/core/database/transactional-mutations.interceptor.ts
- src/core/edgedb/edgedb-transactional-mutations.interceptor.ts
- src/core/edgedb/edgedb.module.ts
- src/core/edgedb/edgedb.service.ts
- src/core/edgedb/transaction.context.ts
This is the same thing as what we do for Neo4j.
It's worth noting that both of these interceptors are live right now, which could have unintended consequences with retry/rollback logic between the two DBs. This is only a temporary migration concern, so I'm not going to give it much thought until I need to.
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5500377488) by [Unito](https://www.unito.io)
> Implicitly run GQL mutations in EdgeDB transactions

- src/core/edgedb/generate.ts
- src/core/edgedb/index.ts
Switch generated query builder's target `mts` -> `ts` to fix usage with jest
Originally switched to support ESM.
Jest struggles with the imports though, and I could not find a configuration that worked.
The generated files produced with the `ts` target are fine for our use, aside from the import/export from `'edgedb/*'`; these need the file extension to work with ESM.
Example:
```diff
- import { Cardinality } from "edgedb/dist/reflection/index";
+ import { Cardinality } from "edgedb/dist/reflection/index.js";
```
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5503511966) by [Unito](https://www.unito.io)
> [EdgeDB] Fix generated query builder with Jest & ESM

- src/components/authentication/session.interceptor.ts
- src/core/edgedb/edgedb.module.ts
- src/core/edgedb/edgedb.service.ts
- src/core/edgedb/options.context.ts
- src/core/edgedb/options.ts
This exposes EdgeDB's `with*` options modifiers with an ALS. Essentially now we can do:
```ts
constructor(private readonly edgeDB: EdgeDB) {}
foo() {
await this.edgeDB.withOptions(
options => options.withGlobals({ foo: 'bar' }).withModuleAliases({ p: 'Project' }),
async () => {
// This block will have the above options applied
await this.edgeDB.run(query);
}
);
}
```
`withOptions` can be called multiple times to further configure the queries.
This is also independent of the current connection/transaction.
This allows a transaction to be started without a global and then later have a global applied.
This separation isn't really intended by the library, but it works with a Proxy referencing the current options stored in the ALS.
This is what we need to apply the `currentUserId` global from …
> EdgeDB.withOptions / Connect App Session to `currentUserId` global

- src/components/language/dto/create-language.dto.ts
- src/components/language/dto/language.dto.ts
- src/components/language/dto/update-language.dto.ts
- src/components/language/language.resolver.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5516673879) by [Unito](https://www.unito.io)
> Correctly mark nullability for language properties

- src/components/authentication/authentication.edgedb.repository.ts
- src/components/user/user.edgedb.repository.ts
- src/core/edgedb/generator/query-builder.ts
Essentially this allows
```ts
e.User
e.User.Status
```
Which is closer to what EdgeQL allows
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5534240837) by [Unito](https://www.unito.io)
> EdgeDB QB implicit default type or named module 

- dbschema/migrations/00028.edgeql
- dbschema/producible.esdl
@CarsonF - I'm not necessarily sold on the splitting out of all of these into their own `esdl` files now that I see the end result.  A case could be made to place them all in the `producible.esdl`.  Or perhaps even include them in the `Producible` module even?  Thoughts appreciated.
[Monday Task](https://seed-company-squad.monday.com/boards/3451697530/pulses/5452828634)
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5553618688) by [Unito](https://www.unito.io)
> [EdgeDB] Create `Producible`, `Film`, `EthnoArt`, and `Story` schemas

- src/components/engagement/dto/engagement.dto.ts
- src/components/engagement/dto/update-engagement.dto.ts
- src/components/engagement/engagement.service.ts
In order to allow certain fields to be nullable within EdgeDB the DTO & Service that handle those fields needed to be modified. Follow this [PR](https://github.com/SeedCompany/cord-api-v3/pull/2909) as a guide the following fields were altered to allow nulls:
InternshipEngagment.countryOfOrigin
InternshipEngagment.mentor
This is the related [Monday Ticket](https://seed-company-squad.monday.com/boards/3451697530/pulses/4909441234)
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5601657093) by [Unito](https://www.unito.io)
> Allow nulls on InternshipEngagement mentor & countryOfOrigin

- src/components/user/known-language.repository.ts
- src/components/user/user.edgedb.repository.ts
- src/components/user/user.module.ts
- src/components/user/user.repository.ts
- src/components/user/user.resolver.ts
- src/components/user/user.service.ts
This trims up user repo, making it easier for the edgedb impl
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5672767565) by [Unito](https://www.unito.io)
> User Repo Refactors / KnownLanguage Repo

- src/common/resource.dto.ts
- src/components/budget/dto/budget-record.dto.ts
- src/components/budget/dto/budget.dto.ts
- src/components/ceremony/dto/ceremony.dto.ts
- src/components/engagement/dto/engagement.dto.ts
- src/components/ethno-art/dto/ethno-art.dto.ts
- src/components/field-region/dto/field-region.dto.ts
- src/components/field-zone/dto/field-zone.dto.ts
- src/components/file/dto/node.ts
- src/components/film/dto/film.dto.ts
- src/components/funding-account/dto/funding-account.dto.ts
- src/components/language/dto/language.dto.ts
- src/components/location/dto/location.dto.ts
- src/components/organization/dto/organization.dto.ts
- src/components/partner/dto/partner.dto.ts
- src/components/product/dto/producible.dto.ts
- src/components/project/dto/project.dto.ts
- src/components/project/project-member/dto/project-member.dto.ts
- src/components/user/dto/user.dto.ts
- src/components/user/education/dto/education.dto.ts
- src/components/user/unavailability/dto/unavailability.dto.ts
- src/core/edgedb/abstract.type-util.ts
- src/core/edgedb/index.ts
- src/core/edgedb/reexports.ts
- src/core/resources/resources.host.ts
This will ease migration at the least. Currently we pass around resource names or objects, and we need to be able to do EdgeDB things with those now.
For example, these are all the same:
```ts
e.select(	e.Budget											);
e.select(	Budget.DB											);
e.select(	EnhancedResource.of(Budget).db						);
e.select(	(await $(ResourcesHost).getByName('Budget')).db		);
```
Also:
```ts
EnhancedResource.of(Project).dbFQN; // => "default::Project"
EnhancedResource.of(Ceremony).dbFQN; // => "Engagement::Ceremony"
```
This is just a first step. And since I touched all the DTOs for the EdgeDB schema we have so far, I wanted to get it in. More will come later that uses this.
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5601073410) by …
> [EdgeDB] Associate DB types with our TS resources

- src/common/exceptions/duplicate.exception.ts
- src/common/exceptions/exception.ts
- src/components/authentication/authentication.edgedb.repository.ts
- src/components/user/user.edgedb.repository.ts
- src/core/edgedb/edgedb.service.ts
- src/core/edgedb/error.util.ts
- src/core/edgedb/exclusivity-violation.error.ts
- src/core/edgedb/index.ts
- src/core/edgedb/transaction.context.ts
- src/core/exception/exception.filter.ts
- src/core/exception/exception.normalizer.ts
- src/core/logger/formatters.ts
This removes the boilerplate of wrapping db errors 1) to convert to generic failures to nicer error messages, 2) convert exclusivity violations to duplicate input errors.
Transactions will now also retry retryable errors, even when they are wrapped in other ones. Not as useful now, but doesn't hurt anything and matches what we do with Neo4j.
Fixed auth not throwing `NoSession`, when it should be.
Have a custom `ExclusivityViolationError` error class now with can be used to programmatically check the object FQN & property name that failed. As stated above, this is converted to a `DuplicateException` on the way out.
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5688525797) by [Unito](https://www.unito.io)
> [EdgeDB] Exception Handling/Formatting

- src/components/project/project-member/project-member.repository.ts
- src/components/user/user.edgedb.repository.ts
- src/components/user/user.module.ts
- src/components/user/user.repository.ts
- src/components/user/user.service.ts
- src/core/database/dto.repository.ts
- src/core/edgedb/common.repository.ts
- src/core/edgedb/dto.repository.ts
- src/core/edgedb/index.ts
- src/repl.ts
This eases the migration to EdgeDB repositories by providing some of the common functions that were declared on the neo4j side.
Additionally it provides all of these common methods out of the box: `readOne, readMany, list, create, update, delete`.
Usage:
```ts
class MyRepo extends RepoFor(Foo).withDefaults() {}
```
If one of the default methods signature doesn't match what you want you can customize it.
```ts
class MyRepo extends RepoFor(Foo).customize(cls => {
return class extends cls {
async create(color: string) {
...
}
}
}) {}
```
Obviously more additional methods can be added on as well, like the User Repo already does.
By default the _hydrated_ object is `*` aka `select User {*}`. This can be customized with a `hydrate` option, and then later accessed via class prop. It has to be …
> [EdgeDB] Abstract Common & DTO Repositories

- dbschema/migrations/00033.edgeql
- dbschema/project.esdl
This is a bit better as it doesn't assume anything about the project context.
Only that the given project & projectContext combo match.
This fixes project insertion, which now has a budget inserted with a trigger.
And that budget / "project child" was trying to check that it was given
the right project/project-context combo.
But the project doesn't yet have itself within its context yet,
because that self-reference has to in a separate query after the insert.
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5785203688) by [Unito](https://www.unito.io)
> [EdgeDB] Adjust enforcing project context during project insertion triggers

- dbschema/migrations/00037.edgeql
- dbschema/producible.esdl
- dbschema/scripture.esdl
There's a trade off here in simplicity of app code using this type vs information available.
I favored having information available, aka reading/select queries.
I'm exploring abstractions in app code currently to support this schema while reducing LoC.
- ✅ The `labels` here allow easy inspection on what the scripture is during adhoc exploration. They will be computed on write by the app.
- ✅ The `start/end.book/chapter/verse` fields allow the API to serve this data without having to compute from verse IDs. Good for reads.
- ✅ The `verseId` supports answering complex analytical questions. i.e. Does this engagement/product include _Matthew 1_?
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5822486982) by …
> [EdgeDB] Build out scripture collection schema, for easier querying & inspection

- src/components/project/dto/project.dto.ts
- src/components/project/project.repository.ts
- src/core/database/query/cypher-functions.ts
- src/core/database/query/lists.ts
[ticket](https://seed-company-squad.monday.com/boards/3451697530/views/78801638/pulses/5675458057?filter=XQAAAALKAAAAAAAAAABBqQqHk62Wwa8yt9cbbXI48HpL2ei1XixEiNVOhiWmf4IrTn4lrcVxz0d8EzlqDpxL1dc7i9JjI1nNW0HEFgqaXhsDsHWTHjMEE6-qlUKWgWTaunFWUdBXUlo9GrL7-Dxs3yXtVsCpk7bU6tq4ASH03XfQsurYW6oz6SfWXIHjSrPNZIVE3__87GiYdcf5oUuHV6IpVDC18IDUOyTd3hSlyn4xwV6TGJGJ____cnOAAA)
This adds sorting on projects entity for status (by status type rather than alphabetically) and engagements (by engagement count)
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5825418833) by [Unito](https://www.unito.io)
> Project sorting status, step, engagement count

- src/components/location/dto/create-location.dto.ts
- src/components/location/dto/location.dto.ts
- src/components/location/dto/update-location.dto.ts
- src/components/location/location.repository.ts
- src/components/location/location.resolver.ts
- test/location.e2e-spec.ts
- test/utility/fragments.ts
https://seed-company-squad.monday.com/boards/3451697530/pulses/4875988786
More to do here but this PR addresses the bullet point below taken from the linked Monday ticket. 
- Add Location.marketingRegion: Location (3)
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5691023859) by [Unito](https://www.unito.io)
> 0573 Location.defaultMarketingRegion

- src/components/location/location.module.ts
- src/components/location/migrations/default-marketing-region.migration.ts
https://seed-company-squad.monday.com/boards/3451697530/pulses/5186744629
Created migration file for defaultMarketingRegion relationship.  
* There is one country in the DB with a name of "Not Applicable" which has a fieldRegion name of "any".  Not sure if we handled this use case correctly.
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5842212514) by [Unito](https://www.unito.io)
> 0701 default marketing region migration

- dbschema/common.esdl
- dbschema/engagement.esdl
- dbschema/migrations/00043.edgeql
- dbschema/post.esdl
- src/core/edgedb/codecs/index.ts
- src/core/edgedb/codecs/rich-text.codec.ts
This declares a `RichText` scalar as a subtype of `json`.
We convert that to our `RichTextDocument` type & instance in app code (thanks to #3049)
I guess it's worth noting that there are some code paths, that don't account for this specific subtype, but uses the plain `json` logic.
For example, converting these documents to EdgeQL literals still does 
```ts
`to_json(${JSON.stringify(value)})`
```
This is actually fine, since our RichTextDocuments serialize to JSON as expected.
Just felt like it was worth calling out that not all code paths use this specific subtype logic.
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5875143343) by [Unito](https://www.unito.io)
> [EdgeDB] RichText Scalar

- src/core/resources/resources.host.test.ts
- src/core/resources/resources.host.ts
Basically this handles
'Ceremony' -> 'Engagement::Ceremony' (after trying 'default::Ceremony')
Not a code path we are currently hitting, but possible in future.
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5884380174) by [Unito](https://www.unito.io)
> [EdgeDB] Fix getBaseNode not using the right type name in some cases

- dbschema/migrations/00044.edgeql
- dbschema/post.esdl
This bug was actually from the `Project.departmentId` rewrite bug. That rewrite is temporarily commented out until that bug is fixed. Fix has been identified, and they have a PR up for it currently, so I expect it to be in our hands in a couple of weeks.
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5895347110) by [Unito](https://www.unito.io)
> [EdgeDB] Unhack the `Post.container` type overload

- src/components/authorization/policy/executor/policy-dumper.ts
- src/components/authorization/policy/granters.factory.ts
- src/components/authorization/policy/policy.factory.ts
- src/components/comments/comment.service.ts
- src/components/file/media/events/can-update-event.ts
- src/components/post/post.service.ts
- src/components/progress-report/media/handlers/update-media-metadata-check.handler.ts
- src/components/search/search.service.ts
- src/core/edgedb/common.repository.ts
- src/core/edgedb/dto.repository.ts
- src/core/resources/resources.host.test.ts
- src/core/resources/resources.host.ts
- src/repl.ts
Previously we needed to import the legacy resource map from another file. Now that's removed, so this no longer needs to be async.
Obviously, this has huge implications.
An argument could be made to keep this async
to allow for future functionality that needs to be async. However, I can't currently think of what this would be.
Making this sync allows for more places to use the current functionality.
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5895368162) by [Unito](https://www.unito.io)
> Make `ResourcesHost` sync

- src/common/exceptions/duplicate.exception.ts
- src/common/exceptions/input.exception.ts
- src/core/exception/exception.normalizer.ts
Now user input IDs can be passed straight into EdgeDB queries without validating, and still have a proper error returned when not found. No more pre validation or manual conversion needed.
This does require that the query be composed in a way that gives info enough back in the error for us to do the conversion.
Object casts work great for this.
```edgeql
<User><uuid>"..."
```
https://github.com/SeedCompany/cord-api-v3/blob/3cb6a335e0fa27ee21a50d844763b67b7dfba75a/src/components/field-zone/field-zone.edgedb.repository.ts#L20-L20
A manual assertion won't give enough info, so that will still be returned as a server error, which it could rightly be.
```edgeql
assert_exists((select User filter .id = <uuid>"..."))
```
This gives a generic assertion failed error so it won't be properly …
> [EdgeDB] Automatically handle not found ID errors from user input

- dbschema/common.esdl
- dbschema/file.esdl
- dbschema/migrations/00045.edgeql
- dbschema/z.owned.esdl
There were a lot of places it couldn't be used in schema due to dependency cycles and other things.
But it's still useful in some places and it's very helpful in adhoc queries.
```edgeql
insert User {
owner := <User>global currentUserId
}
```
```edgeql
insert User {
owner := currentUser
}
```
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5922044431) by [Unito](https://www.unito.io)
> [EdgeDB] Add current user alias

- src/components/file/file-url.controller.ts
- src/components/file/file-url.resolver-util.ts
- src/components/file/file-version.resolver.ts
- src/components/file/file.resolver.ts
- src/components/file/file.service.ts
- src/components/file/media-url.resolver.ts
I kinda wonder if this should be an enum instead of a boolean?
I also wonder what the default value should be? I did switch it from attachment to inline in this PR.
Shortcut to the change in our output: https://github.com/SeedCompany/cord-api-v3/pull/3058/files#diff-559f57a4094a5701bd377bab60ea5315133688bf78f2d6b93371891eab9bbb10R169
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5919092883) by [Unito](https://www.unito.io)
> Allow file urls option to download file or not (disposition header)

- dbschema/migrations/00046.edgeql
- dbschema/migrations/00047.edgeql
- dbschema/migrations/00048.edgeql
- dbschema/project.esdl
- dbschema/seeds/007.language-engagements.edgeql
- edgedb.toml
- src/components/engagement/dto/engagement.dto.ts
This fixes:
- The rewrite with `departmentId`
- The overload on `Engagements` picking specific `Project` types.
- The overload on `Project/Language` setting `ownSensitivity` as required and defaulting to High.
- The `min_value/max_value` constraints. Though I didn't revert these because they aren't that much different than what we have right now.
To upgrade locally:
```
edgedb project upgrade
```
And idk if migrate is needed after
```
edgedb migrate
```
It could be that the migrate fails, as it did for me with my dev changes. So you'll need to blow away and start over.
```
edgedb project unlink -D --non-interactive
edgedb project init --non-interactive
yarn edgedb:seed
```
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/59338186 …
> Upgrade EdgeDB 4.4 -> 4.5

- src/common/validators/short-id.validator.ts
- src/common/validators/validateBy.ts
- src/components/changeset/changeset.module.ts
- src/components/changeset/dto/changeset.args.ts
- src/core/core.module.ts
- src/core/exception/exception.filter.ts
- src/core/validation/index.ts
- src/core/validation/validation.exception.ts
- src/core/validation/validation.module.ts
- src/core/validation/validation.pipe.ts
This allows validators to be injectable. Prepping for future work.
Example:
```ts
@Injectable()
@ValidatorConstraint({ name: 'Foo', async: true })
export class FooConstraint implements ValidatorConstraintInterface {
constructor(
// inject anything...
) {}
async validate(value: unknown, args: ValidationArguments) {
...
}
}
const IsFoo = createValidationDecorator(FooConstraint);
// or
const IsFoo = () => ValidateBy(FooConstraint);
```
Obviously the constraint class provided in a module as well.
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5954156315) by [Unito](https://www.unito.io)
> Validation Injectability

- dbschema/alias.esdl
- dbschema/migrations/00051.edgeql
- src/common/id.arg.ts
- src/common/validators/index.ts
- src/common/validators/short-id.validator.ts
- src/components/changeset/changeset.arg.ts
- src/core/edgedb/alias-id-resolver.ts
- src/core/edgedb/edgedb.module.ts
- src/core/validation/validation.module.ts
This will allow the API/UI to accept our current IDs even after the migration.
My main motivation for this is to not break all references to our URLs that include IDs.
This works with an `Alias` type/table that maps a string to some object.
It assumes all IDs now (after migration) are some form of a UUID.
Therefore, any string that's not a UUID would make a DB call to convert to the target's UUID.
These aliases still have to be globally unique, as our current IDs are.
This currently works transparently for all input fields/args that are of type `ID`, or rather use the [`IdArg`](https://github.com/SeedCompany/cord-api-v3/blob/bfaae760e62d40d4aada19f4b3f8635bacb6f483/src/common/id.arg.ts#L5-L5) or [`IsId`](https://github.com/SeedCompany/cord-api-v3/blob/bfaae760e62d40d4aada19f4b3f8635bacb6f4 …
> [EdgeDB] Aliases for legacy IDs

- dbschema/common.esdl
- dbschema/migrations/00052.edgeql
- src/core/edgedb/edgedb.service.ts
- src/core/edgedb/generator/find-hydration-shapes.ts
- src/core/edgedb/generator/inject-hydrators.ts
- src/core/edgedb/generator/inline-queries.ts
- src/core/edgedb/generator/query-files.ts
- src/core/edgedb/generator/run.ts
- src/core/edgedb/generator/util.ts
One of the big reasons why I pushed for the query builder in the past few weeks, is it has the ability to have "shared/portable shapes" ([doc](https://www.edgedb.com/docs/clients/js/select#portable-shapes)). This is what powers the `hydrate` function in the edgedb repos.
It allows us to define the shape we expect back for the type once, instead of in every query.
Unfortunately, EdgeQL does not natively support this concept yet. ([Proposal](https://github.com/edgedb/edgedb/issues/5736))
Also unfortunately, the TS query builder seems to push TS to its limits and TS slows down & eventually gives up (errors out). This was made evident in my work on the file module.
So we need a solution, which is this.
Doing our own hydration concept. This is basically magical string injection, but hear me …
> EdgeQL Hydration

- dbschema/common.esdl
- dbschema/migrations/00054.edgeql
- dbschema/periodic-report.esdl
- dbschema/progress-report.esdl
In this PR we are adding the EdgeDB schema for the `PeriodicReport`. This work is to be able to move forward with the EdgeDB migration and unblock future work that requires `PeriodicReport` or children types.
In this work we started using the `range` type from EdgeDB for the period a `PeriodicReport` is in and the `start` and `end` are computed fields from the `period` field.
> [EdgeDB] `PeriodicReport` schema

- src/components/engagement/dto/list-engagements.dto.ts
- src/components/engagement/engagement.resolver.ts
It's annoying to have to add fragments to narrow type when you all you want is language engagements.
It's problematic with codegen expecting certain types that only exist on the concrete.
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/6050522434) by [Unito](https://www.unito.io)
> Add GQL queries for LanguageEngagements

- src/common/resource.dto.ts
- src/core/resources/resources.host.ts
The current goal is to have strict output from strict input, but allow / have useable loose output from loose/dynamic input.
```ts
EnhancedResource.of(User).dbFQN => "default::User"
EnhancedResource.of(<any>).dbFQN => string
EnhancedResource.of(User).db => e.User
EnhancedResource.of(<any>).db => e.Resource
ResourcesHost.getByDynamicName("User") => EnhancedResource<any>
ResourcesHost.getByDynamicName("User").db => e.Resource
ResourcesHost.getByDynamicName("asdf").db => e.Resource & RuntimeError
ResourcesHost.getByEdgeDB("User") => EnhancedResource<User>
ResourcesHost.getByEdgeDB("default::User") => EnhancedResource<User>
ResourcesHost.getByEdgeDB("asdf") => EnhancedResource<any> & RuntimeError
```
┆Issue is synchronized with this [Monday …
> [EdgeDB] Tweak Resource Types

- dbschema/common.esdl
- dbschema/migrations/00057.edgeql
- dbschema/prompt-variant-response.esdl
- src/core/edgedb/codecs/index.ts
- src/core/edgedb/codecs/nanoid.codec.ts
- src/core/edgedb/generator/query-builder.ts
This correctly generates types like
```ts
class PromptVariantResponse {
promptId: ID;
...
}
```
This is more accurate than `string`.
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/6148790225) by [Unito](https://www.unito.io)
> [EdgeDB] nanoid scalar to generate types as ID

- src/common/id-field.test.ts
- src/common/id-field.ts
- src/common/resource.dto.ts
- src/core/resources/index.ts
- src/core/resources/resource-name.types.ts
- src/core/resources/resource.loader.ts
- src/core/resources/resources.host.ts
`IdOf` seems to be working well, and helps with DX. This standardizes it and improves the functionality.
- Type generic can now be given to `ID`
- Deprecated `IdOf` for `ID`
- Types/Kinds can be:
- Resource names: `ID<'User'>`. These are easy to use without needing imports.
- EdgeDB FQNs: `ID<'default::User'>`. These will allow DB QB types to be compatible.
- Class "instances": `ID<User>`. These are a little nicer than strings, if already imported. And needed because that's what `IdOf` used.
- Static class references: `ID<typeof User>`. Here for completeness, but idk the use case.
- These are normalized, so they are compatible with each other
```ts
ID<'User'> == ID<'default::User'> == ID<User> == ID<typeof User>
```
- Concrete types are compatible with interface types 😎 
```ts
const …
```
> Typed IDs v2

- src/components/field-region/field-region.edgedb.repository.ts
- src/components/field-zone/field-zone.edgedb.repository.ts
- src/core/edgedb/dto.repository.ts
- src/core/edgedb/query-util/easy-insert.ts
- src/core/edgedb/query-util/map-to-set-block.ts
The queries built will now automatically cast IDs for links to their object refs.
The methods will also accept props with an `Id` suffix and strip it off.
This should help make a lot of our queries involving links easier, as demonstrated by FieldZone & FieldRegion repos.
```diff
create({
name: input.name,
-   director: e.cast(e.User, e.cast(e.uuid, input.directorId)),
+   directorId: input.directorId,
})
```
This is only a shortcut: EdgeQL expressions can still be given, and IDs can be given to `director` (no `Id` suffix).
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/6155607311) by [Unito](https://www.unito.io)
> [EdgeDB] Default Repo create/update handle link IDs

- src/components/engagement/dto/update-engagement.dto.ts
- src/components/file/resolve-defined-file.ts
- src/components/project/dto/update-project.dto.ts
- src/core/database/changes.ts
`FileId` used to have a unique brand that TS could discriminate on.
I removed this in https://github.com/SeedCompany/cord-api-v3/commit/a50ae3c19a37034570b1e4212d801f0f74cb6790 to be forward compatible with the `LinkTo<File>` approach.
So that removal broke this code.
Fixed this by not considering `ID<any>` to be a File ID (`ID<File>`) (for this change mapping).
Unfortunately that break mentioned above was immediately hidden by my next commit https://github.com/SeedCompany/cord-api-v3/commit/2b9f01e034d60e8ec501bbe61d07e0fb0a9ef8eb which was also bugged.
I mixed up the "do nothing" union type with the intersection one.
For reference
```
X | unknown == unknown
X | never   == X
X & unknown == X
X & never   == never
```
So fixed that too.
Fixed some more places where nulls are expected. …
> Fix big ChangesOf regression involving DefinedFiles

- src/common/resource.dto.ts
- src/core/edgedb/edgedb.service.ts
- src/core/resources/resource-name.types.ts
- src/core/resources/resources.host.ts
- [Allow running raw EdgeQL query strings without return types](https://github.com/SeedCompany/cord-api-v3/commit/2cf492f84bb1463b63e42ec0764b6fe1cae327f5)
There's no reason to make this a type error. It's just the return type that is unknown.
REPL uses this signature.
- [Change `ResourceName<any>` to `AllResourceNames` instead of `string`](https://github.com/SeedCompany/cord-api-v3/commit/ff2e71be6279ae2bda1df815362e9a727ab82e31)
No reason to use _any_ string, which we know it's a union of all of our literal strings.
```ts
const resource = ResourcesHost.getByDynamicName('...');
resource.name === 'User' | 'Project' | ...
resource.name === 'asdf' // TS error
```
- [Expose resources keyed by DB FQNs](https://github.com/SeedCompany/cord-api-v3/commit/110d32c1b545fabba8162181c2a429103720c7ac) …
> Some small tweaks extracted from large AP work

- package.json
- src/core/edgedb/generator/inline-queries.ts
- src/core/edgedb/generator/query-builder.ts
- src/core/edgedb/generator/query-files.ts
- yarn.lock
A lot of work upstream to make this possible as well:
edgedb/edgedb-js#884
edgedb/edgedb-js#885
edgedb/edgedb-js#887
edgedb/edgedb-js#889
The library natively generates immutable arguments now.
I tweak the QB & file generators here to generate immutable output types.
> [EdgeDB] Generate immutable types

- .gitattributes
- dbschema/ceremony.esdl
- dbschema/language.esdl
- dbschema/migrations/00071.edgeql
- dbschema/organization.esdl
- dbschema/partner.esdl
- dbschema/project.esdl
- dbschema/scripture.esdl
- Doing `delete Object` would fail on the two trigger assertions.
- These were to prevent mistakes, but these actions should
only happen in one spot in the schema or app code.
So I'm fine dropping them to make deletes more ergonomic.
- FWIW both of these should work from my perspective
with `delete Object` so maybe they are bugs.
- Deleting `Partner` or `Organization` deletes the other.
- Deleting `Language`/`Project`/`Org` deletes their `ProjectContext`
- Deleting `Scripture::VerseRanges` are allowed if their `Scripture::Collection` is being deleted too
- Marking migration files as generated so GitHub doesn't render them by default (or count them in diff stats)
> Fix `delete Object` usage

- src/components/authorization/policies/by-role/project-manager.policy.ts
- src/components/budget/budget-record.repository.ts
- src/components/budget/budget.repository.ts
- src/components/budget/budget.service.ts
- src/components/budget/dto/budget-record.dto.ts
- src/components/budget/dto/budget.dto.ts
- src/components/project/project.service.ts
This fixes the `budget.record.canEdit` flag to correctly emit `false` if the budget is finalized & you/FPM cannot edit finalized budgets.
It's also much cleaner.
> Move budget record non-finalized check to policies

- src/common/context.type.ts
- src/common/session.ts
- src/components/admin/admin.edgedb.repository.ts
- src/components/authentication/authentication.module.ts
- src/components/authentication/authentication.service.ts
- src/components/authentication/current-user.provider.ts
- src/components/authentication/session.interceptor.ts
- src/components/authentication/session.resolver.ts
- src/components/progress-report/media/handlers/update-media-metadata-check.handler.ts
- src/core/data-loader/session-aware-loader.strategy.ts
- src/core/edgedb/edgedb.module.ts
- src/core/edgedb/edgedb.service.ts
- src/core/edgedb/index.ts
- src/core/edgedb/options.context.ts
- src/core/graphql/graphql-session.plugin.ts
- src/core/graphql/graphql-tracing.plugin.ts
- src/core/graphql/graphql.config.ts
- src/core/graphql/graphql.module.ts
This follows up on #2941
[Previously](https://github.com/SeedCompany/cord-api-v3/commit/30238eef49e609fa1b68d97bf122d9d745916115), the `currentUserId` was put in the EdgeDB globals context via a NestJS Interceptor.
But _interceptors_ only cover the main query/mutation method (like a _controller_).
GQL field resolvers are walked/invoked after this lifecycle as needed.
So those field resolvers would not have the currentUser set ❌ 
Aside: I might have been thrown off here, because the transaction context _is_ applied with an [interceptor](https://github.com/SeedCompany/cord-api-v3/blob/develop/src/core/database/abstract-transactional-mutations.interceptor.ts#). But this is fine because DB changes only happen within the main mutation method. Field resolvers after that are just reading back …
> [EdgeDB] `currentUserId` global refactor

- src/core/edgedb/dto.repository.ts
@andrewmurraydavid @bryanjnelson both of you guys hit this with project & language repos.
With no omit array given, TS inferred the `OmitKeys` type to be all of the enum members.
Giving it a default value of `never` suppresses that, so it will infer if the array is given or fallback to this default value which removes nothing.
Honestly TS is amazing.
> Fix omitting `customize` `omit` acting like omitting all default methods

- dbschema/engagement.esdl
- dbschema/language.esdl
- dbschema/migrations/00075.edgeql
Mostly reverts 5829d35e588f7e20eee71e29c8569602df2a7c26
I'm not sure what the error was back then, but it works fine now in 4.7
The actual problem was that we were comparing the engagement to language list, so of course there was no overlap.
```diff
- in .languages
+ in .engagements
```
But the former expression of just selecting the linked project works and should be more performant. So going with that.
> Fix TranslationProject sensitivity sync

- src/core/edgedb/generator/query-builder.ts
- src/core/edgedb/index.ts
- src/core/edgedb/query-util/cast-to-enum.ts
- src/core/edgedb/withScope.ts
This is an unsafe helper to assert that the given str expression
is actually a string literal union of the given enum.
```ts
const expr = e.str('red') // edgeql str literal whose TS value is `string`
castToEnum(expr, ['red', 'blue']) // expression TS value is now `'red' | 'blue'`
```
> [EdgeDB] castToEnum QB helper

- dbschema/migrations/00077.edgeql
- src/components/authorization/policy/edgedb-access-policy.generator.ts
- src/components/authorization/policy/executor/policy-executor.ts
Following up on #3126 
Updates policies were previously skipped because we want the app to handle them.
But we actually have to declare them, otherwise EdgeDB defaults to "no access".
- Set `update read` to match `selects`.
This just means that anything that can be read with a `select` query can be read with an `update` query.
- Set `update write` to always allow.
The API will handle edit permissions.
But we need to declare these so the DB knows to ignore.
Schema diff here: https://github.com/SeedCompany/cord-api-v3/commit/3b556c8fa04dc303a01be624a3a9e5638ccf4edd
> [EdgeDB] Generate APs for update statements

- .github/workflows/edgedb.yml
- package.json
- src/core/edgedb/generator/query-builder.ts
- yarn.lock
- Plain tuples were actually missed before in converting to immutable.
- The `ArrayTypeToTsType` alias changed, so changing my patch to account for that.
> Bump edgedb libs & account for changes

- dbschema/migrations/00079.edgeql
- dbschema/project.esdl
Following up on #3132
That PR added a on Project delete, delete ProjectContext.
All project children are also configured to delete with Project as well. ([src](https://github.com/SeedCompany/cord-api-v3/blob/95af5f9041cd91bda38e3c9401571271e94a832e/dbschema/project.esdl#L136))
But this sibling deletion chain was not respecting that sibling deletion chain.
So setting them both to chain deletes works.
In practice, I could see `delete Project::Context` deleting all directly associated objects (like this PR does), but I could also see it restricting because it still has things referenced.
I guess our hand is forced though. These contexts should be rarely referenced anyways, and would/should never be deleted directly.
> [EdgeDB] Fix delete cascade

- src/core/database/common.repository.ts
Big big facepalm here. Can't believe this has lived for so long, we must've not been using it much. And I think we've made a recent push to fix the "update to nulls" in API/UI.
Creating these empty nodes does affect cardinality, which is why the DOMO sync was throwing a duplicate error.
I'll just drop these empty nodes in prod adhoc, I don't want to create a script.
> [Neo4j] Don't create empty nodes for optional, now null relationships

- dbschema/migrations/00080.edgeql
- dbschema/project.esdl
- dbschema/seeds/008.projects.ts
- src/components/engagement/dto/engagement.dto.ts
- src/components/engagement/engagement.repository.ts
- src/components/engagement/engagement.service.ts
- src/components/engagement/handlers/update-project-status.handler.ts
- src/components/project/dto/list-projects.dto.ts
- src/components/project/dto/project-type.enum.ts
- src/components/project/dto/project.dto.ts
- src/components/project/engagement-connection.resolver.ts
- src/components/project/handlers/set-step-changed-at.handler.ts
- src/components/project/list-filter.query.ts
- src/components/project/migrations/rename-translation-to-momentum.migration.ts
- src/components/project/project.edgedb.repository.ts
- src/components/project/project.loader.ts
- src/components/project/project.module.ts
- src/components/project/project.repository.ts
- src/components/project/project.resolver.ts
- src/components/project/project.service.ts
- src/components/search/dto/search-results.dto.ts
- src/core/database/query/filters.ts
- src/core/database/query/match-project-based-props.ts
- test/engagement-workflow.e2e-spec.ts
- test/engagement.e2e-spec.ts
- test/project-workflow.e2e-spec.ts
- test/project.e2e-spec.ts
- test/utility/create-project.ts
A new Translation Project type was introduced, Multiplication Project. The old "Translation" project becomes "Momentum" from a business stand point, but from a data view, the Translation project becomes abstract and Momentum and Multiplication become "subtypes" of Translation.
> Split TranslationProject into Momentum and Multiplication

- src/components/authorization/policies/conditions/enum-field.condition.ts
Looking back, the former `StatusCondition` also didn't do this.
Due to calling code, this condition always worked fine when securing the object because the object wasn't secured.
(Which is also what declares the `canDelete` boolean.)
It is only when using a secured object as the context, that this bug was hit.
So this did in fact work correctly when it was written: #2863
It was only after we changed the `delete` check, which _did_ use a secured object, that this bug was exposed: #2976
FYI @renatorossiter
> Fix field condition not unwrapping secured values

- dbschema/seeds/018.ceremonies.edgeql
Adds seeding for the additional fields of estimatedDate and actualDate for ceremonies.
> [EdgeDB] Ceremony Seeds

- src/common/secured-property.ts
- src/components/admin/admin.module.ts
- src/components/admin/migrations/normalize-creator.migration.ts
- src/components/authorization/policies/conditions/owner.condition.ts
- src/components/post/dto/post.dto.ts
- src/components/post/post.repository.ts
- src/components/post/post.resolver.ts
- src/components/progress-report/media/dto/media.dto.ts
- src/components/progress-report/media/progress-report-media.repository.ts
- src/components/prompts/dto/prompt-response.dto.ts
- src/components/prompts/prompt-variant-response.repository.ts
- src/components/prompts/prompt-variant-response.resolver.ts
Fixes regression from #3163, which changes the RootUser ID, but didn't account for these denormalized values.
I did test this migration locally and it works as expected
> [Neo4j] Normalize creator relationship to User node

- src/components/project/dto/project.dto.ts
Some TODOs were not addressed and the Projects DTO was not registering the correct EdgeDB concretes.
This meant that when creating a Momentum or Multiplication project, it would try to create a Translation project and fail.
Fixed/addressed the TODOs and fixed the the concrete resource registrations.
> fixed TODOs and incorrectly registered resources on EdgeDB Projects

- src/components/admin/admin.module.ts
- src/components/admin/migrations/normalize-creator-base-node.migration.ts
Another miss from #3172 / #3163
The new schema is
```cql
(:BaseNode)-[:creator]->(:User { id: "user id" })
```
The data migration in that PR handled
```cql
(:BaseNode)-[:creator]->(:Property { value: "user id" })
```
But it missed places where we did
```cql
(:BaseNode { creator: "user id" })
```
I did already run these in dev to test.
> [Neo4j] Migrate creator on BaseNode to normalized relationship

- dbschema/migrations/00003.edgeql
- dbschema/project.esdl
- src/components/project/handlers/set-department-id.handler.ts
Updated the EdgeDB trigger for update and insert on projects to account for the new style of department ID generation, special for the Multiplication Translation Projects.
> Updated `departmentId` generation for Multiplication Projects

- edgedb.toml
- src/components/authentication/authentication.edgedb.repository.ts
- src/core/edgedb/edgedb.service.ts
- src/core/edgedb/transaction.context.ts
This updates min version and removes workaround for avoiding transactions when disabling access policies.
https://github.com/edgedb/edgedb/issues/7138
> EdgeDB v5-rc.1 allows config changes inside sessions

- test/utility/expect-gql-error.ts
i.e.
```ts
toThrowGqlError(
errors.notFound({
message: expect.stringMatching(/Could not find project/i),
})
)
```
> Fix toThrowGqlError to support asymmetric matchers

- test/utility/edgedb-setup.ts
- test/utility/expect-gql-error.ts
Missed in #3183
This previous code avoided quoting the message string.
I was trying to reduce syntax to sort through in error message.
Compromising to include quotes here to be consistent & support the matchers.
```
Message:
StringMatching: /not found/
"Server Error"
```
```
Message:
"Not Found"
"Server Error"
```
> Change toThrowGqlError message failure to support asymmetric matchers

- src/components/periodic-report/dto/list-periodic-reports.dto.ts
- src/components/periodic-report/periodic-report.repository.ts
Sort periodic reports by `start` date instead of `end` date.
This fixes incorrectly matching the current report to the final one.
Given reports:
Last regular:  1/1/2024 - 3/31/2024
Final:        3/31/2024 - 3/31/2024
So if using the end date, one of those two is arbitrarily picked, and has so far just been a coincidence to have been picked correctly.
> Fix current report picking final prematurely

- src/components/ceremony/ceremony.edgedb.repository.ts
- src/components/field-region/field-region.edgedb.repository.ts
- src/components/field-zone/field-zone.edgedb.repository.ts
- src/components/funding-account/funding-account.edgedb.repository.ts
- src/components/language/ethnologue-language/ethnologue-language.edgedb.repository.ts
- src/components/language/language.edgedb.repository.ts
- src/components/location/location.edgedb.repository.ts
- src/components/progress-report/variance-explanation/variance-explanation.edgedb.repository.ts
- src/components/progress-report/workflow/progress-report-workflow.edgedb.repository.ts
- src/components/project/project.edgedb.repository.ts
- src/components/story/story.edgedb.repository.ts
- src/components/user/education/education.edgedb.repository.ts
- src/components/user/unavailability/unavailability.edgedb.repository.ts
- src/components/user/user.edgedb.repository.ts
- src/core/edgedb/dto.repository.ts
Instead of putting customized methods in an intermediary class, they can now just go in the final class.
If the signature is compatible with the default one, then nothing more is needed, which is the same as before.
If the signature is _not_ compatible with the default one, then it can just be marked in the `omit` array to ignore the default signature.
Overall I think this simpler for customization cases.
For default cases, it doesn't appear that we will ever not want to start with default methods.
If we did we'd just extend from CommonRepo instead. Maybe future work here if needed.
> Simplify EdgeDB Repo customize

- src/app.module.ts
- src/components/user/actor.edgedb.repository.ts
Queries cannot run in parallel within a transaction.
https://github.com/SeedCompany/cord-api-v3/blob/1eb8d8b7b6db30146704486487f7def21e3b8f47/src/components/authentication/authentication.service.ts#L121-L124
The actor logic is not meant to be a part of the current mutation, so changed there.
Also removed the stacktrace limit for dev.
> Upsert actors outside of current transaction

- dbschema/migrations/00007-m15wwix.edgeql
- dbschema/organization.esdl
- dbschema/partner.esdl
- dbschema/seeds/006.organizations.edgeql
- dbschema/seeds/007.partners.edgeql
- src/components/organization/dto/organization.dto.ts
- src/components/organization/organization.edgedb.repository.ts
- src/components/organization/organization.module.ts
- src/components/organization/organization.repository.ts
- src/components/organization/organization.service.ts
- src/components/partner/dto/create-partner.dto.ts
- src/components/partner/dto/partner.dto.ts
- src/components/partner/dto/update-partner.dto.ts
- src/components/partner/partner.edgedb.repository.ts
- src/components/partner/partner.module.ts
- src/components/partner/partner.repository.ts
- src/components/partner/partner.resolver.ts
- src/components/partner/partner.service.ts
- src/core/database/changes.ts
Migrate Partner and Organization Queries to edgedb
> EdgeDB - Partner and Organization Queries

- src/components/ethno-art/ethno-art.edgedb.repository.ts
- src/components/ethno-art/ethno-art.module.ts
- src/components/ethno-art/ethno-art.repository.ts
- src/components/ethno-art/ethno-art.service.ts
Implementing the EdgeDB Query Updates for the EthnoArt data
- [na] Add/update tests if needed
> [EdgeDB] EthnoArt queries

- src/components/project/project.rules.ts
- src/core/email/templates/project-step-changed.template.tsx
[Monday Task](https://seed-company-squad.monday.com/boards/3451697530/pulses/6074211485)
> Project Workflow: All Controllers -> FinancialApprovers

- src/components/engagement/dto/list-engagements.dto.ts
- src/components/engagement/engagement.repository.ts
- src/components/engagement/engagement.service.ts
- src/components/partner/partner.module.ts
- src/components/partner/partner.resolver.ts
- src/components/partner/partner.service.ts
[Monday task](https://seed-company-squad.monday.com/boards/5989610236/views/132288519/pulses/6508717681)
> Expose Partner.engagements

- src/components/engagement/engagement.rules.ts
- src/components/engagement/handlers/update-project-status.handler.ts
This PR changes how the engagements are updated in the project handler.
There seems to be an issue, either with the the way `Promise.all` handles the UnauthorizedException for the edgecase where a project has 3 engagements, one (or more) of them being in a step previous (for example 2 in `Active change plan` and 1 in `Discussing change plan`), the engagement update would fail with the UnauthorizedException. 
It is assumed that because Promis.all not handling the exception properly, would cause a neo4j transaction creation to retry in an infinite loop.
This infinite loop caused the API service to crash completely being OOM (out of memory).
In the description
Not crash, lol
> [Hotfix] Change `Promise.all` to `for await` in project status handler to catch UnauthorizedException

- src/components/project/project.rules.ts
- src/core/email/templates/project-step-changed.template.tsx
[Monday task](https://seed-company-squad.monday.com/boards/3451697530/pulses/6074211485)
https://seed-company-squad.monday.com/boards/5989610236/pulses/6509819818
> Add primary partner name to project workflow notification

- package.json
- src/components/file/bucket/local-bucket.ts
- src/components/file/file.service.ts
- src/components/file/files-bucket.factory.ts
- src/components/file/local-bucket.controller.ts
- src/core/config/config.service.ts
- src/core/tracing/tracing.module.ts
- src/core/tracing/xray.middleware.ts
- src/main.ts
- test/file.e2e-spec.ts
- test/utility/create-file.ts
- test/utility/create-graphql-client.ts
- test/utility/fragments.ts
- yarn.lock
Previously we were faking the upload/download process by talking to the _assumed_ `LocalBucket` storage.
Where as in actual usage we are expecting PUT/GET HTTP requests.
This changes the tests to actually use that code path.
The reasoning for this previous decision was because we weren't actually serving the GQL API over a server, but executing the operations directly. So without a web server setup, we couldn't do these requests either. That has since changed.
The last hard part here was that we use a unix socket for the test web server which assigns a random port when we start listening.
The app needs to know where it is hosting/listening on so it can generate those PUT/GET urls.
But app boot happens before listening so the port can't be known ahead of time.
I switched the …
> [Tests] E2E File upload/download

- src/components/file/file-version.resolver.ts
- src/components/file/file.resolver.ts
No longer used now: seedcompany/cord-field#1511
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5923277137) by [Unito](https://www.unito.io)
> Drop deprecated short-lived downloadUrl field

- dbschema/seeds/019.pins.edgeql
Add seeding for pinnable types; some test users now have populated `pins` for projects, languages, and/or partners
> [EdgeDB] Add Pins Seeding

- package.json
- src/common/make-enum.ts
- src/components/engagement/engagement.rules.ts
- src/components/progress-report/workflow/progress-report-workflow.flowchart.ts
- src/core/email/templates/progress-report-status-changed.template.tsx
- yarn.lock
- Added `EnumX.entry(EnumX.Y)` to retrieve the _entry_ for the given value.
e.g.
```ts
ProjectStep.entry('DiscussingChangeToPlan')
ProjectStep.entry(ProjectStep.DiscussingChangeToPlan)
```
I thought about calling it `.get()` instead. Thoughts?
- Added default `label` to all entries that didn't have one provided / handwritten.
- Swapped usage across app to use enum labels instead of adhoc conversion.
```ts
// handwritten
ProjectType.entry('MomentumTranslation').label // => "Momentum"
ProductMedium.entry('EBook').label // => "E-Book"
// automatic convention
ProjectStep.entry('DiscussingChangeToPlan').label // => "Discussing Change to Plan"
```
> Enum entry & default label

- .yarn/patches/neo4j-driver-bolt-connection-npm-5.20.0-1f7809f435.patch
- .yarn/patches/neo4j-driver-core-npm-5.20.0-99216f6938.patch
- package.json
- src/components/authentication/authentication.edgedb.repository.ts
- src/components/authentication/authentication.repository.ts
- src/core/core.module.ts
- src/core/database/database.service.ts
- src/core/database/migration/migration.module.ts
- src/core/shutdown.hook.ts
- yarn.lock
- Bump neo4j driver
- Patch neo4j driver to stop preventing the process from closing when waiting to connect.
This is felt in CLI (console/REPL), where a command could finish before DB connection is created or needed. This is also exacerbated by the fact that sometimes the socket connection doesn't emit data (from server, though I'm not convinced it's an actual server problem) in these short windows. So the driver is left waiting for a successful response to a `logon` command, but it never shows up. 
- Allow the process to close while waiting for `waitForRootUserId()`
Like the above, if the retry loop is a timed out waiting state, don't let that block the process from closing.
- Patch neo4j driver to fix infinite loop with errors in transactions.
This will be released in 5.21 tomorrow(?) …
> Bump neo4j driver / Improve connection handling in CLI

- src/components/budget/budget.service.ts
- src/components/engagement/engagement.service.ts
- src/components/partnership/partnership.service.ts
- src/components/progress-report/media/progress-report-media.repository.ts
- src/components/progress-report/media/progress-report-media.service.ts
- src/core/database/common.repository.ts
- src/core/database/dto.repository.ts
- src/core/edgedb/common.repository.ts
- src/core/edgedb/dto.repository.ts
So one doesn't accidentally delete something legit but of the wrong type
> Limit `DtoRepo.deleteNode` to filter to the resource type by default

- src/common/make-enum.ts
Currently:
```ts
const Status = makeEnum(...);
Status.entry(...) // => { value: Status, label: string }
```
BUT if referencing the type generically:
```ts
const statusEnum: MadeEnum<Status>;
```
The entries didn't have a shape:
```ts
statusEnum.entry(...) // => empty object
```
Now they have the implicit shape:
```ts
statusEnum.entry(...) // => { value: Status, label: string }
```
This allows declaring extra entry declarations easier, by making it the second arg instead of third.
```ts
const statusEnum: MadeEnum<Status, { color: string }>;
statusEnum.entry(...).color // => string
```
This `Extra` generic really has nothing to do with the enum functionality, it's just extra "statics".
The type could be written as:
```ts
MadeEnum<Status> & { <Extras> }
```
Which we can still do now when …
> Fix MadeEnum type to provide value & label from entries implicitly

- src/common/db-sort.decorator.ts
- src/common/index.ts
- src/common/pagination.input.ts
- src/components/engagement/engagement.repository.ts
- src/components/language/language.repository.ts
- src/components/location/location.repository.ts
- src/components/periodic-report/periodic-report.repository.ts
- src/components/progress-report/dto/progress-report.entity.ts
- src/components/progress-report/progress-report-extra-for-periodic-interface.repository.ts
- src/components/project/project.repository.ts
- src/components/user/user.repository.ts
- src/core/database/query/index.ts
- src/core/database/query/lists.ts
- src/core/database/query/match-project-based-props.ts
- src/core/database/query/sorting.ts
This new functionality is driven by the need for the new UI to sort by deep fields.
Now the engagements list supports sorting by:
- `nameProjectFirst` - project name, then language/intern name.
- `nameProjectLast` - language/intern name, then project name.
(Yes yes I hear you thinking multi sorting. Some day.)
- `sensitivity`
- `project.primaryLocation.name`
- `language.ethnologue.code`
- `language.registryOfDialectsCode`
- `currentProgressReportDue.status`
Previously we had
```ts
query.apply(sorting(User, input, {
...
}))
```
This still works, but now it's recommended to switch to declare the matchers/sorters separately from application in a query.
```ts
// top level
export const userSorters = defineSorters(User, {
...
});
// in list()
query.apply(sortWith(userSorters, input))
```
This …
> [Neo4j] Nested Sorting + Engagement expanded usage

- src/common/make-enum.ts
```ts
// Given
let Color: MadeEnum<'red' | 'blue'>;
let AnEnum: MadeEnum<string>;
// Now
AnEnum = Color;
```
Two changes to make this compatible.
First, disallow direct access to member values when referencing generically.
Without this change `Color` can't be assigned to `AnEnum`, because the TS defines the member values as an index: `{ [x: string]: string }`. So since one has an index accessor and one doesn't, making them incompatible.
Secondly, The `entry()` arg type change also allows them to be compatible. Without it TS thinks something like `entry()` fn accepting any `string` is not compatible with `entry()` fn only accepting `'red' | 'blue'`. Using another generic at the function level somehow works around this, while still maintaining all the strictness.
> Fix `MadeEnum<'a'>` to be compatible with `MadeEnum<string>`

- src/common/types.ts
- src/components/budget/dto/budget-record.dto.ts
- src/components/budget/dto/budget.dto.ts
- src/components/engagement/dto/engagement.dto.ts
- src/components/language/dto/language.dto.ts
- src/components/partner/dto/partner.dto.ts
- src/components/partnership/dto/financial-reporting-type.enum.ts
- src/components/partnership/dto/partnership-agreement-status.enum.ts
- src/components/partnership/dto/partnership.dto.ts
- src/components/project/dto/project.dto.ts
- src/components/user/dto/user-status.enum.ts
- src/components/user/dto/user.dto.ts
I held off on this because TS doesn't natively support variadic generic parameters, so the conventional workaround is to add overloads for 1-10ish parameters before giving up.
But what we do right now is so clunky and we need up enumerating each interface 3 times.
So I bit the bullet. The type code is long, but cleans up the business logic nicely.
I also moved the remaining secured enum wrappers to their respective files. Most were already there, but there were some stragglers.
> New way to merge interfaces that's variadic and DRY for TS & GQL

- src/components/file/media/media.repository.ts
- src/components/product/product.repository.ts
- src/components/search/search.repository.ts
- src/core/database/query-augmentation/SubClauseCollection.ts
- src/core/database/query-augmentation/call.ts
- src/core/database/query-augmentation/condition-variables.ts
- src/core/database/query-augmentation/index.ts
- src/core/database/query-augmentation/yield.ts
- src/core/database/query/cypher-functions.ts
- src/core/database/query/full-text.ts
- src/core/database/query/index.ts
This unifies how full text indexes are configured & then referenced.
```ts
const MyIndex = FullTextIndex({ ... });
Query.apply(MyIndex.create())
Query.call(MyIndex.search(...).yield('node'))
```
Previously the index name was a magic string referenced in multiple spots.
Also added support for `Query.call()` & `Query.yield()`, which mostly just means we have less big string blocks.
```ts
.call('foo.bar.baz')
.call('foo.bar.baz', ['arg1'])
```
```ts
.yield('node')
.yield(['node', 'score'])
.yield('node as result')
.yield({
node: 'result',
score: 'rank',
})
```
Procedures can be declared with `procedure()` which provides more strict types.
```ts
.call(
apoc.create.setLabels('node', res.dbLabels)
.yield({ node: 'labelsAdded' })
)
```
- Fix cypher nested subqueries not using the same parameter …
> Neo4j: FullTextIndex / .call() / .yield()

- src/components/project/workflow/project-workflow.ts
Notify Financial Approvers when they need to take action, not when they just have taken action
> Notify Financial Approvers only when they need to take action

- src/components/engagement/engagement.repository.ts
- src/core/database/query/filters.ts
This is a quick fix. I don't really like it. I want to pursue passing the current user to neo4j in a similar fashion to EdgeDB.
> Fix requestingUser not being forward to project filters

- src/components/engagement/dto/list-engagements.dto.ts
- src/components/engagement/engagement.repository.ts
- src/core/database/query/filters.ts
> Engagement date filters

- src/core/database/query/sorting.ts
They were already last by default when sorting `ASC`, but neo4j defaults to putting them first when sorting `DESC`.
This changes `DESC` logic/query to have them also come last there.
```cql
order by name is not null desc, name desc
```
The first sort value is a boolean: nulls are 1, others are 0.
Following that sort normally on the value.
> Neo4j order nulls last always

- dbschema/engagement.esdl
- dbschema/migrations/00005-m1yeyjr.edgeql
- package.json
- src/common/id-field.ts
- src/common/resource.dto.ts
- src/components/ceremony/handlers/create-engagement-default-ceremony.handler.ts
- src/components/engagement/dto/engagement.dto.ts
- src/components/engagement/engagement.edgedb.repository.ts
- src/components/engagement/engagement.module.ts
- src/components/engagement/engagement.repository.ts
- src/components/engagement/engagement.resolver.ts
- src/components/engagement/events/engagement-created.event.ts
- src/components/engagement/events/engagement-updated.event.ts
- src/components/engagement/handlers/set-initial-end-date.handler.ts
- src/components/engagement/handlers/set-last-status-date.handler.ts
- src/core/edgedb/dto.repository.ts
- src/core/edgedb/index.ts
- src/core/resources/resource-name.types.ts
- src/core/resources/resource-resolver.service.ts
- src/core/resources/resources.host.ts
- yarn.lock
- Allow our `__typename` fields to be EdgeDB FQN names
- Switch to temp unreleased `@edgedb/generate` branch
edgedb/edgedb-js#1090
- Use `Engagement.resolve` function instead of `.__typename === '...'` to decouple the strings
- Created EdgeDB version of the Engagements repo with polymorphic hydration.
What's here is working which is the main thing, but it could be better.
The QB types could still be better to allow merging shapes & automatically handling EdgeQL type intersections & TS discrimated unions. One day.
- Pulled the rest of Bryan's queries & work from #3219
[Monday Task](https://seed-company-squad.monday.com/boards/5989610236/pulses/5792966980)
> [EdgeDB] Polymorphic queries & Engagement Repo

- dbschema/migrations/00006-m13cjeo.edgeql
- src/common/parent-types.ts
- src/common/types.ts
- src/components/file/media/media.dto.ts
- src/components/product/dto/update-product.dto.ts
- src/components/progress-report/media/dto/upload.dto.ts
- src/core/resources/resources.host.ts
- Adjust `getParentTypes` to work with `IntersectTypes()`
This is possible now that we have our own that adds a static `members` array.
- Replace the remaining usage of `IntersectionType` with our `IntersectTypes`
Notice how this removes the workaround needed on `Video`'s `DbLabels`.
- Remove split between GQL schema & class types in `ResourcesHost.getInterfaces`
The GQL schema is always available now that my PR got merged.
The class types (aka `EnhancedResource.interfaces`) now works for `IntersectTypes`
Still, having the split between our class type inheritance and GQL schema gives me pause for thought.
They should be in sync, so maybe one should just be picked always over the other?
I guess class types could still be private, not exposed to GQL schema.
And GQL schema needs the app to …
> Fix inheritance reflection with IntersectTypes()

- src/components/periodic-report/handlers/sync-progress-report-to-engagement.handler.ts
- src/components/progress-report/migrations/drop-internship-progress-reports.migration.ts
- src/components/progress-report/progress-report.module.ts
Remarkably we never checked the project/engagement type before creating/syncing progress reports.
These should only be for TranslationProjects/LanguageEngagements.
Add migration to drop these rogue entries that are never accessed.
> BUG: Don't create ProgressReports for InternshipEngagements

- src/components/periodic-report/periodic-report.repository.ts
This was supposed to be fixed with #3200
Now the _current report due_ is the most recently ending report (of the reports that have already ended) and of the reports with the same end date, the one that started first.
> Fix current report due prioritizing the final report

- .eslintrc.cjs
- src/common/context.type.ts
- src/common/exceptions/input.exception.ts
- src/components/authentication/current-user.provider.ts
- src/components/authentication/session.interceptor.ts
- src/components/file/file-url.controller.ts
- src/components/file/local-bucket.controller.ts
- src/core/config/config.service.ts
- src/core/core.module.ts
- src/core/database/abstract-transactional-mutations.interceptor.ts
- src/core/exception/exception.filter.ts
- src/core/exception/exception.normalizer.test.ts
- src/core/exception/exception.normalizer.ts
- src/core/exception/is-from-hack-attempt.ts
- src/core/graphql/gql-context.host.ts
- src/core/graphql/graphql.module.ts
- src/core/graphql/types.ts
- src/core/http/http.adapter.ts
- src/core/http/http.module.ts
- src/core/http/index.ts
- src/core/http/types.ts
- src/core/timeout.interceptor.ts
- src/core/tracing/xray-sampler.ts
- src/core/tracing/xray.middleware.ts
- src/main.ts
- test/utility/create-app.ts
I've created `~/core/http` to hold all http platform specifics. The codebase can reference this now and we don't have implementation details littered all over the codebase.
---
Also `.switchToHttp()` & `GqlExecutionContext` have strict return types (via declaration merging).
So the default return values of `any` is avoided and there's no need to give explicit generic at every usage.
> Infer/Decouple Platform types (HTTP/GraphQL)

- src/components/authentication/session.resolver.ts
- src/components/file/file-url.controller.ts
- src/components/file/local-bucket.controller.ts
- src/core/exception/exception.filter.ts
- src/core/http/http.adapter.ts
- src/core/http/http.module.ts
- src/core/tracing/xray.middleware.ts
- src/main.ts
- test/utility/create-app.ts
- Allow injecting `HttpAdapter` directly back by `Proxy` to `HttpAdapterHost`
- Move more calls to use `HttpAdapter` abstraction
- Use more standard request properties in xray middleware
- Move http server configuration into `HttpAdapter`
> More HttpAdapter usage

- src/components/engagement/engagement.repository.ts
- src/components/language/language.repository.ts
- src/components/location/location.repository.ts
- src/components/partner/partner.repository.ts
- src/components/partnership/partnership.repository.ts
- src/components/periodic-report/periodic-report.repository.ts
- src/components/product/product.repository.ts
- src/components/progress-report/media/progress-report-media.repository.ts
- src/components/progress-report/progress-report.repository.ts
- src/components/project/project-filters.query.ts
- src/core/database/query-augmentation/pattern-formatting.ts
- src/core/database/query/filters.ts
Previously we'd group where conditions into a single-ish where clause. If filters needed to select additional data they'd do so before declaring their where condition.
```cypher
match (node)-[:start { active: true }]->(start:Property)
match (node)-[:end { active: true }]->(end:Property)
...
where start.value >= $start and end.value <= $end
```
What this meant though is that filter work could have to be done on all of the `(node)`s instead of filtering immediately.
This was happening with ProgressReports trying to filter by project name.
All of the work to navigate to the project and run the full text search was happening on every report, before we filtered down to just reports for the given quarter.
Now I have changed it to have each filter produce its own where clause instead of grouping …
> Neo4j Filter Performance

- src/components/changeset/enforce-changeset-editable.pipe.ts
- src/components/progress-report/media/handlers/update-media-metadata-check.handler.ts
- src/core/graphql/graphql-error-formatter.ts
- src/core/graphql/graphql.module.ts
- src/core/graphql/graphql.options.ts
- src/core/index.ts
No logical changes here, just code shuffling.
- Don't export graphql from `core/index.ts` following suit of other core modules.
IMO that DX context is key/identifiable and shouldn't be flattened into `~/core`
- Rename `graphql.config.ts` so it isn't mistaken for IDE config.
My IDE (prob vscode too) tries to read/parse it as like a gql client configuration file.
- Move graphql error handling logic to a separate class.
Just a lot of code that could be segregated off.
> Shuffle `~/core/graphql` code around

- src/components/comments/comment-thread.loader.ts
- src/components/comments/comment-thread.resolver.ts
- src/components/comments/comment.service.ts
- src/components/comments/dto/list-comment-thread.dto.ts
- src/components/comments/dto/list-comment.dto.ts
Currently the comments canCreate just points to threads canCreate. I think this is fine, until it's not.
It's probable that we'd want to simplify and remove threads from authorization, since they just group comments.
But first we'd need to do the policy refactor for embedded resources
```diff
- r.X.children(c => c.comments...)
+ r.Comment.for('X')...
```
https://seed-company-squad.monday.com/boards/3451697530/pulses/7124883698
> Expose canCreate flags for Comments

- src/components/changeset/enforce-changeset-editable.pipe.ts
- src/core/graphql/gql-context.host.ts
- src/core/graphql/graphql.options.ts
- src/core/graphql/index.ts
This wasn't possible at the time.
Since then https://github.com/nestjs/graphql/issues/325 has been resolved & released in v11.0.0
This is better because this is a global pipe, so it runs for GQL requests & HTTP requests.
This check is easier because it doesn't assume that you are looking for a GQL context.
The ALS getter does assume this, so here we had to try/catch check for specific exception to ignore.
In general this is easier, and works now.
> Change EnforceChangesetEditablePipe to use injected, request-scoped GQL context

- src/core/http/http.module.ts
Previously method calls still had `this` bound to the proxy instead of the `HttpAdapter`.
So
```ts
class HttpAdapter {
getInstance() {
return this.instance;
}
}
```
Previously this calling the proxy `getInstance()` would ask the proxy for get `instance`. Obviously this is wrong `this` should be the actual class instance here, not the proxy.
Now we correctly scope `this` on getters with the `Reflect.get` 3rd parameter change.
Doing this fixed the need to have a special case for `httpAdapter` for the `HttpAdapterHost`.
And correctly explicitly bind functions to `HttpAdapter` instance instead of letting them be implicitly bound to the proxy.
> Fix HttpAdapter proxy `this` scoping

- src/components/progress-report/progress-report-extra-for-periodic-interface.repository.ts
- src/components/progress-summary/dto/progress-summary.dto.ts
- src/components/progress-summary/progress-summary.repository.ts
- src/core/database/query/sorting.ts
```gql
progressReports(input: {
sort: "cumulativeSummary.variance"
sort: "fiscalYearSummary.planned"
sort: "periodSummary.scheduleStatus"
}) {
...
}
```
https://seed-company-squad.monday.com/boards/5989610236/pulses/7551148894
> Add sorting for progress summaries

- src/components/post/post.service.ts
Assume the post object is all that is needed to check permissions. This is because we know we want the creator to be able to delete.
Previously other members could delete any post - this seems like a mistake. So this new code prevents that by not having the member context.
This kinda breaks the isolation I wanted these to have from policies. I wanted policies to be in full control of the permissions.
But we have to provide the right context/attributes. The project doesn't have the creator attribute (or even the right one).
We could do a better job exposing exactly what attributes are given to the privileges service instead of the dto object wholesale.
The policies are also ill-equipped to declare permissions for these "embedded" resources.
A rewrite is needed there.
> Fix delete auth check for posts delete

- src/components/file/file-url.controller.ts
Fastify appears to handle this differently than Express. If the variable segment is too long (~135 chars in this case), Fastify gives up.
Maybe for security? IDK
Changing now to a (optional) wildcard route.
We don't care what is after the file id - it is just for UX/DX.
> Fix file redirect route match regression

- src/components/engagement/engagement.repository.ts
- src/components/engagement/engagement.service.ts
- Remove duplicate call to update growth plan
- Explicitly throw errors when updating files in engagement when expected files do not exist
[Monday Story 0286](https://seed-company-squad.monday.com/boards/3451697530/pulses/7815063635)
> 0286 growth plan upload failure

- package.json
- src/core/graphql/driver.ts
- src/core/graphql/graphql.options.ts
- src/core/graphql/plugin.decorator.ts
- yarn.lock
It turns out it wasn't doing that much.
It also had a lot we don't need, like `express` support, and the legacy ws protocol.
This gives us complete control which will help with ws protocol
> Adopt @graphql-yoga/nestjs driver code locally

- src/components/pnp/isProgressCompletedOutsideProject.ts
- src/components/pnp/planning-sheet.ts
[Monday](https://seed-company-squad.monday.com/boards/3451697530/views/78801638/pulses/7995665803)
> Fix PnP progress step comparison with project date range

- src/components/authentication/authentication.module.ts
- src/components/authentication/authentication.service.ts
- src/components/progress-report/migrations/reextract-all-progress-reports.migration.ts
- src/core/config/config.service.ts
- src/core/data-loader/data-loader.config.ts
- src/core/data-loader/session-aware-loader.strategy.ts
- src/core/resources/resource.loader.ts
#3342 added usage of data loader (via `ResourceLoader`) which was triggered during a data migration. But those do not have a GQL Context, which is what holds the data data loaders.
This creates a global context for data loaders for CLI (REPL/Console/Jest).
So the entire process, short-lived, will share loaders. But I have caching disabled.
So this is more to allow the process to continue to work vs trying to improve performance.
Since CLI processes are not hot path.
I've created a bit of a mess trying to get a fake-ish root session established which the data loaders reference.
Creating an ALS unique for session/current user makes a lot of sense, and has been on the mental whiteboard for a while.
This should allow current user/session to be declared at will for:
- GQL requests pull from …
> Allow ResourceLoader within CLI migrations

- src/components/user/user.edgedb.repository.ts
- src/components/user/user.repository.ts
- src/components/user/user.resolver.ts
- src/components/user/user.service.ts
[Monday Story #0322](https://seed-company-squad.monday.com/boards/3451697530/pulses/8002040129)
> Add `getUserByEmail` query

- dbschema/migrations/00012-m1ec555.edgeql
- dbschema/partner.esdl
- src/components/partner/dto/create-partner.dto.ts
- src/components/partner/dto/partner.dto.ts
- src/components/partner/dto/update-partner.dto.ts
- src/components/partner/migrations/add-partner-approved-programs.migration.ts
- src/components/partner/partner.module.ts
- src/components/partner/partner.repository.ts
- src/components/project/dto/project-type.enum.ts
[Monday Task 0321](https://seed-company-squad.monday.com/boards/3451697530/pulses/8001931872)
> Add `approvedPrograms` to `Partner` object

- src/components/engagement/engagement.repository.ts
The `WITH` clause here acts to carry forward the node along with date override(`startDateOverride`, `endDateOverride`) and project date(`mouStart`, `mouEnd`) into the next part of the query.
> Fix Engagement Date Filtering

- src/components/pnp/planning-sheet.ts
- src/components/progress-report/migrations/reextract-all-progress-reports.migration.ts
I'm not sure why we were doing this in the first place. Presumably, authors would mistakenly write the first day of the month when they meant the last, and this was to help "correct" that for them.
Now we're hitting cases where the project doesn't end on the last day of the month, and we need to allow that.
Reverts 291f47f4bddf6fad8e9dda45f06f6e4817956720
> Stop assuming PnP project end date is the end of the month

- src/components/progress-summary/progress-summary.extractor.ts
Regressed with #3324
Since that PR changed the `summaryFrom` to always return an object with zeros, this check on line 64 failed.
Updated to check to ignore zeros, or fallback to returning zeros.
Regrettably this would've been caught had this eslint rule been enabled:
https://github.com/SeedCompany/cord-api-v3/blob/79875d5134689bf979bfd42a73d6b7c430a2ff2c/.eslintrc.cjs#L190-L191
> [PnP] Fix regression finding latest cumulative summary

- src/components/partner/dto/list-partner.dto.ts
- src/components/partner/partner.repository.ts
This adds 3 new filters to Partners: `globalInnovationsClient`, `types`, and `financialReportingTypes`.
> Add Partner filters for globalInnovationsClient, types, financialReportingTypes

- src/components/search/dto/search-results.dto.ts
- src/components/search/search.repository.ts
- src/components/search/search.service.ts
This mainly hasn't been touched in 3 years and it needed some love.
This has been pulled out of #3357.
This is mainly naming changes & type tweaks.
Functionally though there are a few changes:
- We actually ensure that the resource types returned are within the search types filter
- Because of this we also expand the interfaces listed in the `types` filter to their searchable concretes.
- We ensure that the results are unique. I don't believe this affects anything currently, but with #3357 there could be matches on two different objects that are then hydrated to the same object.
A big outstanding piece I want to do here is to convert this to use the data loaders.
This way there's only `O(1+R)` requests where `R` is the number of resources.
Currently it's `O(1+M)` where `M` is the number …
> Refactor & polish search service code

- src/core/graphql/driver.ts
The default limit is 10. I'm not really sure if we should use that or 25 is fine or what.
This allows a single HTTP request instead of 25 requests for 25 operations.
So this is an optimization for this protocol layer.
All of these operations are still processed individually/independently.
But it is possible for future work to optimize more. Like the data loaders could be cached by batched request instead of each operation.
> Enable batching up to 25 GQL operations over http

- src/common/index.ts
- src/common/trace-layer.ts
- src/components/admin/admin.gel.repository.ts
- src/components/authentication/authentication.gel.repository.ts
- src/components/authentication/authentication.repository.ts
- src/components/pin/pin.repository.ts
- src/components/user/system-agent.repository.ts
- src/core/database/common.repository.ts
- src/core/database/cypher.factory.ts
- src/core/database/database.service.ts
- src/core/database/migration/migration-runner.service.ts
- src/core/gel/common.repository.ts
- src/core/gel/gel.service.ts
- test/project.e2e-spec.ts
Previously we used the repository method names to identify the DB queries.
This was achieved via a stack trace.
This takes "a lot" of work (relatively) for the engine to calculate,
and since this is on the hot path it's bad.
Now, the strategy is to wrap all of these repository methods to run in an ALS context.
This essentially is an opt-in to allow inner logic to see what call it.
These names are also only calculated once and cached.
From my rough tests, previously the name generation could take up to a couple milliseconds, and **now it's 10-25x faster**.
Not a huge win but it is something that affects every db query call every time.
All of this work is wrapped up in an abstracted `TraceLayer`, and could be used for other tracing scopes. I'm aware this is fairly similar to actual tracing, …
> Optimize automatic DB query names with TraceLayer & ALS

- src/components/scripture/dto/scripture-reference.dto.ts
- src/components/scripture/dto/scripture-reference.transformer.ts
- src/components/scripture/gel.utils.ts
- yarn.lock
I'm guessing this regressed with a7187c6.
Fixed by using an actual getter/setter for the `book` in the initial `ScriptureReferenceInput` class. This allows for overriding in `ScriptureReferenceEndInput`. The getter/setter is re-defined to be a normal property on the first set. So this makes it function like it did before at runtime.
This issue was exacerbated by the fact that this failure to produce a valid scripture reference still produced a `Verse` object that happened to be invalid. This invalid `Verse` object caused an infinite loop in `mergeVerseRanges`. This was fixed here:
https://github.com/SeedCompany/libs/commit/b02ae4033c5bc573eb3d392c4e424051b3df45b8 Where runtime checks were added to prevent those invalid objects from being created, thus avoiding the infinite loop.
For some …
> Fix default last chapter/verse in scripture input

- src/components/search/search.service.ts
Concrete types do not include themselves in their implementations list. Nor should it really, it is a weird ask.
We'll add the input resource to this list, it could be a concrete or an abstract, and let the search types filter check directly below filter appropriately.
> Fix search filtering out concrete type filters

- src/components/engagement/engagement.service.ts
`Project.engagementTotal` will become stale
when creating an engagement if it is currently zero.
> When creating engagement, prevent stale project in data loader

- src/components/authentication/authentication.service.ts
It is easier to use this magic string than to try to keep track of UUIDs across envs.
> Allow "ghost" alias as an impersonation user

- src/components/engagement/engagement.service.ts
Sad that this as existed for so long. The src change is very obvious.
This is especially a pain point, because users will transition a project that then triggers logic to change the status to follow suit, then that fails because there is no transition found for engagements already in that status we are trying to change to (e.g. "Active to Active"), so we fail the whole project transition.
> Fix failing to find an engagement status transition when the status hasn't changed

- src/common/role.dto.ts
- src/components/project/project.service.ts
Roles like "Leadership" or "Administrator" shouldn't be assigned to projects
> Limit roles assigned to the project creator's membership to only those applicable

- src/components/partner/partner.gel.repository.ts
- src/core/gel/query-util/easy-insert.ts
I also needed to relax our `*Id` suffix types for insertion more.
It turns out it is just not possible to express this in TS.
We should rename them away at some point.
Until then, we will just have to live with runtime errors instead of type errors.
> [Gel] Fix missing links on Organization insertion

- src/components/project/handlers/set-department-id.handler.ts
- src/components/project/project.gel.repository.ts
- src/core/database/cypher.factory.ts
- src/core/database/database.module.ts
- src/core/database/index.ts
- src/core/database/transaction-retry.informer.ts
- src/core/database/transaction.ts
- src/core/gel/index.ts
- src/core/gel/transaction.context.ts
Since the collision produces a database constraint error, the whole transaction is in a rollback state, and it is not valid to continue making queries.
Thus it is the entire transaction work (GQL mutation in our setup) that needs to be retried.
This introduces a `TransactionRetryInformer` service as a decoupled way to allow the codebase to inform the database transaction layer that a certain error should be retried.
I've also applied this to the Gel path for assigning department IDs, so it is no longer left in the cold for this path.
This only addresses race conditions when two distinct mutations are trying to assign the same ID.
It is still not possible to have a single gql-mutation/db-transaction/db-query assigning multiple department IDs (using the same id block space), but this is not …
> Retry whole transactions on department id collisions

- src/components/pnp/planning-sheet.ts
This regressed with  e14cb8771b3dd6405dd15569344601e581ca2b0f / #3385, which went live on Monday (2 days ago).
1. The base `PlanningSheet` class initializing `goalStart`
2. `goalColumn` was read, which read the `revisionCell`
3. `revisionCell` wasn't initialized yet, because it is defined in child classes.
Switching `goalStart` to be lazy fixes this.
It was also the only property in the base class that was eagerly initialized.
> Fix PnP init regression from e14cb87

- src/components/authorization/policies/by-role/project-manager.policy.ts
I changed to use `.or.specifically` so the membership condition from the resource level isn't implicitly passed to properties. This is clearer & reads better here.
So the effective change is granting mou start/end [read](https://github.com/SeedCompany/cord-api-v3/compare/bugfix/project-date-perms?expand=1#diff-2ce6dc91076b6679b82573512d72c4b924876b2bde1e363c03f9353d4eb1e782R156) to all projects, not just projects with a membership.
> Fix FPMs not being able to view other projects dates from 9988e85

- dbschema/common.gel
- dbschema/migrations/00018-m1jf7p4.edgeql
- src/common/exceptions/index.ts
- src/common/exceptions/range.exception.ts
- src/components/engagement/dto/engagement.dto.ts
- src/components/engagement/engagement.gel.repository.ts
- src/components/engagement/engagement.repository.ts
- src/components/engagement/engagement.service.ts
- src/components/engagement/handlers/index.ts
- src/components/engagement/handlers/validate-eng-date-overrides-on-project-change.handler.ts
- src/components/project/project.service.ts
- src/core/database/query/cypher-functions.ts
- Project date range now has to be valid
- Engagement override date range now has to be valid
- Engagement override dates have to be within the project date range
`Engagement` now also hydrates _labels_ to help identity in various situations.
I still need to verify production data/fix
> Validate Project/Engagement date ranges

- src/common/exceptions/date-override-conflict.exception.ts
- src/common/exceptions/index.ts
- src/components/engagement/handlers/validate-eng-date-overrides-on-project-change.handler.ts
- src/components/partnership/handlers/index.ts
- src/components/partnership/handlers/validate-partnership-date-overrides-on-project-change.handler.ts
- src/components/partnership/partnership.gel.repository.ts
- src/components/partnership/partnership.repository.ts
- src/components/partnership/partnership.service.ts
- src/components/project/events/project-updated.event.ts
Following up on #3396 to validate Partnerships as well
Honestly I forgot these existed when doing that one.
Re-did the exception shape to be more generic.
> Validate partnership dates

- src/common/exceptions/date-override-conflict.exception.ts
- src/components/partnership/handlers/validate-partnership-date-overrides-on-project-change.handler.ts
Left as TODO in a5bf2f9ab4f77c008222ea04638c6bc37483452a
> Add labels to conflicting partnership date range errors

- src/components/changeset/enforce-changeset-editable.pipe.ts
- src/core/graphql/gql-context.host.ts
- src/core/graphql/index.ts
I didn't realize it at the time, but because this is a global pipe, it applies as a dependency to all controllers/resolvers. Making this request scoped means all controllers/resolvers become request scoped as well.
Revert to using `GqlContextHost`/ALS and add `contextMaybe` to prevent the former try/catch need.
> Revert #3309 / 1fa42ad for EnforceChangesetEditablePipe

- .github/workflows/test.yml
- docker-compose.yml
Obviously, they have a new versioning schema, but this is not treated as a major.
It appears that 5.26.6 (released 2025-05-06, two days before this commit) has a regression with optional match clauses.
This upgrade is a hope to fix that.
Superceeds #3418, hopefully.
> Bump Neo4j 5.26 -> 2025.04

- src/components/project/project.repository.ts
This key matches the data path and should probably be used going forward
This is part of a larger change to fix a UI bug, where a created project fails to add itself to the cached lists when the user has sorted by engagments.
> Allow sorting project's engagement totals with `engagements.total`

- src/common/resource.dto.ts
With `Props`/`SecuredProps` on the chopping block, we don't really a have a way at runtime to check if a class is a resource.
But really what is a "resource"? It has some kind of alignment with GQL's `Resource` interface, but it is kinda fuzzy. It really could be any class model at this point. I think this is ok. We need to facilitate some inner workings that we don't want exposed to the GraphQL schema. Models need to be registered for dynamic lookup, be used in policies, but maybe there are situations we don't want to officially declare them, with `@RegisterResource`.
Some current examples are `Pinnable`, `ChangesetAware`.
I'm not sure. I'm not sure I believe the above. Fuzziness just leads to confusion.
The alternative to this, is to just check if the resource has been registered, and …
> Remove/replace `isResourceClass`

- src/components/authentication/extra-info.resolver.ts
- src/components/file/media/media.dto.ts
- src/components/file/media/media.repository.ts
- src/components/notifications/notification.repository.ts
- src/components/progress-report/media/dto/media.dto.ts
- src/components/project/dto/project.dto.ts
- src/core/database/changes.ts
- src/core/database/common.repository.ts
- src/core/database/dto.repository.ts
- src/core/database/query/sorting.ts
This indirection allows them to be provided in different ways, like with a transformer, or external metadata generation.
The `BaseNodeProps` stuff here is clunky. I don't like it, and it could be refined more. But it is not wide spread and maybe we just wait and delete it with Gel migration.
> Replace remaining direct usages of static Props/SecuredProps

- src/components/project/dto/create-project.dto.ts
- src/components/project/dto/update-project.dto.ts
- src/components/project/project.repository.ts
- src/components/project/project.service.ts
- src/components/project/workflow/dto/workflow-transition.dto.ts
- src/components/project/workflow/migrations/step-history-to-workflow-events.migration.ts
- src/components/project/workflow/project-workflow.service.ts
- src/components/project/workflow/transitions/dynamic-step.ts
UI is migrated to new paths & doesn't reference these type names.
> Remove legacy APIs & transitional code for project workflow

- src/common/xlsx.util.ts
- src/components/product/pnp-product-sync.service.ts
If an excel file is saved while there are multiple open, it can add internal index workbook references in named ranges (probably all formulas?)
Like:
```
[1]SheetName!A1
```
This can be safely parsed to mean `A1` on `SheetName`.
The index is an internal thing that I don't think is even presented to users in Excel, but it does leak through in our navigation tools.
Now we ignore those optional `[N]` prefixes.
We also just ignore any named ranges that correspond to nonexistent sheets now.
This will prevent an all out extract crash just from a named range that we do not care about.
> Fix PnP named range crashes

- src/components/project/dto/project.dto.ts
- src/components/user/dto/actor.dto.ts
- src/components/user/dto/user.dto.ts
- src/components/user/system-agent.gel.repository.ts
- src/components/user/system-agent.neo4j.repository.ts
- src/core/resources/resource-name.types.ts
I think this must've changed when we removed the static `Props` declarations.
Previously comparing static types worked, probably because of the static `Props` list.
Now comparing instance types appears to work, which seems more correct anyway.
However, this uses duck typing / shape matching, not actual inheritance.
So we had a problem with `Pinnable` & `Actor`, both of which only require an `id` prop.
I "fixed", worked around this by declaring the `__typename` string literals for `Actor`/`User`/`SystemAgent`.
This is more feasible than enumerating the concrete types of `Pinnable` & doing the same on them.
It's working now, but not the most stable situation to be in. Will continue pondering other ways to address this.
> Fix inheritance on ID/ResourceName types

- src/core/graphql/driver.ts
This stabilized in Node 22, and seems to be recommended for the simple situations like this case here.
> Swap AsyncResource with ALS.snapshot

- src/components/authentication/anonymous.decorator.ts
- src/components/authentication/auth-level.decorator.ts
- src/components/authentication/index.ts
- src/components/authentication/login.resolver.ts
- src/components/authentication/password.resolver.ts
- src/components/authentication/register.resolver.ts
- src/components/authentication/session.interceptor.ts
- src/components/authentication/session.resolver.ts
- src/components/file/file-url.controller.ts
- src/components/file/local-bucket.controller.ts
- src/core/authentication/index.ts
- src/core/core.controller.ts
Replacing `Anonymous/LoggedIn` decorators with an expanded `AuthLevel`.
This new one allows declaring that a session should not even be tried to be resumed, which is  needed with our HTTP routes.
So the 3 levels:
- `sessionless` - do not attempt a credential gathering from the request
- `anonymous` - gather credential info & validate token is in db & resume session
- `authenticated` - assert that the session is tied to a user aka "logged in"
Now `SessionInterceptor` doesn't have to make assumptions about the codebase.
It doesn't have to know to avoid starting a session for the `session` gql query.
It doesn't have to know to avoid starting a session for http requests unless
it has the session watermark/(session decorator).
This is a smaller PR but distinct with its business logic change, …
> `AuthLevel` decorator

- src/components/field-region/events/field-region-updated.event.ts
- src/components/field-region/field-region.gel.repository.ts
- src/components/field-region/field-region.module.ts
- src/components/field-region/field-region.repository.ts
- src/components/field-region/field-region.service.ts
- src/components/field-region/handlers/restrict-region-director-removal.handler.ts
- src/components/field-zone/events/field-zone-updated.event.ts
- src/components/field-zone/field-zone.gel.repository.ts
- src/components/field-zone/field-zone.module.ts
- src/components/field-zone/field-zone.repository.ts
- src/components/field-zone/field-zone.service.ts
- src/components/field-zone/handlers/restrict-zone-director-removal.handler.ts
- src/components/user/events/user-updated.event.ts
- src/components/user/user.service.ts
- test/region.e2e-spec.ts
- test/utility/create-region.ts
- test/utility/create-zone.ts
- test/zone.e2e-spec.ts
- Directors of Field Zones need to have the `FieldOperationsDirector` role
- Directors of Field Regions need to have the `RegionalDirector` role
- These users cannot have those roles removed if they are currently a director of any zones/regions
> Validate field region/zone director roles

- src/components/project/project.service.ts
New ECMA class fields have all properties defined as undefined. Keys are not optional.
So
```ts
{
id: project.id,
...{ id: undefined },
}
```
So undefined overrides our id instead of us forcing it.
This caused queries like
```graphql
query {
project(id: "") {
engagements(input: { filter: { project: {} } }) {
total
items {
id
}
}
}
}
```
to return more engagements than the one for the project
> Fix Project.engagements() with input.filter.project usage

- src/components/pnp/findStepColumns.ts
- src/components/product-progress/step-progress-extractor.service.ts
- src/components/product/product.extractor.ts
This will remedy the custom step header error for a leadership approved list of alternative headers by replacing custom steps with standard ones.
> Support specific aliases for PnP step labels

- src/components/project/project-member/dto/project-member.dto.ts
- src/components/project/project-member/member-project-connection.resolver.ts
- src/components/project/project-member/membership-by-project-and-user.loader.ts
- src/components/project/project-member/project-member.gel.repository.ts
- src/components/project/project-member/project-member.module.ts
- src/components/project/project-member/project-member.repository.ts
- src/components/project/project-member/project-member.service.ts
- src/components/user/dto/list-users.dto.ts
This should allow an enriched project list on the user page.
```graphql
query UserProjects($user: ID!) {
user(id: $user) {
projects(input: { filter: { members: { user: { id: $user } } } }) {
...normalProjectColumns
membership(user: $user) {
roles {
value
}
}
}
}
}
```
> Expose Project.membership(user: ID)

- src/components/engagement/handlers/apply-finalized-changeset-to-engagement.handler.ts
- src/components/field-region/handlers/restrict-region-director-removal.handler.ts
- src/components/field-zone/handlers/restrict-zone-director-removal.handler.ts
These were found while enabling `no-unnecessary-condition` lint rule, but are actual bugs so I wanted to call them out separately
> Fix change check on region/zone director role removal

- src/common/resource.dto.ts
- src/components/budget/dto/budget.dto.ts
- src/components/comments/dto/comment-thread.dto.ts
- src/components/comments/dto/commentable.dto.ts
- src/components/engagement/dto/engagement.dto.ts
- src/components/language/dto/language.dto.ts
- src/components/organization/dto/organization.dto.ts
- src/components/partner/dto/partner.dto.ts
- src/components/partnership/dto/partnership.dto.ts
- src/components/post/dto/postable.dto.ts
- src/components/progress-report/dto/progress-report.dto.ts
- src/components/project/dto/project.dto.ts
- src/components/prompts/dto/prompt-response.dto.ts
- src/components/user/dto/user.dto.ts
Updated concrete Resources to pull in these Relations.
Added method to "patch in" a relation to the base resource indirectly. Seen here:
```ts
declare module '~/common/resource.dto' {
export interface DeclareResourceRelations {
readonly foos: readonly [typeof Foo];
}
}
patchMethod(Resource, 'Relations', (orig) => () => ({
...orig(),
foos: [Foo] as const,
}));
```
> Allow Resource to have Relations

- src/components/engagement/dto/list-engagements.dto.ts
- src/components/engagement/engagement.resolver.ts
Shamelessly reusing @CarsonF's[ previous PR description](https://github.com/SeedCompany/cord-api-v3/pull/3081):
> It's annoying to have to add fragments to narrow type when you all you want is [internship] engagements.
> It's problematic with codegen expecting certain types that only exist on the concrete.
Related to [#860](https://github.com/SeedCompany/seed-api/issues/860)
> Add GQL queries for InternshipEngagements

- dbschema/migrations/00021-m1vlvhh.edgeql
- dbschema/y.department-id.gel
- src/components/project/handlers/set-department-id.handler.ts
Cherry-picks work from #3560 and adds schema parity for Gel.
> Exclude external department IDs from being available

- src/common/file-upload.scalar.ts
- src/components/file/file-url.controller.ts
- src/components/file/file-url.resolver-util.ts
- src/components/file/file-version.resolver.ts
- src/components/file/file.resolver.ts
- src/components/file/file.service.ts
- src/components/file/media-url.resolver.ts
- `kind: Evergreen` - Allow generating a url for a `File` that points to that `File` aka the latest version of the file when the url requested, instead of the current version at time of generation.
This allows the url to live / be referenced longer than the API call for the associated data, which could be useful is some cases.
- Allow overriding the file name in the generated url. Filenames before were are directly from users via rename or the latest version of the actual file uploaded. In some cases, we want a prettier name or maybe more generic name, for displaying.
- This name in the url path now also applies to the filename that is downloaded as well.
- Fixed direct file uploads (in Apollo Explorer) which regressed somewhere around the move to Yoga with its `File` polyfill.
> More File Url options & some fixes
