src/components/user/user.dto.ts, src/components/user/user.service.ts, test/language.e2e-spec.ts, test/user.e2e-spec.ts
=> Cord api 6

src/app.module.ts, src/components/budget/budget.dto.ts, src/components/budget/budget.resolver.ts, src/components/budget/budget.service.ts, src/components/budget/budget.ts
=> cord-api-26 

src/app.module.ts, src/components/budget/budget.service.ts, src/components/budget/budget.ts, test/area.e2e-spec.ts, test/budget.e2e-spec.ts
Budget CRUD
I added tests and then made them pass
=> tests pass

src/components/location/location.dto.ts, src/components/location/location.resolver.ts, src/components/location/location.service.ts, src/components/location/location.ts, test/location.e2e-spec.ts
Done with CRUD operation , list countries and test cases
=> "cord-api-25"

package-lock.json, src/components/product/product.dto.ts, src/components/product/product.resolver.ts, src/components/product/product.service.ts, src/components/product/product.ts, test/product.e2e-spec.ts
=> Cord api 23

src/app.module.ts, src/components/project-engagement/engagement.ts, src/components/project-engagement/project-engagement.dto.ts, src/components/project-engagement/project-engagement.resolver.ts, src/components/project-engagement/project-engagement.service.ts, test/language.e2e-spec.ts, test/project-engagement.e2e-spec.ts
project engagement CRUD and tests.  creates relationship to language
=> Cord api 47

src/components/product/product.dto.ts, src/components/product/product.service.ts, test/location.e2e-spec.ts, test/product.e2e-spec.ts
=> ‘cord-api-53’

src/app.module.ts, src/components/internship-engagement/engagement.ts, src/components/internship-engagement/internship-engagement.dto.ts, src/components/internship-engagement/internship-engagement.resolver.ts, src/components/internship-engagement/internship-engagement.service.ts, src/components/project-engagement/project-engagement.dto.ts, src/components/user/user.service.ts, test/internship-engagement.e2e-spec.ts, test/user.e2e-spec.ts
internship-engagements CRUD, intern is a user
=> Cord api 48

src/components/user/unavailability/unavailability.service.ts
‘create_for_User_Unavailability’  
=> cord-api-78

src/components/user/unavailability/unavailability.service.ts, test/unavailability.e2e-spec.ts
update works for unavailability
=> Unavail update

src/components/language/language.service.ts, src/components/user/education/education.service.ts, src/components/user/unavailability/unavailability.service.ts, src/core/database/property-updater.service.ts, test/education.e2e-spec.ts, test/language.e2e-spec.ts
delete function.  
Uses raw DB query instead of Cypher query builder
=> Del template

src/components/user/user.service.ts, test/utility/create-user.ts, test/utility/fragments.ts
@michaelmarshall , 
Please review my code changes and let me know the reason why values are not set however the relations  are created (as per our discussion in the zoom call)
Thanks,
Koijam
=> Cord api 112 : Add phone, timezone, and bio to user.service.ts

src/components/user/unavailability/unavailability.service.ts, src/components/user/user.service.ts, src/core/database/property-updater.service.ts, test/unavailability.e2e-spec.ts
Most of create abstraction done
=> Cord api 92

src/components/organization/organization.service.ts, src/core/database/property-updater.service.ts, test/organization.e2e-spec.ts
Refactored Organization service with generics, Can you please check once and if any changes require, add comments
=> "cord-api-116: "

src/components/user/user.service.ts, src/core/config/config.service.ts, src/core/database/property-updater.service.ts
@michaelmarshall, Please review the PR. 
Have added a generic function to fetch data based on the given keys to a node.
=> Generic read function #110

src/components/user/user.service.ts, test/user.e2e-spec.ts
=> Cord api 122

src/components/user/dto/check-email.dto.ts, src/components/user/dto/index.ts, src/components/user/user.resolver.ts, src/components/user/user.service.ts, test/user.e2e-spec.ts
======Query=========  
query{  
checkEmail(input:{  
email: "test@test.com"  
})  
}
==========Result========  
{  
"data": {  
"checkEmail": false  
}  
}
At this time, I checked email existence on session condition. I can change it whatever our API needs.
=> email check done.

src/components/file/file.module.ts, src/components/file/file.service.ts, src/components/user/user.service.ts, src/core/database/property-updater.service.ts, test/file.e2e-spec.ts, test/utility/create-file.ts, test/utility/create-user.ts, test/utility/fragments.ts
this has a user attached to file with createdby relationship.
=> cord-api-130

package.json, src/components/auth/auth.dto.ts, src/components/auth/auth.resolver.ts, src/components/auth/auth.service.ts, src/components/user/user.resolver.ts, src/components/user/user.service.ts, src/core/aws-ses.factory.ts, src/core/config/config.service.ts, src/core/core.module.ts, test/auth.e2e-spec.ts, test/user.e2e-spec.ts, test/utility/aws.ts, test/utility/create-app.ts, yarn.lock
Completed reset password.
- 2 endpoints
- AWS configuration and SES config.
At this time, I tested this endpoint with my AWS account info.
=> Forgot/Reset Password

.github/workflows/ci.yml, src/components/location/dto/update-location.dto.ts, src/components/location/location.module.ts, src/components/location/location.service.ts, src/components/user/dto/user.dto.ts, src/components/user/user.service.ts, test/country.e2e-spec.ts, test/jest-e2e.json, test/region.e2e-spec.ts, test/unavailability.e2e-spec.ts, test/utility/create-country.ts, test/utility/create-region.ts, test/utility/create-zone.ts, test/utility/fragments.ts, test/utility/index.ts, test/zone.e2e-spec.ts
=> Cord api 189

src/components/engagement/engagement.service.ts, src/components/engagement/language-engagement.resolver.ts, src/components/product/dto/create-product.dto.ts, src/components/product/dto/list-product.dto.ts, src/components/product/dto/product-approach.ts, src/components/product/dto/product-medium.ts, src/components/product/dto/product-methodology.ts, src/components/product/dto/product-purpose.ts, src/components/product/dto/update-product.dto.ts, src/components/product/product.service.ts, test/utility/create-product.ts
- Product Approach is determined by methodology
- Remove setters
- Update query to set db property based on methodology
- Connect products to language engagements
Closes #171
=> Update products DTOs

src/common/calendar-date.ts, src/common/date-filter.input.ts, src/common/index.ts, src/common/luxon.graphql.ts, src/common/secured-property.ts, src/components/cermony/dto/create-ceremony.dto.ts, src/components/cermony/dto/update-ceremony.dto.ts, src/components/engagement/dto/create-engagement.dto.ts, src/components/engagement/dto/update-engagement.dto.ts, src/components/partnership/dto/create-partnership.dto.ts, src/components/partnership/dto/update-partnership.dto.ts, src/components/project/dto/create-project.dto.ts, src/components/project/dto/update-project.dto.ts, src/components/project/project.service.ts, src/components/user/user.service.ts, src/core/core.module.ts, src/core/database/cypher.factory.ts, src/core/database/database.module.ts, src/core/database/database.service.ts, src/core/database/parameter-transformer.service.ts, src/core/database/transformer.ts, test/utility/create-partnership.ts
- Created `CalendarDate`
- A separate object from `DateTime` that's only used for dates
- It does tweak a couple of the inherited functionality. More may come later.
- Created `ParameterTransformer` to transform db query parameters _transparently_
- Move database services to their own module
Fixes #210
=> CalendarDate & DB Transformation

docs/Cord API v3.postman_collection.json, docs/My Workspace.postman_globals.json, docs/integration.postman_environment.json, docs/local.postman_environment.json
Updated request to not use Token in header at places. Added exported global variable json file.
=> Updated request to not use Token in header/Added exported global variable json file

src/core/database/database.service.ts, src/core/database/parameter-transformer.service.ts, src/core/database/transformer.ts
Transforms Neo4J `Duration`'s to Luxon `Duration`'s transparently
=> Transform Neo Durations to Luxon Durations

docs/Cord API v3.postman_collection.json, docs/My Workspace.postman_globals.json, docs/integration.postman_environment.json, docs/local.postman_environment.json
Each request/input variables has all possible parameters
=> Each request/input variables has all possible parameters

src/components/file/file.service.spec.ts, src/components/file/file.service.ts, test/file.e2e-spec.ts, test/utility/create-file.ts, test/utility/index.ts
Note: Move object is not ready yet
=> delete and rename for file service with unit test

src/components/file/file.resolver.ts, src/components/file/file.service.ts, src/core/database/database.service.ts
– implements update file and move file
– move currently handles file nodes only but not directory
=> finishes crud for fileNode

src/components/auth/auth.service.ts, src/components/file/file.service.ts, src/components/language/language.service.ts, src/components/location/location.service.ts, src/components/organization/organization.service.ts, src/components/user/education/education.service.ts, src/main.ts, test/country.e2e-spec.ts, test/education.e2e-spec.ts, test/file.e2e-spec.ts, test/language.e2e-spec.ts, test/region.e2e-spec.ts, test/unavailability.e2e-spec.ts, test/zone.e2e-spec.ts
- Replace console.logs with logger calls
- Remove useless try/catches
=> No console

src/components/partnership/partnership.service.spec.ts
=> created partnership.service spec

src/components/project/project.service.ts, test/project.e2e-spec.ts, test/utility/create-project.ts
Adds constraints 
- ProjectName for unique and existence
- ProjectState for existence
- ProjectStatus for existence
=> DB constraints for project service

src/components/budget/budget.module.ts, src/components/budget/budget.service.ts, src/components/partnership/dto/list-partnership.dto.ts, src/components/partnership/partnership.service.ts, test/budget.e2e-spec.ts, test/partnership.e2e-spec.ts, test/utility/create-organization.ts, test/utility/create-partnership.ts
=> 373 Project and Partnership connection

src/components/engagement/engagement.service.spec.ts
service unit test for engagement
=> created service unit test for engagement

src/components/engagement/engagement.service.spec.ts, src/components/location/location.service.spec.ts, src/components/project/project.service.spec.ts
Fix #339 and #348 from #346 merge
=> Fix from auth rename

package.json, src/components/budget/dto/budget.ts, src/components/budget/dto/update-budget.dto.ts, src/components/user/education/dto/create-education.dto.ts, src/components/user/education/dto/education.dto.ts, src/components/user/education/dto/update-education.dto.ts, src/core/config/config.service.ts, src/core/database/cypher.factory.ts, src/core/database/indexer/indexer.module.ts, src/core/logger/formatters.ts, src/core/logger/level-matcher.provider.ts, yarn.lock
=> Display multiline strings in CLI better & tweaks

src/components/authentication/authentication.service.ts, src/core/config/config.service.ts, src/core/email/email.service.ts, src/core/email/templates/mjml.tsx, src/core/exception.filter.ts
- Fix frontend reset password url and form it from a single base path
- Wait for 10 secs before deleting temp file after opening in chrome
- Update exception filter to handle generic Errors as server errors
- Pull title via context instead of manually traversing tree
=> Email Fixes

src/components/organization/organization.service.ts
Organization name should be unique globally.
=> fixed unique org name issue

.vscode/launch.json, src/components/budget/budget.service.ts, src/components/user/user.service.ts
Budget and budget record refactor
=> Cord api 315 budget sg

src/components/user/user.service.ts, test/authentication.e2e-spec.ts, test/utility/index.ts, test/utility/logout.ts
=> Added login test case, Logout Func, modified user perm

src/components/ceremony/ceremony.service.ts, src/components/engagement/dto/engagement.dto.ts, src/components/engagement/engagement.service.ts, test/engagement.e2e-spec.ts
This has language engagements and internship engagements of sg refactor for create, read and update.
=> sg refactor of engagement service 

src/components/project/dto/project.dto.ts, src/components/project/project-lazy-fields.resolver.ts, src/components/project/project.service.ts
I am not sure about two field in response -> canCreate, and canRead.
Just set up it as true.
=> project lazy field for partnership

src/components/engagement/engagement.service.ts, src/core/database/database.service.ts, test/engagement.e2e-spec.ts
Fixes - update and consistency
=> fix internships

src/components/product/film/dto/create-film.dto.ts, src/components/product/film/dto/film.ts, src/components/product/film/dto/index.ts, src/components/product/film/dto/list-film.dto.ts, src/components/product/film/dto/range.ts, src/components/product/film/dto/update-film.dto.ts, src/components/product/film/film.module.ts, src/components/product/film/film.resolver.ts, src/components/product/film/film.service.ts, src/components/product/film/index.ts, src/components/product/index.ts, src/components/product/product.module.ts, src/components/product/range/dto/create-range.dto.ts, src/components/product/range/dto/index.ts, src/components/product/range/dto/list-range.dto.ts, src/components/product/range/dto/range.ts, src/components/product/range/dto/update-range.dto.ts, src/components/product/range/index.ts, src/components/product/range/range.module.ts, src/components/product/range/range.service.ts, src/components/user/user.service.ts, src/core/database/database.service.ts, test/film.e2e-spec.ts, test/utility/create-film.ts, test/utility/fragments.ts, test/utility/index.ts
Feature Film Ticket No : #388 
--> Created DTOs
--> Create Film
--> Read Film
--> Delete Film
--> Listing Films
--> Testing e2e
=> Created Film DTOs, CreateFilm, ReadFilm, DeleteFilm, ListFilm

src/components/product/index.ts, src/components/product/product.module.ts, src/components/product/story/dto/create-story.dto.ts, src/components/product/story/dto/index.ts, src/components/product/story/dto/list-story.dto.ts, src/components/product/story/dto/story.ts, src/components/product/story/dto/update-story.dto.ts, src/components/product/story/index.ts, src/components/product/story/story.module.ts, src/components/product/story/story.resolver.ts, src/components/product/story/story.service.ts, src/components/user/user.service.ts, test/story.e2e-spec.ts, test/utility/create-story.ts, test/utility/fragments.ts, test/utility/index.ts
=> Cord api v3 389

src/components/file/file-version.resolver.ts, src/components/file/file.service.ts, test/file.e2e-spec.ts
- Add download url for file versions
- Enforce directories are only created under directories
- Enforce directories have unique names inside their parent
=> Add download url for file versions & more checks

src/components/organization/organization.service.ts, src/core/database/database.service.ts
Created sgReadOne function in db Service #474
=> Created sgReadOne function in db Service 

src/components/budget/budget.service.ts
=> The first budget status 'current' with the project creation

src/components/organization/organization.service.ts, src/components/project/project.service.ts, src/core/database/query.helpers.ts, src/core/database/query.ts
In doing so abstracted running a list query as well
=> Fix list returns for empty lists

src/components/authorization/authorization.service.ts, src/components/budget/budget.service.ts, src/components/ceremony/ceremony.service.ts, src/components/engagement/engagement.service.ts, src/components/language/language.service.ts, src/components/location/location.service.ts, src/components/partnership/partnership.service.ts, src/components/product/film/film.service.ts, src/components/product/literacy-material/literacy-material.service.ts, src/components/product/story/story.service.ts, src/components/project/project.service.ts, src/components/user/education/education.service.ts, src/core/database/database.service.ts, test/engagement.e2e-spec.ts
=> Engagement status

src/app.module.ts, src/components/search/dto/index.ts, src/components/search/dto/search-results.dto.ts, src/components/search/dto/search.dto.ts, src/components/search/index.ts, src/components/search/search.module.ts, src/components/search/search.resolver.ts, src/components/search/search.service.ts
=> Implement Search API

test/engagement.e2e-spec.ts
This is a test that proves #620 needs more information.  
The current engagements list will return both kinds of engagements.
=> 620 eng list

src/common/index.ts, src/common/name-field.ts, src/components/language/dto/create-language.dto.ts, src/components/language/dto/update-language.dto.ts, src/components/location/dto/create-location.dto.ts, src/components/location/dto/update-location.dto.ts, src/components/organization/dto/create-organization.dto.ts, src/components/organization/dto/update-organization.dto.ts, src/components/product/film/dto/create-film.dto.ts, src/components/product/film/dto/update-film.dto.ts, src/components/product/literacy-material/dto/create-literacy-material.dto.ts, src/components/product/literacy-material/dto/update-literacy-material.dto.ts, src/components/product/story/dto/create-story.dto.ts, src/components/product/story/dto/update-story.dto.ts, src/components/project/dto/create-project.dto.ts, src/components/project/dto/update-project.dto.ts, src/components/user/dto/create-person.dto.ts, src/components/user/dto/update-user.dto.ts
=> Trim name fields on input

src/components/engagement/engagement.service.ts, test/engagement.e2e-spec.ts, test/utility/create-engagement.ts, test/utility/fragments.ts
#609 and #610 
Does not satisfy #642 which I will do next
=> 609 status modified at

src/components/project/project.service.ts
Removed commented Lines ( for property [ Type ])
=> Fixed create project type error

src/components/partnership/dto/list-partnership.dto.ts, test/partnership.e2e-spec.ts
Removed agreementStatus from filters
=> fixed partner list issue

src/components/project/project-member/project-member.service.ts, test/utility/create-language.ts
https://github.com/SeedCompany/cord-api-v3/issues/621
=> Issue 621: Create Project Member modifiedAt null error

src/components/engagement/engagement.service.ts, test/engagement.e2e-spec.ts
Now when an internId, mentorId, countryoforiginId or projectId is bad, the create fails and there is an error message to tell you which one is bad.
=> 642 int engagement create fail

src/components/engagement/engagement.service.ts, test/engagement.e2e-spec.ts
=> 648 - InternshipEngagement.methodologies should return empty array by default instead of error

src/components/engagement/engagement.service.ts, test/engagement.e2e-spec.ts
https://github.com/SeedCompany/cord-api-v3/issues/647
- LanguageEngagements can only be created on TranslationProjects
- InternshipEngagements can only be created on InternshipProjects
=> 647 - Check project type that matches with engagement type

src/common/validators/iana-timezone.validator.ts, src/common/validators/index.ts, src/components/user/dto/create-person.dto.ts, src/components/user/dto/update-user.dto.ts
https://github.com/SeedCompany/cord-api-v3/issues/665
=> Issue - 665: Add user timezone validation decorator

src/components/partnership/partnership.service.ts
https://github.com/SeedCompany/cord-api-v3/issues/670
https://github.com/SeedCompany/cord-api-v3/issues/672
=> Issue - 670, 672: Cannot return null for canRead,canEdit fields of mou and agreement

src/components/project/project.service.ts, src/components/user/user.service.ts
Fixes :  https://github.com/SeedCompany/cord-api-v3/issues/674
=> Fixes - 674: Project permission bug

src/core/database/errors.ts
Previously these errors were not shown in console at all.
=> Catch, map, and log neo4j syntax errors

src/components/location/location.service.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/695
=> Issue: 695 - Fix location list filter mandatory

src/components/partnership/partnership.service.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/694
=> Issue - 694: Fix Partnership list filter issue

src/core/database/database.service.ts, test/favorite.e2e-spec.ts, test/film.e2e-spec.ts, test/literacy.e2e-spec.ts, test/story.e2e-spec.ts, test/user.e2e-spec.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/655
Refactored `database.service` list function to make working `WHERE` clause
=> Issue: 655 - User status value is returned null

test/organization.e2e-spec.ts
#748 seems to work consistently. 
these two tests prove
=> sort order test

src/components/engagement/engagement.service.ts, src/components/organization/organization.service.ts, src/core/database/query.helpers.ts, test/organization.e2e-spec.ts
long lived branch to hold a bunch of refactors.
=> Query refactor2

src/core/database/query.helpers.ts
=> the function `filterByString` in `query.helper.ts` can accept a case insensitive

src/components/user/user.service.ts, src/core/database/query.helpers.ts, test/user.e2e-spec.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/677
=> Refactor user service list and readone

src/components/engagement/dto/engagement.dto.ts, src/components/engagement/engagement.service.ts
merges read intern and lang engagements into one query and removes the need to call the extra read one query.
=> merged read lang and intern into one query

src/components/product/product.service.ts, src/core/database/query.helpers.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/716
=> Issue: 716 - Refactor product service list and readone

src/components/authentication/authentication.dto.ts, src/components/authentication/authentication.resolver.ts, src/components/authentication/authentication.service.ts
Implementation can be done by someone else.
=> Change Password API

src/common/types.ts, src/components/product/dto/create-product.dto.ts, src/components/product/dto/update-product.dto.ts
Also trying out NestJS' [mapped types](https://docs.nestjs.com/graphql/mapped-types) for `UpdateProduct`
=> Allow scripture to be set when creating products

src/components/project/project-member/project-member.service.ts, src/core/database/query.helpers.ts
Fixes - https://github.com/SeedCompany/cord-api-v3/issues/676
=> Refactor project member readone, list

src/components/product/product.service.ts, src/core/database/query.helpers.ts
Fixes - https://github.com/SeedCompany/cord-api-v3/pull/725 comments
@michaelmarshall Current `filter` query function cannot handle multi-filtering now. https://github.com/SeedCompany/cord-api-v3/pull/725/files/8767cbf9aa75900867dfe9f361e19f1668b8184b#r457577819
=> Chore: refactor product service

src/components/partnership/partnership.service.ts
Fixes - https://github.com/SeedCompany/cord-api-v3/issues/678
=> Refactor partnership readone, list

src/components/organization/organization.service.ts, test/user.e2e-spec.ts
Fixes - https://github.com/SeedCompany/cord-api-v3/issues/796
=> Refactor/Implement read/list a user's orgs

src/components/search/search.module.ts, src/components/search/search.service.ts, src/core/database/query.helpers.ts
Global search: https://github.com/SeedCompany/cord-api-v3/issues/392
=> Issue 392: Global Search

src/components/language/ethnologue-language/ethnologue-language.service.ts, src/components/language/language.service.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/814 https://github.com/SeedCompany/cord-api-v3/issues/816
=> Refactor language readone, list

src/components/project/project.service.ts
=> added label on project to specify type

src/components/engagement/engagement.service.ts, src/components/product/product.service.ts, test/product.e2e-spec.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/738
=> Refactor create product with engagement, add e2e test case

src/components/location/location.service.ts
Fixes - https://github.com/SeedCompany/cord-api-v3/issues/821
=> Refactor location.service readone and list

src/components/literacy-material/literacy-material.service.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/834
=> Refactor LiteracyMaterial create, readone, list

src/components/engagement/engagement.service.ts, test/engagement.e2e-spec.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/844
=> Fix engagement duplication

src/components/project/project-member/project-member.service.ts, test/budget.e2e-spec.ts, test/project-member.e2e-spec.ts, test/project.e2e-spec.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/842
=> Fix ProjectMember duplication

src/components/engagement/engagement.service.ts, src/components/song/song.service.ts, test/song.e2e-spec.ts, test/utility/create-song.ts, test/utility/fragments.ts, test/utility/index.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/848
=> Refactor SongService create, readone, list, update and delete

src/components/authentication/authentication.service.ts, test/authentication.e2e-spec.ts, test/project.e2e-spec.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/852
=> Issue: 852 - Add changing password feature and test case

src/components/product/product.service.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/870
=> Refactor product list filter by approach

src/common/name-field.ts, src/components/location/dto/location.dto.ts, src/components/user/dto/create-person.dto.ts, src/components/user/dto/update-user.dto.ts, src/components/user/dto/user.dto.ts, src/components/user/user.service.spec.ts, src/components/user/user.service.ts, test/utility/register.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/873
=> Add roles to UserService

src/components/search/dto/search-results.dto.ts, src/components/search/search.module.ts, src/components/search/search.service.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/885
=> Add producible search

src/components/location/dto/location.dto.ts, src/components/user/user.service.ts
We need to discuss more how to delete the user `roles` while updating `user`
=> Refactor user.service roles

src/components/engagement/engagement.service.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/883
=> Add unauthorized message while creating engagement

src/components/language/ethnologue-language/ethnologue-language.service.ts, src/components/language/language.service.ts, src/core/database/query.helpers.ts
=> Refacotr languages query to decrease response time

src/components/partnership/partnership.service.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/898
=> Fix update partnership permission error

src/components/file/file.repository.ts, src/components/file/file.service.ts
=> Fix some file queries

src/components/engagement/engagement.service.ts, src/components/project/project.service.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/917
=> Throw duplication exception while creating with same project name

src/components/engagement/engagement.service.ts, src/components/product/product.module.ts, src/components/product/product.service.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/923
=> Fix derivative product query

src/components/engagement/engagement.service.ts, src/components/project/project.service.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/900
=> Filter projects by type

src/core/database/query.helpers.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/931
=> Fix querying error empty languages

src/common/secured-property.ts, src/components/engagement/dto/intern-position.enum.ts, src/components/partnership/dto/partnership.dto.ts, src/components/product/dto/product-methodology.ts, src/components/project/dto/step.enum.ts, src/components/user/dto/user.dto.ts, src/components/user/education/dto/education.dto.ts
Same as #959 but for single values
=> Refactor SecuredEnum out of SecuredProperty to fix types

src/components/user/dto/create-person.dto.ts, src/components/user/dto/update-user.dto.ts, src/components/user/dto/user.dto.ts, src/components/user/user.service.spec.ts, src/components/user/user.service.ts, test/utility/register.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/939
=> Add new title field to User

src/components/partnership/dto/create-partnership.dto.ts, src/components/partnership/dto/index.ts, src/components/partnership/dto/partnership-funding-type.enum.ts, src/components/partnership/dto/partnership.dto.ts, src/components/partnership/dto/update-partnership.dto.ts, src/components/partnership/partnership.service.ts, src/core/database/database.service.ts, test/budget.e2e-spec.ts, test/partnership.e2e-spec.ts, test/utility/create-partnership.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/938
=> Add funding type to partnership

src/components/language/language.service.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/978
=> Refactor language readOne (set property value to null if canRead is false)

src/components/partnership/dto/create-partnership.dto.ts, src/components/partnership/partnership.service.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/889
=> Fix budget records array empty

src/components/organization/organization.service.ts
refactor just as languages readone
=> Refactor org readOne with strict typing

src/components/project/project-member/project-member.service.ts, src/core/database/database.service.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/979
=> Check permission before updating language

src/components/project/project.service.ts
1. needs finishing off and quality checks.
2. needs to be abstracted for other services.
=> first draft of new list strategy

src/core/database/results/types.ts
Instead of omitting these props we just change their value to `unknown`.
This allows them to be used in permissions, but still requires their values to be handled explicitly some other way.
For example:
```ts
export class ProjectMember extends Resource {
user: SecuredUser
roles: SecuredRoles
modifiedAt: DateTime
}
// Previously DbPropsOfDto<ProjectMember> would be this:
type ProjectMemberDbProps = {
roles: Role[]
modifiedAt: DateTime
}
// Now it's:
type ProjectMemberDbProps = {
user: unknown
roles: Role[]
modifiedAt: DateTime
}
```
=> DbPropsOfDto - Allow props that are not native DB values as unknown

src/common/secured-property.ts
=> Fix SecuredDateNullable value type

src/components/story/story.service.ts
https://github.com/SeedCompany/cord-api-v3/issues/1019
=> feat:refactor story readOne

src/components/project/project-member/project-member.service.ts
https://github.com/SeedCompany/cord-api-v3/issues/1023
=> feat:refactor project-member readOne

src/components/budget/handlers/index.ts, src/components/budget/handlers/sync-budget-records-to-funding-partners.handler.ts, src/components/budget/handlers/update-project-current-budget-status.handler.ts, src/components/project/events/project-updated.event.ts, src/components/project/project.service.ts, test/project.e2e-spec.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1041
=> Move updating budget status to budget event handler

src/components/authentication/authentication.resolver.ts, src/components/authentication/authentication.service.ts, src/components/budget/budget.service.ts, src/components/ceremony/ceremony.service.ts, src/components/engagement/engagement.service.ts, src/components/file/file.service.ts, src/components/film/film.service.ts, src/components/literacy-material/literacy-material.service.ts, src/components/location/location.service.ts, src/components/partnership/partnership.service.ts, src/components/product/product.service.ts, src/components/project/project-member/project-member.service.ts, src/components/project/project.service.ts, src/components/song/song.service.ts, src/components/story/story.service.ts, src/components/user/education/education.service.ts, src/components/user/unavailability/unavailability.service.ts, src/components/user/user.service.ts, src/core/config/environment.service.ts, src/core/database/database.service.ts, src/core/database/indexer/indexer.module.ts, src/core/database/query.helpers.ts, src/core/email/email.service.ts, src/core/logger/logger.interface.ts, src/core/logger/nest-logger-adapter.service.ts
=> changed logger.info to logger.debug

src/common/firstLettersOfWords.test.ts, src/common/firstLettersOfWords.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/789
=> Fix avatar letters lowercase issue

src/components/project/project.service.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/947
=> Throw unauthenticated exception if user not logged in while creating project

test/partnership.e2e-spec.ts, test/project.e2e-spec.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1032
=> Fix partnership mou dates and add more test cases

src/components/language/ethnologue-language/ethnologue-language.service.ts, test/language.e2e-spec.ts, test/utility/create-language.ts
=> Fix updating ethnologue language

test/engagement.e2e-spec.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1050
=> Add test cases to engagement

src/components/engagement/engagement.service.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1095
=> Refactor engagement list

src/components/partnership/partnership.service.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1102
=> Create partnership with unique types

src/components/song/dto/update-song.dto.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1103
=> Validation error updating song with invalid id

src/components/language/language.service.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1086
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1090
=> Refactor language list

src/components/partnership/partnership.service.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1106
=> Refactor partnership list with new abstraction

src/components/language/language.service.ts
Fixes https://github.com/SeedCompany/cord-api-v3/issues/816
=> fix:language sort with ASC/DESC order

src/components/engagement/engagement.service.ts, test/engagement.e2e-spec.ts, test/utility/fragments.ts
https://github.com/SeedCompany/cord-api-v3/issues/1072
=> 1072 add test ceremony

src/common/util.ts, src/components/user/user.service.ts, test/user.e2e-spec.ts
Copied from project list refactor.  Skipped the first/last name filters as Carson said we don't need them.  Was in the process of making `applyListFilters` to abstract the users but will keep the code in, maybe used later.
=> User list refactor

src/components/budget/budget.service.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/837
Use new `Project.list` pattern
=> Refactor budget lists

src/components/film/film.module.ts, src/components/film/film.service.ts, src/components/literacy-material/literacy-material.module.ts, src/components/literacy-material/literacy-material.service.ts, src/components/scripture/scripture-reference.service.ts, src/components/scripture/scripture.module.ts, src/components/song/song.module.ts, src/components/song/song.service.ts, src/components/story/story.module.ts, src/components/story/story.service.ts
re-refactor readones for Story, Song, Literacy-material and Film.
update create and update function for Song.
=> re-refactor readOnes and update create and update for song

src/core/validation.pipe.ts
Bug introduced with #1117 
Sometimes ValidationErrors don't have any constraint violations but they have children that do. These were not being handled.
Now we flatten the list down and ignore parents that don't have their own constraint violations.
Since we are using the target name to identify the nested object there's no need to prefix the parent.
This is inverse to what is exposed to the API which identifies by a nested path structure.
This was also missed because the shape of nestjs' ValidationError
doesn't have nullability correct. Switch to the interface from class-validator produced the error correctly.
=> Fix ValidationException handling of nested constraint violations

src/components/partnership/partnership.service.ts
https://github.com/SeedCompany/cord-api-v3/issues/1129
=> feat: default agreementStatus and mouStatus for Partnership

src/components/location/location.service.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1141
=> Refactor location list with new abstractions

src/components/file/file.service.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1113
Need to fix `file.e2e` failings
=> Add file migration logic to file service

src/components/project/dto/project.dto.ts, src/components/project/project.resolver.ts, src/components/project/project.service.ts, test/project.e2e-spec.ts, test/utility/fragments.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1144
=> Rename deptId to departmentId

src/components/scripture/dto/scripture-range.dto.ts, src/components/scripture/dto/scripture-range.validator.ts, src/components/scripture/reference.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1150
=> Add decorator to ensure start and end order

src/core/database/query/lists.ts
Fix https://github.com/SeedCompany/cord-api-v3/issues/1156
=> Fix: duplicates in query results

src/components/file/dto/node.ts, src/components/project/project.resolver.ts, src/components/project/project.service.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1059
=> Handle no permission for project root directory

src/components/scripture/scripture-range.resolver.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1134
=> Calculate total verse in scriptureReferences

src/components/language/dto/language.dto.ts, src/components/language/language.resolver.ts, src/components/language/language.service.ts, test/utility/fragments.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1161
=> Change sponsor date to sponsor start date

src/components/language/dto/create-language.dto.ts, src/components/language/dto/language.dto.ts, src/components/language/dto/update-language.dto.ts, src/components/language/language.service.ts, test/language.e2e-spec.ts, test/utility/create-language.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1167
=> Add signLanguageCode to language

src/components/budget/budget.service.ts, src/components/engagement/engagement.service.ts, src/components/language/ethnologue-language/ethnologue-language.service.ts, src/components/language/language.service.ts, src/components/organization/organization.service.ts, src/components/project/project.service.ts, src/core/database/query/matching.ts
=> removed variable length queries

src/components/language/dto/create-language.dto.ts, src/components/language/dto/language.dto.ts, src/components/language/dto/update-language.dto.ts, src/components/language/ethnologue-language/ethnologue-language.service.ts, test/utility/create-language.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1166
=> Remove id from enthnologue language

src/components/ceremony/ceremony.module.ts, src/components/ceremony/handlers/create-engagement-default-ceremony.handler.ts, src/components/ceremony/handlers/delete-engagement-default-ceremony.handler.ts, src/components/ceremony/handlers/index.ts, src/components/engagement/engagement.service.ts, src/components/engagement/events/engagement-created.event.ts, src/components/engagement/events/engagement-deleted.event.ts, src/components/engagement/events/engagement-updated.event.ts, src/components/engagement/events/index.ts, test/engagement.e2e-spec.ts
=> Engagements events. Ceremony refactoring.

src/components/language/dto/create-language.dto.ts, src/components/language/dto/language.dto.ts, src/components/language/dto/update-language.dto.ts, src/components/language/language.service.ts
=> 1158 language.isSignLanguage

src/components/budget/budget.module.ts, src/components/budget/budget.resolver.ts, src/components/budget/budget.service.ts, src/components/budget/dto/budget.dto.ts, src/components/budget/dto/create-budget.dto.ts, src/components/budget/dto/update-budget.dto.ts
=> Budget universalTemplateFile field

test/user.e2e-spec.ts
Test was previously asserting based on incorrect assumptions
=> Fix test for User.avatarLetters

src/components/language/dto/create-language.dto.ts, src/components/language/dto/update-language.dto.ts, src/components/language/language.service.ts
=> Change Language.sensitivity to be set by user instead of being calculated

src/components/product/product.service.ts, test/product.e2e-spec.ts
Can be merged after merging https://github.com/SeedCompany/cord-api-v3/pull/1096
=> add test for product with scriptureRefOverride which is null

src/components/partnership/dto/create-partnership.dto.ts, src/components/partnership/dto/financial-reporting-type.ts, src/components/partnership/dto/index.ts, src/components/partnership/dto/partnership-funding-type.enum.ts, src/components/partnership/dto/partnership.dto.ts, src/components/partnership/dto/update-partnership.dto.ts, src/components/partnership/partnership.service.ts, test/budget.e2e-spec.ts, test/utility/create-partnership.ts
Closes #1162 (on the API side)
- Update all instances of `PartnershipFundingType` to `FinancialReportingType`
- Change `fundingType` property of `Partnership` to `financialReportingType`
=> Change `PartnershipFundingType` to `FinancialReportingType`

src/components/language/dto/create-language.dto.ts, src/components/language/dto/language.dto.ts, src/components/language/dto/update-language.dto.ts, src/components/language/language.service.ts, test/utility/create-language.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1165
=> Add sponsor estimated date to language

src/app.module.ts, src/components/partner/dto/create-partner.dto.ts, src/components/partner/dto/index.ts, src/components/partner/dto/list-partner.dto.ts, src/components/partner/dto/partner.ts, src/components/partner/dto/update-partner.dto.ts, src/components/partner/index.ts, src/components/partner/partner.module.ts, src/components/partner/partner.resolver.ts, src/components/partner/partner.service.ts, src/components/user/user.service.ts, test/partner.e2e-spec.ts, test/utility/create-partner.ts, test/utility/fragments.ts, test/utility/index.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1194
=> Add Partner module

src/components/budget/dto/update-budget.dto.ts, test/budget.e2e-spec.ts
=> Make `status` property of `UpdateBudget` class private

src/core/graphql.config.ts
Checking for messages as seen in #1208 and from searching around
=> Catch more schema query validation errors as client errors

src/components/partner/dto/create-partner.dto.ts, src/components/partner/dto/partner.ts, src/components/partner/dto/update-partner.dto.ts, src/components/partner/partner.module.ts, src/components/partner/partner.resolver.ts, src/components/partner/partner.service.ts, test/partner.e2e-spec.ts, test/utility/create-partner.ts, test/utility/fragments.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1164
=> Add nullable pointOfContact to Partner module

src/components/file/file.repository.ts, src/core/database/database.service.ts, src/core/database/query.helpers.ts
Refactor the 3 file creates with the new Create pattern, then remove the db.createNode and its helpers
=> Remove old acl create node refactor file service

test/project.e2e-spec.ts
https://github.com/SeedCompany/cord-api-v3/issues/971
https://github.com/SeedCompany/cord-api-v3/issues/972
=> fix:list view of project members by projectId test

test/organization.e2e-spec.ts
=> add test into organization

src/components/project/project.service.ts
=> Fix permissions on Project.engagements query

src/common/sensitivity.enum.ts, src/components/project/dto/create-project.dto.ts, src/components/project/dto/update-project.dto.ts, src/components/project/project.service.ts, test/project.e2e-spec.ts
Translation project sensitivity is calculated on read, internship allowed to be set by user
=> Set project sensitivity

src/components/authentication/authentication.service.ts, src/core/config/config.service.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1217
=> Add secret to password hashing

src/components/project/project.service.ts
removed active property and added project id to engagements query
=> Bug in Project.listEngagements query

src/components/engagement/dto/update-engagement.dto.ts, src/components/engagement/engagement.module.ts, src/components/engagement/engagement.service.ts, src/components/engagement/events/engagement-created.event.ts, src/components/engagement/events/engagement-updated.event.ts, src/components/engagement/handlers/index.ts, src/components/engagement/handlers/set-initial-end-date.handler.ts
Added events for engagements being created or updated.
Updated engagement creation and update methods on engagement service to allow for updating initialEndDate.
Added event handler which sets initial end date.
=> added handler to set initial end date

src/components/project/index.ts, src/components/project/project.service.ts, src/components/project/query.helpers.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/643
=> Project filters

src/components/project/query.helpers.ts, src/components/user/unavailability/unavailability.service.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1230
=> Refactor unavailability readone

test/budget.e2e-spec.ts, test/engagement.e2e-spec.ts, test/language.e2e-spec.ts, test/organization.e2e-spec.ts, test/partnership.e2e-spec.ts, test/project-member.e2e-spec.ts, test/project.e2e-spec.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1216
=> E2E tests - Unchecked errors

src/components/project/project.service.ts, src/core/database/query.helpers.ts, test/project.e2e-spec.ts, test/utility/fragments.ts
remove the old permission method in the project service that was creating disconnected SG nodes.
remove creating `writerSG` and `readerSG` nodes for all services.
=> Own project cannot create engagement

src/components/scripture/dto/scripture-reference.dto.ts, src/components/scripture/scripture-reference.resolver.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1202, https://github.com/SeedCompany/cord-api-v3/issues/1220
=> Remove book code

src/components/budget/budget.service.ts, src/components/ceremony/ceremony.service.ts, src/components/engagement/engagement.service.ts, src/components/film/film.service.ts, src/components/language/ethnologue-language/ethnologue-language.service.ts, src/components/language/language.service.ts, src/components/literacy-material/literacy-material.service.ts, src/components/location/location.service.ts, src/components/partner/partner.service.ts, src/components/partnership/partnership.service.ts, src/components/product/product.service.ts, src/components/project/project-member/project-member.service.ts, src/components/project/project.service.ts, src/components/song/song.service.ts, src/components/story/story.service.ts, src/components/user/user.service.ts, src/core/database/database.service.ts, src/core/database/query.helpers.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1197
=> Remove duplicated query helpers

src/components/authorization/policies/policies.ts
Add sensitivity perms on Project Policies
=> Update project sensitivity

src/components/authorization/dto/powers.ts, src/components/user/user.service.ts
prepping for the test refactor. added default powers to all users. need Seth to tweak.
=> added base powers to all users. added GrantPower to root.

src/components/authorization/policies/policies.ts, src/components/location/dto/location.dto.ts, src/components/location/location.service.ts, src/components/search/dto/search-results.dto.ts, src/components/search/search.module.ts, src/components/search/search.service.ts, test/utility/fragments.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1295
=> Location Refactor Clean Up

src/components/authorization/policies/policies.ts, src/components/language/dto/create-language.dto.ts, src/components/language/dto/language.dto.ts, src/components/language/dto/update-language.dto.ts, src/components/language/language.service.ts, test/language.e2e-spec.ts, test/utility/fragments.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1275
=> Add new hasExternalFirstScripture to language and business logic

src/components/authorization/policies/policies.ts, src/components/budget/handlers/sync-budget-records-to-funding-partners.handler.ts, src/components/partnership/dto/create-partnership.dto.ts, src/components/partnership/dto/partnership.dto.ts, src/components/partnership/partnership.module.ts, src/components/partnership/partnership.resolver.ts, src/components/partnership/partnership.service.spec.ts, src/components/partnership/partnership.service.ts, src/components/project/project.module.ts, src/components/project/project.service.ts, test/partnership.e2e-spec.ts, test/project.e2e-spec.ts, test/utility/create-partnership.ts, test/utility/fragments.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1196
=> Update partnership to have partner relation

src/components/engagement/engagement.service.ts, test/engagement.e2e-spec.ts, test/utility/create-engagement.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1276
=> Verify engagement first scripture on create/update

src/components/authorization/roles/internal-admin.role.db.ts, src/components/partner/dto/create-partner.dto.ts, src/components/partner/dto/partner.dto.ts, src/components/partner/dto/update-partner.dto.ts, src/components/partner/model/partner.model.db.ts, src/components/partner/partner.service.ts, src/components/partnership/partnership.service.ts, test/partner.e2e-spec.ts, test/partnership.e2e-spec.ts, test/utility/create-partner.ts, test/utility/fragments.ts, test/utility/index.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/982
=> Add new fields to partner module

src/components/user/education/education.service.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1255
=> Refactor education module

test/engagement.e2e-spec.ts
Fixing a missing import in the test, not sure how this slipped through the first time.
Eslint has been acting weird for me lately on the test files, anyone else?
=> fix(engagement.e2e-spec.ts): fix import

src/components/authorization/authorization.resolver.ts, src/components/authorization/authorization.service.ts, test/utility/grant-power.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1336
=> Rename mutation grantPower/removePower arg id to userId

src/components/project/project.service.ts, test/project.e2e-spec.ts
Used to sort by the sensitivity words alphabetically.  Now use CASE to map it to a numerical value to be sorted
=> Sort project sensitivity

src/components/budget/handlers/sync-budget-records-to-funding-partners.handler.ts, src/components/partnership/events/partnership-deleted.event.ts, src/components/partnership/partnership.service.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1259
=> Fix delete partnership bug related budget records

src/components/authorization/roles/administrator.role.ts, src/components/authorization/roles/consultant-manager.role.ts, src/components/authorization/roles/controller.role.ts, src/components/authorization/roles/field-operations-director.role.ts, src/components/authorization/roles/financial-analyst.role.ts, src/components/authorization/roles/project-manager.role.ts, src/components/authorization/roles/read-all.role.ts, src/components/authorization/roles/regional-director.role.ts, src/components/engagement/handlers/index.ts, src/components/engagement/handlers/update-project-status.handler.ts, src/components/engagement/model/engagement.model.db.ts, test/engagement.e2e-spec.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1142
=> Update engagement status to active

src/components/engagement/engagement.service.ts, src/components/engagement/handlers/index.ts, src/components/engagement/handlers/set-last-status-date.handler.ts, test/engagement.e2e-spec.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1143
Wait until https://github.com/SeedCompany/cord-api-v3/pull/1334 is merged
=> Engagement last status date reactions

src/components/authorization/dto/powers.ts, src/components/project/project.service.ts, src/components/user/user.service.ts, test/project.e2e-spec.ts
Testing the new delete refactor on proejct
=> fix(project.service.ts): use new delete

src/components/authorization/authorization.service.ts
refactored a query that was taking forever to use apoc.
rushing this to get beta sort of working. will clean up later.
=> refactored query to use apoc

src/components/partnership/partnership.service.ts, test/partnership.e2e-spec.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1349
=> Partnerships should have unique partners/organziations per project

src/components/authorization/roles/administrator.role.ts, src/components/authorization/roles/consultant-manager.role.ts, src/components/authorization/roles/controller.role.ts, src/components/authorization/roles/field-operations-director.role.ts, src/components/authorization/roles/financial-analyst.role.ts, src/components/authorization/roles/intern.role.ts, src/components/authorization/roles/project-manager.role.ts, src/components/authorization/roles/regional-director.role.ts, src/components/organization/dto/create-organization.dto.ts, src/components/organization/dto/organization.ts, src/components/organization/dto/update-organization.dto.ts, src/components/organization/model/organization.model.db.ts, src/components/organization/organization.service.ts, test/organization.e2e-spec.ts, test/utility/create-organization.ts, test/utility/fragments.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1354
=> Add address field to organization

src/components/authorization/roles/administrator.role.ts, src/components/authorization/roles/consultant-manager.role.ts, src/components/authorization/roles/consultant.role.ts, src/components/authorization/roles/controller.role.ts, src/components/authorization/roles/field-operations-director.role.ts, src/components/authorization/roles/financial-analyst.role.ts, src/components/authorization/roles/fundraising.role.ts, src/components/authorization/roles/intern.role.ts, src/components/authorization/roles/leadership.role.ts, src/components/authorization/roles/liason.role.ts, src/components/authorization/roles/marketing.role.ts, src/components/authorization/roles/mentor.role.ts, src/components/authorization/roles/project-manager.role.ts, src/components/authorization/roles/regional-communications-coordinator.role.ts, src/components/authorization/roles/regional-director.role.ts, src/components/authorization/roles/staff-member.role.ts, src/components/authorization/roles/translator.role.ts, src/components/partner/dto/partner.dto.ts, src/components/partner/model/partner.model.db.ts, src/components/partner/partner.service.ts, test/partner.e2e-spec.ts, test/utility/fragments.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1348
@michaelmarshall can you add `modifiedAt` to partner in the schema doc?
=> Add modifiedAt to partner

.github/workflows/ci.yml
=> Fix env key for APOC on CI

src/components/user/dto/assign-organization-to-user.dto.ts, src/components/user/dto/remove-organization-from-user.dto.ts, src/components/user/user.resolver.ts, src/components/user/user.service.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1383
=> Add validate nested and type decorator to assignOrganizationToUser

.lintstagedrc
=> Lint test files on commit

.github/workflows/ci.yml, src/components/organization/organization.service.ts, src/components/project/project.service.ts, src/core/database/database.service.ts, src/core/database/indexer/indexer.module.ts
Support both Neo4j 3.x and 4.x to make the transition easy.
Supersedes #1391
=> Neo4j v4 Compat

test/budget.e2e-spec.ts
https://github.com/SeedCompany/cord-api-v3/issues/1040
=> add test case in budget

src/components/project/project.service.ts
=> wip: adding primaryLocation to project udpate

src/components/authorization/authorization.service.ts
quick update for the global role add query.
=> updated iterate function when adding users with global roles to SGs

src/components/product/dto/create-product.dto.ts, src/components/product/product.service.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1351
=> Remove duplicated mediums and purposes in Product

src/components/authorization/authorization.service.ts, test/partnership.e2e-spec.ts
We used to give the creator admin privileges on all basenodes they create, regardless of the user's role.  So a ProjectMember can create a partnership and has edit access on all the fields.  Now check that the baseNode is a certain kind (e.g. not a Partnership) before giving admin SGs.
=> Only give creator admin privileges on certain basenodes

src/common/resource.dto.ts, src/components/budget/budget.service.ts, src/components/ceremony/ceremony.service.ts, src/components/engagement/engagement.service.ts, src/components/field-region/field-region.service.ts, src/components/field-zone/field-zone.service.ts, src/components/file/file.repository.ts, src/components/film/film.service.ts, src/components/funding-account/funding-account.service.ts, src/components/language/language.service.ts, src/components/literacy-material/literacy-material.service.ts, src/components/location/location.service.ts, src/components/organization/organization.service.ts, src/components/partner/partner.service.ts, src/components/partnership/partnership.service.ts, src/components/product/product.service.ts, src/components/project/project-member/project-member.service.ts, src/components/project/project.service.ts, src/components/song/song.service.ts, src/components/story/story.service.ts, src/components/user/education/education.service.ts, src/components/user/unavailability/unavailability.service.ts, src/components/user/user.service.ts
Closes #1274
Implements the changes discussed in #1341
=> Add canDelete to Resource

src/components/authentication/authentication.dto.ts, src/components/user/dto/check-email.dto.ts, src/components/user/dto/create-person.dto.ts, test/authentication.e2e-spec.ts, test/user.e2e-spec.ts, test/utility/create-person.ts, test/utility/register.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1414
=> Fix email is case sensitive

src/components/language/language.resolver.ts, src/components/language/language.service.ts, src/components/location/location.service.ts, src/components/organization/organization.service.ts, src/components/project/project.service.ts, src/components/user/user.service.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1347
=> Refactor add/remove/list locations in several services

src/components/project/events/project-updated.event.ts, src/components/project/handlers/index.ts, src/components/project/handlers/set-department-id.handler.ts, src/components/project/project.service.ts, src/core/events/event-bus.service.ts, test/engagement.e2e-spec.ts, test/project.e2e-spec.ts
Added handler to calculate and set project departmentId when project step is updated to Pending Finance Confirmation.
=> 612 calculate department id

src/components/authorization/roles/administrator.role.ts, src/components/authorization/roles/consultant-manager.role.ts, src/components/authorization/roles/consultant.role.ts, src/components/authorization/roles/controller.role.ts, src/components/authorization/roles/field-operations-director.role.ts, src/components/authorization/roles/financial-analyst.role.ts, src/components/authorization/roles/fundraising.role.ts, src/components/authorization/roles/intern.role.ts, src/components/authorization/roles/leadership.role.ts, src/components/authorization/roles/liason.role.ts, src/components/authorization/roles/marketing.role.ts, src/components/authorization/roles/mentor.role.ts, src/components/authorization/roles/project-manager.role.ts, src/components/authorization/roles/regional-communications-coordinator.role.ts, src/components/authorization/roles/regional-director.role.ts, src/components/authorization/roles/staff-member.role.ts, src/components/authorization/roles/translator.role.ts, src/components/project/dto/project.dto.ts, src/components/project/dto/update-project.dto.ts, src/components/project/events/project-created.event.ts, src/components/project/handlers/index.ts, src/components/project/handlers/set-initial-mou-end.handler.ts, src/components/project/model/project.model.db.ts, src/components/project/project.service.ts, test/project.e2e-spec.ts, test/utility/fragments.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1439
=> Add initialMouEnd handler to project

src/components/authorization/roles/administrator.role.ts, src/components/authorization/roles/consultant-manager.role.ts, src/components/authorization/roles/consultant.role.ts, src/components/authorization/roles/controller.role.ts, src/components/authorization/roles/field-operations-director.role.ts, src/components/authorization/roles/financial-analyst.role.ts, src/components/authorization/roles/fundraising.role.ts, src/components/authorization/roles/intern.role.ts, src/components/authorization/roles/leadership.role.ts, src/components/authorization/roles/liason.role.ts, src/components/authorization/roles/marketing.role.ts, src/components/authorization/roles/mentor.role.ts, src/components/authorization/roles/project-manager.role.ts, src/components/authorization/roles/regional-communications-coordinator.role.ts, src/components/authorization/roles/regional-director.role.ts, src/components/authorization/roles/staff-member.role.ts, src/components/authorization/roles/translator.role.ts, src/components/project/dto/project.dto.ts, src/components/project/handlers/index.ts, src/components/project/handlers/set-step-changed-at.handler.ts, src/components/project/model/project.model.db.ts, src/components/project/project.service.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1437
@michaelmarshall can you update the project schema with this new field?
=> Add stepChangedAt field/handler to project

src/components/project/dto/project.dto.ts, src/components/project/project.module.ts, src/components/project/project.resolver.ts, src/components/project/project.service.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1438
=> Expose owningOrganization to project

.github/workflows/ci.yml, docker-compose.yml, src/components/admin/admin.module.ts, src/components/admin/admin.resolver.ts, src/components/admin/admin.service.ts, src/components/authorization/authorization.service.ts, src/components/budget/budget.service.ts, src/components/ceremony/ceremony.service.ts, src/components/ceremony/handlers/create-engagement-default-ceremony.handler.ts, src/components/engagement/engagement.service.ts, src/components/file/file.repository.ts, src/components/file/file.service.ts, src/components/file/handlers/attach-project-root-directory.handler.ts, src/components/film/film.service.ts, src/components/language/language.service.ts, src/components/literacy-material/literacy-material.service.ts, src/components/location/location.service.ts, src/components/partner/partner.service.ts, src/components/partnership/partnership.service.ts, src/components/project/project.service.ts, src/components/song/song.service.ts, src/components/story/story.service.ts, src/components/user/education/education.service.ts, src/components/user/unavailability/unavailability.service.ts, src/components/user/user.service.ts, src/core/config/config.service.ts, test/engagement.e2e-spec.ts, test/project.e2e-spec.ts, test/user.e2e-spec.ts, test/utility/register.ts
=> Procedures

src/common/pagination-list.ts, src/common/secured-list.ts, src/components/user/user.service.ts
=> Return redacted User.unavailabilities instead of throwing

src/components/partner/dto/list-partner.dto.ts, src/components/partner/partner.module.ts, src/components/partner/partner.resolver.ts, src/components/partner/partner.service.ts, src/components/user/user.module.ts, src/components/user/user.resolver.ts, src/components/user/user.service.ts
Searches the user's partners (if the user has an org assigned from `assignOrganizationToUser` and if that org has a partner)
@michaelmarshall add the new field to the db proc.
=> 1436 user partners

src/components/project/project.service.ts, test/project.e2e-spec.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1342
=> Fix mine filter in list projects

src/components/engagement/engagement.service.ts, test/engagement.e2e-spec.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1401
=> Add verify project status while create/delete engagements

src/components/project/project.rules.ts
=> bug fix: needed to collect query results

src/components/authorization/roles/administrator.role.ts, src/components/authorization/roles/consultant-manager.role.ts, src/components/authorization/roles/consultant.role.ts, src/components/authorization/roles/controller.role.ts, src/components/authorization/roles/field-operations-director.role.ts, src/components/authorization/roles/financial-analyst.role.ts, src/components/authorization/roles/fundraising.role.ts, src/components/authorization/roles/intern.role.ts, src/components/authorization/roles/leadership.role.ts, src/components/authorization/roles/liason.role.ts, src/components/authorization/roles/marketing.role.ts, src/components/authorization/roles/mentor.role.ts, src/components/authorization/roles/project-manager.role.ts, src/components/authorization/roles/regional-communications-coordinator.role.ts, src/components/authorization/roles/regional-director.role.ts, src/components/authorization/roles/staff-member.role.ts, src/components/authorization/roles/translator.role.ts, src/components/project/dto/create-project.dto.ts, src/components/project/dto/project.dto.ts, src/components/project/dto/update-project.dto.ts, src/components/project/model/project.model.db.ts, src/components/project/project.service.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1490
=> Add financialReportReceivedAt to project

src/components/admin/admin.service.ts, src/components/project/project.service.ts, test/project.e2e-spec.ts
I reverted due to ignorance. It'll happen again.
=> 1342 revert reversion my projects

test/project.e2e-spec.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1509
=> Unskip project e2e

test/product.e2e-spec.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1503
=> Unskip product e2e

test/project-workflow.e2e-spec.ts, test/utility/fragments.ts, test/utility/index.ts, test/utility/update-project.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1385
=> Project workflow test

test/project-member.e2e-spec.ts, test/utility/fragments.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1505
=> Unskip project memeber e2e

test/partnership.e2e-spec.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1492
=> Unskip partnership test

test/language.e2e-spec.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1483
=> Unskip language e2e

src/components/field-zone/field-zone.service.ts, test/engagement.e2e-spec.ts, test/partnership.e2e-spec.ts, test/zone.e2e-spec.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1469
=> Unskip engagement.e2e

src/components/language/language.service.ts
Same as project sensitivity sort
=> Language list correctly sort sensitivity

src/components/engagement/engagement.service.ts, test/engagement.e2e-spec.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1527
=> Set engagement status

src/components/language/dto/list-language.dto.ts, src/components/language/language.service.ts, src/components/language/query.helpers.ts, src/components/project/query.helpers.ts
Branched off of: https://github.com/SeedCompany/cord-api-v3/pull/1513
Filter on sensitivity, leastOfThese, signLanguage, and Dialect
=> Language filters

src/components/funding-account/dto/create-funding-account.dto.ts, src/components/funding-account/dto/update-funding-account.dto.ts, src/components/funding-account/funding-account.service.ts, src/components/project/handlers/set-department-id.handler.ts, test/funding-account.e2e-spec.ts, test/utility/create-funding-account.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1542
=> Fix departmentId length issue

src/components/engagement/dto/create-engagement.dto.ts, src/components/engagement/dto/intern-position.enum.ts, src/components/engagement/dto/update-engagement.dto.ts, src/components/engagement/engagement.module.ts, src/components/engagement/internship-engagement.resolver.ts, src/components/engagement/internship-position.resolver.ts, test/engagement.e2e-spec.ts, test/utility/create-engagement.ts
Part of #1520
This is a breaking API change due to the renames of the position options.
I don't think this is a breaking DB change though.
=> Internship Position, Domain, Program fields

src/components/user/user.service.ts
also covers https://github.com/SeedCompany/cord-api-v3/issues/1563
=> null canCreate be false if user.edit is false #1566

src/components/language/language.service.ts
=> Exclude certain engagement statuses from language sponsor start date

src/components/authorization/roles/administrator.role.ts, src/components/authorization/roles/consultant-manager.role.ts, src/components/authorization/roles/consultant.role.ts, src/components/authorization/roles/controller.role.ts, src/components/authorization/roles/field-operations-director.role.ts, src/components/authorization/roles/financial-analyst.role.ts, src/components/authorization/roles/fundraising.role.ts, src/components/authorization/roles/intern.role.ts, src/components/authorization/roles/leadership.role.ts, src/components/authorization/roles/liason.role.ts, src/components/authorization/roles/marketing.role.ts, src/components/authorization/roles/mentor.role.ts, src/components/authorization/roles/project-manager.role.ts, src/components/authorization/roles/regional-communications-coordinator.role.ts, src/components/authorization/roles/regional-director.role.ts, src/components/authorization/roles/staff-member.role.ts, src/components/authorization/roles/translator.role.ts, src/components/location/dto/create-location.dto.ts, src/components/location/dto/location.dto.ts, src/components/location/dto/update-location.dto.ts, src/components/location/location.service.ts, src/components/location/model/location.model.db.ts, test/utility/create-location.ts, test/utility/fragments.ts
These are no longer connected per @sethmcknight
=> Remove sensitivity from location

src/components/budget/budget.module.ts, src/components/engagement/engagement.module.ts, src/components/language/language.module.ts, src/components/location/dto/create-location.dto.ts, src/components/location/dto/location.dto.ts, src/components/location/dto/update-location.dto.ts, src/components/location/location.module.ts, src/components/location/location.resolver.ts, src/components/location/location.service.ts, src/components/location/model/location.model.db.ts, src/components/project/project.module.ts, src/components/user/user.module.ts, test/location.e2e-spec.ts, test/utility/fragments.ts
=> Add defaultFieldRegion to Location

src/components/budget/dto/create-budget.dto.ts, src/components/budget/dto/update-budget.dto.ts, src/components/engagement/dto/create-engagement.dto.ts, src/components/engagement/dto/update-engagement.dto.ts, src/components/file/file.service.ts, src/components/partnership/dto/create-partnership.dto.ts, src/components/partnership/dto/update-partnership.dto.ts
- Update file name with latest version name
- Fix validation not traversing into the create object
=> Defined files tweaks

src/components/file/file.repository.ts, src/components/file/file.service.ts, src/core/database/database.service.ts
=> Fix file rename to not check security groups which don't exist anymore

src/components/authorization/roles/consultant-on-project.role.ts
=> added read perms to consultant on project budget and budget record.

src/components/engagement/engagement-status.resolver.ts, src/components/engagement/engagement.rules.ts, src/components/project/project-step.resolver.ts, src/components/project/project.rules.ts
=> Bypass workflow

src/core/database/database.service.ts
=> Easier db query strings

src/components/authentication/authentication.service.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1645
=> Remove current session after changing password

src/components/authorization/roles/lead-financial-analyst-global.role.ts
=> fix role name for the lead-financial-analyst-glob

.vscode/launch.json
=> added config for jest vscode extension

src/components/authentication/authentication.resolver.ts, src/components/authentication/authentication.service.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1645
=> Invalidate old tokens after reset password

src/components/project/project.rules.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1668
=> Additional Approvers - Pending Consultant Endorsement

src/components/project/dto/status.enum.ts, test/project-workflow.e2e-spec.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1687
=> New status for Did Not Develop step

src/components/user/dto/create-person.dto.ts, src/components/user/dto/update-user.dto.ts, src/components/user/user.service.ts, test/user.e2e-spec.ts, test/utility/create-person.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1610
=> Create person email field optional

src/components/project/dto/status.enum.ts, src/components/project/dto/step.enum.ts, src/components/project/project.rules.ts, test/project-workflow.e2e-spec.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1696
=> New project step pending change to plan approval

src/components/project/project.service.ts, test/project.e2e-spec.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1704
=> Create/Update Project - Validate other resource ids

src/app.module.ts, src/components/pin/dto/index.ts, src/components/pin/dto/pinnable.dto.ts, src/components/pin/dto/pinned-list.dto.ts, src/components/pin/pin.module.ts, src/components/pin/pin.repository.ts, src/components/pin/pin.resolver.ts, src/components/pin/pin.service.ts, src/components/project/dto/list-projects.dto.ts, src/components/project/dto/project.dto.ts, src/components/project/project.module.ts, src/components/project/project.service.ts, src/components/project/query.helpers.ts, test/pin.e2e-spec.ts, test/project.e2e-spec.ts, test/utility/create-pin.ts, test/utility/fragments.ts, test/utility/index.ts
https://github.com/SeedCompany/cord-api-v3/issues/1721
=> Feature pinning

src/components/budget/budget.service.ts, src/components/budget/handlers/sync-budget-records-to-funding-partners.handler.ts
=> Ensure duplicate budget records cannot be created

src/components/budget/budget.service.ts, src/components/ceremony/ceremony.service.ts, src/components/engagement/engagement.service.ts, src/components/field-region/field-region.service.ts, src/components/field-zone/field-zone.service.ts, src/components/file/file.repository.ts, src/components/film/film.service.ts, src/components/funding-account/funding-account.service.ts, src/components/language/language.service.ts, src/components/literacy-material/literacy-material.service.ts, src/components/location/location.service.ts, src/components/organization/organization.service.ts, src/components/partner/partner.service.ts, src/components/partnership/partnership.service.ts, src/components/product/product.service.ts, src/components/project/project.service.ts, src/components/song/song.service.ts, src/components/story/story.service.ts, src/components/user/user.service.ts, src/core/database/database.service.ts, src/core/database/query.helpers.ts
- Includes base node labels and property labels. 
- I've changed the deletion of properties to just specify base node property relationships, which I believe are the same as 
resource keys. That way you don't have to specify the property node labels.
=> Dynamically set Deleted_ labels and remove original labels on delete

src/core/email/templates/project-step-changed.template.tsx
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1744
=> Add information to the email subject line for Workflow Notifications.

src/components/user/user.service.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1756
=> updateUser mutation doesn't work with empty role array.

src/components/engagement/engagement.service.ts
=> Only allow admins to delete engagements that are not in development

src/components/engagement/engagement.repository.ts, src/components/engagement/engagement.service.ts
Fixes #1772 which has messed up security groups.
Currently this gives more access than expected, because our project managers, globally can read & create products.
https://github.com/SeedCompany/cord-api-v3/blob/d8d17718e15201d7f1d79524d81d04b978d19ffd/src/components/authorization/roles/project-manager-global.role.ts#L230-L230
=> Change Engagement.products to get permissions from app

src/common/resource.dto.ts, src/common/secured-property.ts, src/components/engagement/handlers/update-project-status.handler.ts, src/components/project/events/project-created.event.ts, src/components/project/events/project-deleted.event.ts, src/components/project/events/project-updated.event.ts, src/components/project/handlers/set-department-id.handler.ts, src/components/project/handlers/set-initial-mou-end.handler.ts, src/components/project/handlers/set-step-changed-at.handler.ts, src/components/project/handlers/step-changed-notification.handler.ts, src/components/project/project.resolver.ts, src/components/project/project.service.ts, src/core/database/changes.ts, src/core/database/database.service.ts, src/core/database/results/types.ts
This allows project events to be executed without requiring the current user to have permission to make the event handler changes.
=> Unsecured project events

src/common/db-label.decorator.ts, src/common/index.ts, src/components/budget/dto/budget.dto.ts, src/components/literacy-material/dto/literacy-material.dto.ts, src/components/organization/dto/organization.dto.ts, src/components/product/dto/product.dto.ts, src/components/project/dto/project.dto.ts, src/core/database/database.service.ts
=> Add property labels on update

src/components/engagement/engagement.rules.ts, src/components/project/project.rules.ts, src/core/database/database.service.ts
Query has been tested with updating ProjectName.
=> Prefix updated property node labels with Deleted_

src/components/language/ethnologue-language/ethnologue-language.service.ts, test/language.e2e-spec.ts
=> Don't try to update Ethnologue if there are no changes

src/components/engagement/engagement.service.ts, src/components/project/project.service.ts, test/engagement.e2e-spec.ts, test/utility/register.ts
=> Allow admins to create engagement anytime

src/components/post/dto/shareability.dto.ts
=> Rename post shareability enum values from "Public" to "External"

src/components/budget/budget.repository.ts, src/components/budget/budget.service.ts, src/components/budget/dto/budget-record.dto.ts, src/components/budget/dto/budget.dto.ts, src/components/ceremony/ceremony.repository.ts, src/components/ceremony/ceremony.service.ts, src/components/ceremony/dto/ceremony.dto.ts, src/components/ceremony/handlers/create-engagement-default-ceremony.handler.ts, src/components/ceremony/handlers/delete-engagement-default-ceremony.handler.ts, src/components/engagement/dto/engagement.dto.ts, src/components/engagement/engagement.repository.ts, src/components/engagement/engagement.service.ts, src/components/engagement/events/engagement-will-delete.event.ts, src/components/engagement/events/index.ts, src/components/partnership/dto/partnership.dto.ts, src/components/partnership/partnership.repository.ts, src/components/partnership/partnership.service.ts, src/components/product/dto/product.dto.ts, src/components/product/product.repository.ts, src/components/product/product.service.ts, src/components/project/project-member/dto/project-member.dto.ts, src/components/project/project-member/project-member.repository.ts, src/components/project/project-member/project-member.service.ts, src/core/database/query/cypher-functions.ts, src/core/database/query/index.ts, src/core/database/query/match-project-based-props.ts, src/core/database/query/matching.ts, src/core/database/results/parse-props.ts, src/core/database/results/types.ts, src/core/database/subquery.override.ts
It's based on highest language engaged or project's own sensitivity for internships and calculated on read
Also moved role scoping & flattening into query
Part of #1736
=> Add sensitivity to project based resources

src/components/authorization/authorization.repository.ts, src/components/authorization/authorization.service.ts, src/components/budget/budget.service.ts, src/components/ceremony/handlers/create-engagement-default-ceremony.handler.ts, src/components/engagement/engagement.service.ts, src/components/field-region/field-region.service.ts, src/components/field-zone/field-zone.service.ts, src/components/file/handlers/attach-project-root-directory.handler.ts, src/components/film/film.service.ts, src/components/funding-account/funding-account.service.ts, src/components/language/ethnologue-language/ethnologue-language.service.ts, src/components/language/language.service.ts, src/components/literacy-material/literacy-material.service.ts, src/components/location/location.service.ts, src/components/organization/organization.service.ts, src/components/partner/partner.service.ts, src/components/partnership/partnership.service.ts, src/components/product/product.service.ts, src/components/project/project-member/project-member.service.ts, src/components/project/project.service.ts, src/components/song/song.service.ts, src/components/story/story.service.ts, src/components/user/education/education.service.ts, src/components/user/unavailability/unavailability.service.ts, src/components/user/user.service.ts
This further limits their usage to just authorization roles
=> Change processNewBaseNode to use label from resource class

src/app.module.ts, src/components/periodic-report/periodic-report-engagement-connection.resolver.ts
Also change progress reports to only exist on Language Engagements
=> Connect Periodic Reports module

src/components/post/dto/list-posts.dto.ts
=> Post sorting default & filter tweaks

src/components/authorization/authorization.service.ts, src/components/authorization/model/permission.model.db.ts, src/components/authorization/roles/consultant-manager-global.role.ts, src/components/budget/budget.service.ts, src/components/budget/dto/budget.dto.ts, test/security/budget.e2e-spec.ts, test/security/permissions.ts, test/utility/create-budget.ts, test/utility/create-organization.ts, test/utility/fragments.ts, test/utility/roles.ts, test/utility/sensitivity.ts
Should be merged after https://github.com/SeedCompany/cord-api-v3/pull/1908
=> Budget record fix list of nulls when not authorized to see budget's budget record list

src/components/periodic-report/periodic-report.resolver.ts
- Give name to pnp extraction code in case of extraction failure
=> Make pnp extraction transactional

src/core/database/cypher.factory.ts, src/core/database/errors.ts, src/core/graphql-logging.plugin.ts, src/core/graphql.config.ts, src/core/logger/formatters.ts
Ok but I have no idea where that query is, and thanks for the duplicate message clutter.
Much better!
=> Improve DB errors

src/components/user/user.repository.ts, src/components/user/user.service.ts
Update user query to use new match props function and merge roles inside of query. Split out secure step into separate function in service.
=> Refactor User.readOne to use new strategies

src/components/periodic-report/dto/report-period.enum.ts, src/components/periodic-report/handlers/sync-periodic-report-to-project.handler.ts, src/components/project/dto/create-project.dto.ts, src/components/project/project.service.ts
What needed to happen in the UI again? I'm ready with the queries.
=> Make financialReportPeriod nullable

src/components/changeset/changeset.repository.ts, src/core/database/database.service.ts
Now when `updateProperty` is called if the new value matches the existing value (outside of the changeset) it is considered a revert. In this case the old changeset property is still deleted but the new property is no longer created. Not only is this cleaner data but it helps our diff query know that there isn't actually a change there without having to do a comparison.
Also updated the diff query to ignore `modifiedAt` properties when determining changed BaseNodes. This prop is changed automatically when other properties are changed but it isn't reverted if properties are reverted.
=> Handle changeset reverts (by user)

src/components/engagement/engagement.resolver.ts, src/components/partnership/partnership.resolver.ts
=> Add range override fields to Engagement, Partnership

src/components/ceremony/handlers/delete-engagement-default-ceremony.handler.ts, src/components/engagement/engagement.repository.ts, src/components/engagement/engagement.resolver.ts, src/components/engagement/engagement.service.ts, src/components/engagement/handlers/apply-approved-changeset-to-engagement.handler.ts, src/components/partnership/handlers/apply-approved-changeset-to-partnership.handler.ts, src/components/partnership/partnership.repository.ts, src/components/partnership/partnership.resolver.ts, src/components/partnership/partnership.service.ts, src/components/periodic-report/periodic-report.repository.ts, src/core/database/common.repository.ts, src/core/database/database.service.ts, src/core/database/query/deletes.ts, src/core/database/query/lists.ts, test/engagement-changeset-aware.e2e-spec.ts, test/partnership-changeset-aware.e2e-spec.ts
Need to implement in `Partnership.delete` as well.
=> Delete in Changeset

src/components/changeset/changeset.repository.ts
Also fixes added items query which needs to account for the lack of a deleting relation as well
=> Update changeset diff query to handle new "deleting" relation

src/components/authorization/roles/consultant-global.role.ts, src/components/authorization/roles/consultant-manager-global.role.ts, src/components/authorization/roles/consultant-manager-on-project.role.ts, src/components/authorization/roles/consultant-on-project.role.ts, src/components/authorization/roles/controller.role.ts, src/components/authorization/roles/fundraising.role.ts, src/components/authorization/roles/intern.role.ts, src/components/authorization/roles/leadership.role.ts, src/components/authorization/roles/liaison.role.ts, src/components/authorization/roles/marketing.role.ts, src/components/authorization/roles/mentor.role.ts, src/components/authorization/roles/regional-communications-coordinator.role.ts, src/components/authorization/roles/staff-member.role.ts, src/components/authorization/roles/translator.role.ts
Closes https://github.com/SeedCompany/cord-api-v3/issues/1969
=> Update users permission for periodic reports edit

src/components/authorization/dto/powers.ts
=> Add Beta Features Power

src/components/authorization/authorization.service.ts, src/components/user/user.service.ts, test/project-member.e2e-spec.ts, test/utility/grant-power.ts, test/utility/register.ts
Correctly convey that a user can only edit their roles if they have the GrantRole power.
Related to https://github.com/SeedCompany/cord-field/issues/722
=> User cannot edit their own roles unless GrantRole power

src/components/product/dto/completion-description.dto.ts, src/components/product/dto/index.ts, src/components/product/product.repository.ts, src/components/product/product.resolver.ts, src/components/product/product.service.ts, src/core/database/database.service.ts, src/core/database/indexer/create-indexes.decorator.ts, src/core/database/indexer/indexer.module.ts, src/core/database/query/full-text.ts, src/core/database/query/index.ts
Save and suggest `Product.completionDescription`
This is powered by a full text index, so a couple abstractions have been added to aid in that.
Related to #1737
=> Save and suggest product completion descriptions

src/components/budget/budget.service.ts, src/components/budget/handlers/sync-budget-records-to-funding-partners.handler.ts, src/components/partnership/partnership.repository.ts, src/components/partnership/partnership.service.ts, src/components/project/handlers/apply-approved-changeset-to-project.handler.ts, test/project-changeset-aware.e2e-spec.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1983
=> Partnership changeset bugs

src/components/budget/budget.repository.ts
Fixes #2053
Regressed in #2044
=> Fix budget template file creation

src/common/validators/email.validator.ts, src/components/user/dto/create-person.dto.ts, src/components/user/dto/update-user.dto.ts, src/components/user/dto/user.dto.ts, src/components/user/user.repository.ts, src/components/user/user.service.ts, src/core/database/query/deactivate-property.ts, test/user.e2e-spec.ts
https://github.com/SeedCompany/cord-api-v3/issues/1610
=> Make User.email optional

src/components/progress-summary/dto/progress-summary.dto.ts, src/components/progress-summary/handlers/extract-pnp-file-on-upload.handler.ts, src/components/progress-summary/progress-extractor.service.ts, src/components/progress-summary/progress-report-connection.resolver.ts, src/components/progress-summary/progress-summary-engagement-connection.resolver.ts, src/components/progress-summary/progress-summary.module.ts, src/components/progress-summary/progress-summary.repository.ts, src/components/progress-summary/progress-summary.resolver.ts
=> New progress summary periods

src/components/authorization/dto/role.dto.ts
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/2065
=> 2065 - Add beta tester role

src/components/progress-summary/handlers/extract-pnp-file-on-upload.handler.ts, src/components/progress-summary/progress-extractor.service.ts
=> Goals & Progress | Parse Overall Progress from PnP

src/components/periodic-report/dto/list-periodic-reports.dto.ts, src/components/periodic-report/dto/periodic-report.dto.ts, src/components/periodic-report/periodic-report-engagement-connection.resolver.ts, src/components/periodic-report/periodic-report-project-connection.resolver.ts, src/components/periodic-report/periodic-report.repository.ts, src/components/periodic-report/periodic-report.service.ts
=> Consider project scoped roles & sensitivity when authorizing periodic reports

src/components/changeset/dto/changeset.args.ts
=> Validate input for IdsAndView

src/components/user/unavailability/unavailability.repository.ts, src/components/user/unavailability/unavailability.service.ts
=> unavailabilities > Total number is returned 0 even "> 0" records are available 

src/components/project/dto/list-projects.dto.ts, src/components/project/query.helpers.ts, src/core/database/query/index.ts, src/core/database/query/where-path.ts
=> Fix project filters

src/components/authorization/roles/administrator.role.ts, src/components/authorization/roles/consultant-global.role.ts, src/components/authorization/roles/consultant-manager-global.role.ts, src/components/authorization/roles/consultant-manager-on-project.role.ts, src/components/authorization/roles/consultant-on-project.role.ts, src/components/authorization/roles/controller.role.ts, src/components/authorization/roles/field-operations-director.role.ts, src/components/authorization/roles/financial-analyst-global.role.ts, src/components/authorization/roles/financial-analyst-on-project.role.ts, src/components/authorization/roles/fundraising.role.ts, src/components/authorization/roles/intern.role.ts, src/components/authorization/roles/lead-financial-analyst-global.role.ts, src/components/authorization/roles/lead-financial-analyst-on-project.role.ts, src/components/authorization/roles/leadership.role.ts, src/components/authorization/roles/liaison.role.ts, src/components/authorization/roles/marketing.role.ts, src/components/authorization/roles/mentor.role.ts, src/components/authorization/roles/project-manager-global.role.ts, src/components/authorization/roles/project-manager-on-project.role.ts, src/components/authorization/roles/regional-communications-coordinator.role.ts, src/components/authorization/roles/regional-director-global.role.ts, src/components/authorization/roles/regional-director-on-project.role.ts, src/components/authorization/roles/staff-member.role.ts, src/components/authorization/roles/translator.role.ts, src/components/ceremony/ceremony.repository.ts, src/components/ceremony/ceremony.service.ts, src/core/database/query/lists.ts, test/security/ceremony.security.ts, test/utility/create-engagement.ts
also fix sort of listCeremonies to have a custom matcher that returns the project node's name to sort on
=> List ceremony based on global and scoped roles and sensitivity of project

src/components/file/local-bucket.controller.ts
=> Return file content instead of stream

src/components/project/project.rules.ts
=> Add ProjectManager to PendingConsultantEndorsement step approvers

src/components/engagement/engagement.rules.ts, src/components/engagement/engagement.service.ts, src/components/file/handlers/attach-project-root-directory.handler.ts, src/components/project/handlers/step-changed-notification.handler.ts, src/components/project/project-member/project-member.service.ts, src/components/project/project.rules.ts, src/components/project/project.service.ts, src/core/config/config.service.ts
=> Remove migration configuration logic

src/components/partnership/partnership.service.ts
=> Fix partnership update when partner cannot be read

src/components/authorization/roles/consultant-manager-global.role.ts, src/components/authorization/roles/consultant-manager-on-project.role.ts, src/components/authorization/roles/consultant-on-project.role.ts, src/components/authorization/roles/controller-global.role.ts, src/components/authorization/roles/controller-on-project.role.ts, src/components/authorization/roles/financial-analyst-global.role.ts, src/components/authorization/roles/financial-analyst-on-project.role.ts, src/components/authorization/roles/fundraising-global.role.ts, src/components/authorization/roles/fundraising-on-project.role.ts, src/components/authorization/roles/intern.role.ts, src/components/authorization/roles/lead-financial-analyst-global.role.ts, src/components/authorization/roles/lead-financial-analyst-on-project.role.ts, src/components/authorization/roles/leadership.role.ts, src/components/authorization/roles/liaison.role.ts, src/components/authorization/roles/marketing-global.role.ts, src/components/authorization/roles/marketing-on-project.role.ts, src/components/authorization/roles/mentor.role.ts, src/components/authorization/roles/project-manager-global.role.ts, src/components/authorization/roles/project-manager-on-project.role.ts, src/components/authorization/roles/regional-communications-coordinator.role.ts, src/components/authorization/roles/regional-director-global.role.ts, src/components/authorization/roles/regional-director-on-project.role.ts, src/components/authorization/roles/staff-member.role.ts, src/components/authorization/roles/translator.role.ts
Fixes:https://github.com/SeedCompany/cord-api-v3/issues/2151
=> Restrict preset inventory perms

src/components/product/product.repository.ts, src/components/product/query.helpers.ts
=> add product approach and methodology list filters

src/components/file/file.service.ts
Part of https://github.com/SeedCompany/cord-field/issues/786
=> Rename file on new verision upload

.gitignore, Dockerfile, src/common/fiscal-year.ts, src/components/changeset/dto/changeset-diff.dto.ts, src/core/data-loader/loader.decorator.ts, src/core/database/common.repository.ts, src/core/database/query-augmentation/SubClauseCollection.ts, src/core/database/query-augmentation/condition-variables.ts, src/core/database/query/create-relationships.ts, src/core/resources/resource-resolver.service.ts
Since #2182 got put on the back burner for a while I wanted to get these unrelated changes in that were discovered in dev process.
=> Tweaks & fixes pulled out of #2182

src/components/authorization/roles/consultant-manager-global.role.ts, src/components/authorization/roles/staff-member.role.ts, src/components/budget/budget.repository.ts, src/components/budget/budget.service.ts, src/components/project/project.service.ts, test/security/budget.security.ts, test/security/organization.security.ts, test/security/project.security.ts, test/utility/create-organization.ts
=> Project budget secured based on sensitivity defined in roles

src/common/xlsx.util.ts, src/components/file/dto/node.ts, src/components/file/file.service.ts, src/components/periodic-report/dto/periodic-report.dto.ts, src/components/periodic-report/events/periodic-report-uploaded.event.ts, src/components/periodic-report/periodic-report.repository.ts, src/components/periodic-report/periodic-report.service.ts, src/components/product-progress/dto/progress-report.input.ts, src/components/product-progress/handlers/extract-pnp-progress.handler.ts, src/components/product-progress/handlers/index.ts, src/components/product-progress/product-progress.module.ts, src/components/product-progress/step-progress-extractor.service.ts, src/components/product/product.repository.ts, src/components/product/product.service.ts, src/components/progress-summary/progress-extractor.service.ts, src/components/progress-summary/progress-summary.module.ts, tsconfig.json
=> Extract step progress from PnP

src/components/product/migrations/AddProgressMeasurements.migration.ts, src/components/product/migrations/index.ts, src/components/product/product.module.ts, src/components/product/product.repository.ts
=> Added product progress measurements migration

src/common/async-pool.util.ts, src/components/progress-summary/handlers/extract-pnp-file-on-upload.handler.ts, src/components/progress-summary/migrations/index.ts, src/components/progress-summary/migrations/pnp-capture-summary-for-multiple-periods.migration.ts, src/components/progress-summary/progress-extractor.service.ts, src/components/progress-summary/progress-summary.module.ts, src/components/progress-summary/progress-summary.repository.ts, src/core/database/migration/base-migration.service.ts
- Fixed [bug in saving summary data](https://github.com/SeedCompany/cord-api-v3/compare/master...hotfix/pnp-progress-summary?expand=1#diff-46756b3927db1c52cc64ee6c05d71f2c4208a83454583470ba226d94510a385aR40)
- Added migration to re-extract all PnP's to save data for all periods now extracted (reporting period, fiscal year, cumulative).
This fixes previously bugged cumulative data & adds extracted data for the 2 new periods.
=> Hotfix PnP progress summary extraction

src/common/fiscal-year.ts, src/components/product/product-extractor.service.ts
=> Fix issues around matching steps in product extraction

src/components/product-progress/step-progress-extractor.service.ts, src/components/product/product-extractor.service.ts, src/components/scripture/books.ts
=> More PnP fixes

src/components/search/search.repository.ts
Fixes #2253 
Fixes #2250
Fixes [#996](https://github.com/SeedCompany/cord-field/issues/996)
=> Fix EthnoArt search

src/components/product/handlers/extract-products-from-pnp.handler.ts, src/components/product/product-extractor.service.ts
=> Extract product completion description from PnP "My Notes" column

src/components/product/dto/available-steps.ts
=> Add Completed step to OtherVisual methodology

src/app.module.ts, src/components/partnership-producing-medium/dto/partnership-producing-medium.dto.ts, src/components/partnership-producing-medium/partnership-producing-medium-engagement-connection.resolver.ts, src/components/partnership-producing-medium/partnership-producing-medium.module.ts, src/components/partnership-producing-medium/partnership-producing-medium.repository.ts, src/components/partnership-producing-medium/partnership-producing-medium.resolver.ts, src/components/partnership-producing-medium/partnership-producing-medium.service.ts, src/components/partnership-producing-medium/update-partnership-producing-medium-output.resolver.ts
=> Implement partnership producing medium

src/components/product/handlers/extract-products-from-pnp.handler.ts, src/components/product/migrations/ReextractPlanningPnps.migration.ts, src/components/product/migrations/index.ts, src/components/product/product.service.ts
=> Update products on extract & add migration to re-extract existing planning pnps

src/components/authorization/roles/consultant-global.role.ts, src/components/authorization/roles/consultant-manager-global.role.ts, src/components/authorization/roles/consultant-manager-on-project.role.ts, src/components/authorization/roles/consultant-on-project.role.ts, src/components/authorization/roles/controller-global.role.ts, src/components/authorization/roles/controller-on-project.role.ts, src/components/authorization/roles/field-operations-director.role.ts, src/components/authorization/roles/lead-financial-analyst-on-project.role.ts, src/components/authorization/roles/marketing-global.role.ts, src/components/authorization/roles/marketing-on-project.role.ts, src/components/authorization/roles/project-manager-global.role.ts, src/components/authorization/roles/project-manager-on-project.role.ts, src/components/authorization/roles/regional-director-on-project.role.ts
=> Adjust disbursementCompleteDate permissions

src/components/authorization/roles/financial-analyst-global.role.ts
=> Restrict budget edit permissions for financial analyst global role

src/components/project/project.repository.ts, src/components/project/project.service.ts
=> Allow field region and primary location to be null when updated

src/components/budget/handlers/update-project-current-budget-status.handler.ts, src/components/engagement/handlers/update-project-status.handler.ts
Fixes:https://github.com/SeedCompany/cord-api-v3/issues/2199
=> Handle project active to in dev

src/components/engagement/handlers/apply-finalized-changeset-to-engagement.handler.ts, src/components/engagement/language-engagement.resolver.ts, src/components/language/dto/update-language.dto.ts, src/components/language/language.loader.ts, src/components/language/language.repository.ts, src/components/language/language.resolver.ts, src/components/language/language.service.ts, src/components/user/known-language.resolver.ts, test/language-changeset-aware.e2e-spec.ts
Fixes https://github.com/SeedCompany/cord-api-v3/issues/2205
=> Language changeset aware

src/common/validators/email.validator.ts
=> Tweak email validator

src/components/scripture/books.ts, src/components/scripture/dto/scripture-reference.transformer.ts
=> Validate scriptureReference end bookName

src/components/ceremony/ceremony.repository.ts, src/components/engagement/engagement.service.ts, src/components/engagement/handlers/apply-finalized-changeset-to-engagement.handler.ts, src/components/engagement/handlers/set-initial-end-date.handler.ts, src/components/periodic-report/handlers/sync-progress-report-to-engagement.handler.ts, test/engagement-changeset-aware.e2e-spec.ts
Fixes https://github.com/SeedCompany/cord-api-v3/issues/2204 https://github.com/SeedCompany/cord-field/issues/933
=> Engagement ceremony changeset

src/components/authorization/roles/administrator.role.ts, src/components/authorization/roles/consultant-global.role.ts, src/components/authorization/roles/consultant-manager-global.role.ts, src/components/authorization/roles/consultant-manager-on-project.role.ts, src/components/authorization/roles/consultant-on-project.role.ts, src/components/authorization/roles/controller-global.role.ts, src/components/authorization/roles/controller-on-project.role.ts, src/components/authorization/roles/field-operations-director.role.ts, src/components/authorization/roles/financial-analyst-global.role.ts, src/components/authorization/roles/financial-analyst-on-project.role.ts, src/components/authorization/roles/fundraising-global.role.ts, src/components/authorization/roles/fundraising-on-project.role.ts, src/components/authorization/roles/intern.role.ts, src/components/authorization/roles/lead-financial-analyst-global.role.ts, src/components/authorization/roles/lead-financial-analyst-on-project.role.ts, src/components/authorization/roles/leadership.role.ts, src/components/authorization/roles/liaison.role.ts, src/components/authorization/roles/marketing-global.role.ts, src/components/authorization/roles/marketing-on-project.role.ts, src/components/authorization/roles/mentor.role.ts, src/components/authorization/roles/project-manager-global.role.ts, src/components/authorization/roles/project-manager-on-project.role.ts, src/components/authorization/roles/regional-communications-coordinator.role.ts, src/components/authorization/roles/regional-director-global.role.ts, src/components/authorization/roles/regional-director-on-project.role.ts, src/components/authorization/roles/staff-member.role.ts, src/components/authorization/roles/translator.role.ts, src/components/language/dto/language.dto.ts, src/components/language/model/language.model.db.ts
API part of https://github.com/SeedCompany/cord-field/issues/946
=> Add posts to language

src/components/scripture/dto/scripture-range.dto.ts
=> Tweak ScriptureField decorator

src/components/product-progress/handlers/extract-pnp-progress.handler.ts, src/components/product-progress/step-progress-extractor.service.ts, src/components/product/dto/create-product.dto.ts, src/components/product/dto/product.dto.ts, src/components/product/dto/update-product.dto.ts, src/components/product/handlers/extract-products-from-pnp.handler.ts, src/components/product/migrations/AddComposite.migration.ts, src/components/product/model/product.model.db.ts, src/components/product/product-extractor.service.ts, src/components/product/product.module.ts, src/components/product/product.repository.ts, src/components/product/product.service.ts, src/components/scripture/dto/scripture-range.dto.ts, src/components/scripture/parser.test.ts, src/components/scripture/parser.ts
=> Extract stories from OBS PnP

src/components/file/dto/update.dto.ts
=> Tweak file name field

src/components/product/dto/create-product.dto.ts, src/components/product/product.repository.ts
=> Tweak progressStepMeasurement default

src/components/authorization/roles/consultant-on-project.role.ts
=> Add step write permission on consultant-on-project role to transition from PendingConsultantEndorsement to PrepForFinancialEndorsement

src/common/util.ts, src/components/product-progress/handlers/extract-pnp-progress.handler.ts, src/components/product-progress/step-progress-extractor.service.ts, src/components/product/dto/create-product.dto.ts, src/components/product/dto/product.dto.ts, src/components/product/dto/update-product.dto.ts, src/components/product/handlers/extract-products-from-pnp.handler.ts, src/components/product/product-extractor.service.ts, src/components/product/product.repository.ts, src/components/product/product.service.ts, src/components/scripture/books.ts
=> Product pnp index

src/components/ceremony/handlers/create-engagement-default-ceremony.handler.ts, src/components/engagement/dto/engagement.dto.ts, src/components/engagement/engagement.repository.ts, src/components/engagement/engagement.service.ts, src/components/engagement/events/engagement-created.event.ts, src/components/engagement/events/engagement-updated.event.ts, src/components/engagement/handlers/apply-finalized-changeset-to-engagement.handler.ts, src/components/engagement/handlers/set-initial-end-date.handler.ts, src/components/engagement/handlers/set-last-status-date.handler.ts, src/components/periodic-report/handlers/sync-progress-report-to-engagement.handler.ts, src/components/product/handlers/extract-products-from-pnp.handler.ts, src/components/product/migrations/ReextractPlanningPnps.migration.ts
The logic should happen regardless of current user permissions
=> Change update & create engagement events to be unsecured

.github/workflows/ci.yml
16.9.0 bug was fixed a few days later with 16.9.1
=> Update CI tests to use Node 16

src/common/resource.dto.ts, src/components/periodic-report/periodic-report-parent.resolver.ts
=> Resolve PeriodicReport.parent type for GQL

src/components/partner/dto/create-partner.dto.ts, src/components/partner/dto/update-partner.dto.ts
=> Tweak partner create/update dto

src/components/product/migrations/AddProductSteps.migration.ts, src/components/product/migrations/index.ts
=> Added migration to populate all products with steps.

src/components/pnp/progress-sheet.ts
=> Fix goal start column to be book/story name

src/components/authentication/authentication.repository.ts, src/components/authentication/authentication.service.ts, src/components/authentication/session.interceptor.ts, src/components/authentication/session.resolver.ts, src/core/database/query/match-project-based-props.ts, test/utility/create-directory.ts
This saves 1 db call for _every_ request
=> Lookup roles in resume session query

src/components/engagement/engagement.repository.ts, test/engagement-changeset-aware.e2e-spec.ts
Closes https://github.com/SeedCompany/cord-field/issues/1058
=> Fix duplicate engagements for project in changeset

src/components/product-progress/product-progress.repository.ts, src/components/product-progress/product-progress.service.ts
=> Restrict product progress service to update only the steps that are planned

src/components/location/dto/location-type.enum.ts, src/components/post/dto/shareability.dto.ts, src/components/product/dto/product-medium.ts, src/components/product/dto/progress-measurement.enum.ts
This is based on a convention described here
https://github.com/SeedCompany/cord-field/issues/1106#issuecomment-1110011256
=> Define labels for enum values that don't follow the standard rules

src/components/file/file.service.ts, src/core/database/transactional-mutations.interceptor.ts
=> Rollback S3 file creation on error

src/components/pnp/isGoalStepPlannedInsideProject.spec.ts
@CarsonF - An example shell for @atGit2021 on how to lay out conditions to test a function.
=> Stubbed stepCompleteDate tests

src/components/project/list-filter.query.ts, src/core/database/query/filters.ts
=> Fix onlyMultipleEngagements project list filter

src/components/engagement/dto/intern-position.enum.ts
=> Made Exegetical/Translation Facilitator Internship roles historic; added Mid Level Quality Assurance Internship role.

src/components/post/dto/create-post.dto.ts
=> Make parentId field required

.gitignore, package.json, src/components/admin/admin.service.ts, src/core/config/config.service.ts, src/core/database/indexer/indexer.module.ts, src/repl.ts
https://docs.nestjs.com/recipes/repl
```
$ yarn repl
```
=> Setup NestJS REPL

src/components/engagement/engagement.repository.ts, src/components/engagement/engagement.service.ts, src/components/project/project.rules.ts, test/engagement.e2e-spec.ts
Fixes https://github.com/SeedCompany/cord-api-v3/issues/2526
=> Adjust finalize completion

src/components/pnp/isGoalRow.ts, src/components/product/handlers/extract-products-from-pnp.handler.ts, src/components/product/product-extractor.service.ts, src/components/product/product.service.ts, src/components/scripture/dto/scripture-range.dto.ts, src/components/scripture/parser.ts
Bryan, for your review. This is the code for capturing and parsing scripture references from the book column or my notes section when uploading the PnP planning and progress sheets.
=> parse and capture scripture references from book name or my notes

src/components/product/product.loader.ts, src/core/database/errors.ts, src/core/exception.filter.ts
- Create/handle new Session Expired Error
- Lower max batch size of product lower to 25 from 100
=> Attempt to handle large product queries more gracefully.

src/components/authorization/dto/beta-features.ts, src/components/authorization/policies/by-feature/new-progress-reports-beta.policy.ts, src/components/authorization/policies/index.ts
Create NewProgressReports beta feature for the new Progress/Quarterly reports for the UI
=> Added new progress report beta feature

src/common/resource.dto.ts, src/components/budget/budget-record.repository.ts, src/components/budget/budget.repository.ts, src/components/budget/dto/budget-record.dto.ts, src/components/budget/dto/budget.dto.ts, src/components/changeset/changeset-aware.resolver.ts, src/components/changeset/dto/changeset-aware.dto.ts, src/components/engagement/dto/engagement.dto.ts, src/components/engagement/engagement.repository.ts, src/components/partnership/dto/partnership.dto.ts, src/components/partnership/partnership.repository.ts, src/components/project/dto/project.dto.ts, src/core/resources/resource.loader.ts
This is continued work on changesets to help the UI re-build the resource tree where needed.
=> Expose `ChangesetAware.parent` field

src/components/progress-report/community-stories/progress-report-community-story.repository.ts, src/components/progress-report/community-stories/progress-report-community-story.resolver.ts, src/components/progress-report/community-stories/progress-report-community-story.service.ts, src/components/progress-report/dto/community-stories.dto.ts, src/components/progress-report/dto/hightlights.dto.ts, src/components/progress-report/dto/progress-report.entity.ts, src/components/progress-report/once-per-project-from-progress-report-child.db-query.ts, src/components/progress-report/progress-report.module.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3502346908) by [Unito](https://www.unito.io)
┆Link To Item: https://seed-company-squad.monday.com/boards/3451697530/pulses/3502346908
=> Progress Report's Community Stories

src/common/rich-text.scalar.ts, src/components/prompts/dto/prompt-response.dto.ts, src/components/prompts/prompt-variant-response.service.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3503304195) by [Unito](https://www.unito.io)
┆Link To Item: https://seed-company-squad.monday.com/boards/3451697530/pulses/3503304195
=> Couple tweaks for PromptResponse updating

src/components/engagement/dto/engagement.dto.ts, src/components/engagement/dto/update-engagement.dto.ts
Added summary field to the engagement object
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3629667485) by [Unito](https://www.unito.io)
=> Add Engagment.description

src/components/authorization/policies/by-role/field-partner.policy.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3629288915) by [Unito](https://www.unito.io)
=> Field Partner Policy Updates

src/components/progress-report/migrations/AddStatus.migration.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3633549574) by [Unito](https://www.unito.io)
=> Complete adding progress report status migration

src/components/periodic-report/periodic-report.repository.ts
Match "not used" ProgressReports based on `NotStarted` status instead of report file presence
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3636128752) by [Unito](https://www.unito.io)
=> Keep started ProgressReports when project range changes

src/common/secured-property.ts, src/components/progress-report/progress-report.module.ts, src/components/progress-report/resolvers/progress-report.resolver.ts, src/components/progress-report/variance-explanation/reason-options.ts, src/components/progress-report/variance-explanation/variance-explanation.dto.ts, src/components/progress-report/variance-explanation/variance-explanation.loader.ts, src/components/progress-report/variance-explanation/variance-explanation.module.ts, src/components/progress-report/variance-explanation/variance-explanation.repository.ts, src/components/progress-report/variance-explanation/variance-explanation.resolver.ts, src/components/progress-report/variance-explanation/variance-explanation.service.ts
Related to https://github.com/SeedCompany/cord-field/issues/1106
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3643302121) by [Unito](https://www.unito.io)
=> ProgressReport VarianceExplanation

src/components/project/project.rules.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3647335362) by [Unito](https://www.unito.io)
=> Updated Project FinalizingCompletion approvers to include LFA

src/components/progress-report/workflow/transitions.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3656155460) by [Unito](https://www.unito.io)
=> NotStarted now goes to InProgress

src/components/pnp/extract-scripture.ts, src/components/pnp/index.ts, src/components/product-progress/handlers/extract-pnp-progress.handler.ts, src/components/product-progress/step-progress-extractor.service.ts, src/components/product/product-extractor.service.ts
…erence notes section does not exist on the progress sheet
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3523040122) by [Unito](https://www.unito.io)
=> Fix PnP to identify products from progress sheet the same way planning sheet does

src/components/file/bucket/file-bucket.ts, src/components/file/bucket/local-bucket.ts, src/components/file/bucket/s3-bucket.ts, src/components/file/file.service.ts, src/components/file/local-bucket.controller.ts
Magical line:
https://github.com/SeedCompany/cord-api-v3/blob/477cf59686a11ef7f9ecca33d67d3d3525af6fc8/src/components/file/file.service.ts#L130
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3681222229) by [Unito](https://www.unito.io)
=> Fix file not having the right name on download via S3 signed url

src/common/default-value.ts, src/common/filter-field.ts, src/common/index.ts, src/common/pagination.input.ts, src/components/budget/dto/list-budget.dto.ts, src/components/ceremony/dto/list-ceremony.dto.ts, src/components/engagement/dto/list-engagements.dto.ts, src/components/ethno-art/dto/list-ethno-art.dto.ts, src/components/field-region/dto/list-field-region.dto.ts, src/components/field-zone/dto/list-field-zone.dto.ts, src/components/file/dto/list.ts, src/components/film/dto/list-film.dto.ts, src/components/language/dto/list-language.dto.ts, src/components/literacy-material/dto/list-literacy-material.dto.ts, src/components/location/dto/list-locations.dto.ts, src/components/organization/dto/list-organization.dto.ts, src/components/partner/dto/list-partner.dto.ts, src/components/partnership/dto/list-partnership.dto.ts, src/components/post/dto/list-posts.dto.ts, src/components/product/dto/list-product.dto.ts, src/components/project-change-request/dto/project-change-request-list.dto.ts, src/components/project/dto/list-projects.dto.ts, src/components/project/project-member/dto/list-project-members.dto.ts, src/components/song/dto/list-story.dto.ts, src/components/story/dto/list-story.dto.ts, src/components/user/dto/list-users.dto.ts, src/components/user/education/dto/list-education.dto.ts, src/components/user/unavailability/dto/list-unavailabilities.dto.ts
Fixes #2547
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3692225368) by [Unito](https://www.unito.io)
=> Create FilterField decorator abstraction & coerce nulls to {}

src/components/authorization/policies/by-role/marketing.policy.ts, src/components/authorization/policies/by-role/project-manager.policy.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3751804815) by [Unito](https://www.unito.io)
=> Added explanation of progress permissions to project manager and marketing policies.

src/core/database/database.service.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3764521201) by [Unito](https://www.unito.io)
=> Change `DbUnique` constraints to throw, more specific, `DuplicateException`

src/components/location/dto/location-type.enum.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3767653024) by [Unito](https://www.unito.io)
=> Add Region to LocationType enum

src/components/authorization/policies/by-feature/user-can-manage-own-prompts.policy.ts, src/components/authorization/policies/by-feature/view-progress-report.policy.ts, src/components/authorization/policies/by-role/field-partner.policy.ts, src/components/authorization/policies/by-role/marketing.policy.ts, src/components/authorization/policies/by-role/project-manager.policy.ts, src/components/authorization/policies/by-role/translator.policy.ts, src/components/progress-report/dto/progress-report.entity.ts, src/components/progress-report/dto/team-news.dto.ts, src/components/progress-report/progress-report.module.ts, src/components/progress-report/team-news/progress-report-team-news.repository.ts, src/components/progress-report/team-news/progress-report-team-news.resolver.ts, src/components/progress-report/team-news/progress-report-team-news.service.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3753950612) by [Unito](https://www.unito.io)
=> Add Team News

src/components/authorization/policies/by-role/consultant.policy.ts
Closes #2723.
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3833101085) by [Unito](https://www.unito.io)
=> Updated Consultant policy to include edit/create permission for Narrative Reports.

src/components/project/project.rules.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3840320754) by [Unito](https://www.unito.io)
=> Fix notifications for DidNotDevelop/Rejected

src/core/database/query-augmentation/log-it.ts, src/core/database/query-augmentation/root.ts, src/core/database/query-augmentation/subquery.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3872029970) by [Unito](https://www.unito.io)
=> Fix `logIt` not applying in sub queries

src/components/admin/admin.service.ts, src/core/config/config.service.ts, src/core/database/cypher.factory.ts, src/core/database/database.service.ts, src/core/database/indexer/indexer.module.ts, src/core/database/migration/migration-runner.service.ts, src/core/database/transaction.ts, src/core/logger/nest-logger-adapter.service.ts
Startup output is now:
```
[nest] Listening at http://localhost:3333/ +0ms
```
with logger.yml config
```yaml
levels:
nest:application,nest:factory,nest:loader,nest:router:*: warning
admin:service: error
version: info
database:query: debug
```
=> Reduce start up log spam

.github/workflows/test.yml
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3903735068) by [Unito](https://www.unito.io)
=> Parallelize e2e tests with native jest sharding & github actions matrix

.github/workflows/test.yml
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3904573788) by [Unito](https://www.unito.io)
=> Enable Jest annotations

src/components/progress-summary/dto/schedule-status.enum.ts
[Monday.com Ticket](https://seed-company-squad.monday.com/boards/3451697530/views/78801638/pulses/3873143878)
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3906185376) by [Unito](https://www.unito.io)
=> Adjust ScheduleStatus thresholds to match business requirements

src/components/user/unavailability/dto/unavailability.dto.ts, test/utility/fragments.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3912154635) by [Unito](https://www.unito.io)
=> Fix incorrect usage of DateTimeField on Unavailability object

package.json, yarn.lock
GQL schema breaking changes expected but shouldn't cause issues practically
Related to https://github.com/nestjs/graphql/pull/2500
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3912930701) by [Unito](https://www.unito.io)
=> Bump @nestjs/graphql

src/components/authorization/policies/by-role/financial-analyst.policy.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3927850215) by [Unito](https://www.unito.io)
=> FA policy fix to allow the viewing of partner information as a project member.

src/components/prompts/prompt-variant-response.repository.ts, src/components/prompts/prompt-variant-response.service.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3928623093) by [Unito](https://www.unito.io)
=> Various PromptVariantResponse fixes

src/components/project/project-member/project-member.repository.ts, src/components/project/project-member/project-member.service.ts, src/components/project/project.resolver.ts, src/components/project/project.service.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3952435152) by [Unito](https://www.unito.io)
=> Update ProjectMember list to use new privileges API

src/components/product-progress/handlers/extract-pnp-progress.handler.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3954508778) by [Unito](https://www.unito.io)
=> Fix exactScriptureMatch in progress extraction

src/components/authorization/policies/by-role/consultant-manager.policy.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3992486059) by [Unito](https://www.unito.io)
=> Tweak Consultant Manager Policy to allow the addition/removal of project members globally.

src/components/authorization/policies/by-role/financial-analyst-lead.policy.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3993319054) by [Unito](https://www.unito.io)
=> Tweaked read/edit capabilities of specific properties within the Lead Financial Analyst policy.

src/components/progress-report/workflow/progress-report-workflow.service.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/4116166387) by [Unito](https://www.unito.io)
=> Unify progress report workflow transition execution

src/common/temporal/date-time.ts, src/core/database/database.service.ts, src/core/database/indexer/create-indexes.decorator.ts, src/core/database/indexer/indexer.module.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/4135878500) by [Unito](https://www.unito.io)
=> Prep for Neo4j 4.4/5+ / Drop support for 4.2-

src/common/util.ts, src/components/authentication/authentication.module.ts, src/components/authentication/session.interceptor.ts, src/components/file/dto/node.ts, src/components/file/file-url.controller.ts, src/components/file/file.repository.ts, src/components/file/file.service.ts
Continuing on from #2706 
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/4226983156) by [Unito](https://www.unito.io)
=> Public/Anonymous Files

src/components/location/dto/create-location.dto.ts, src/components/location/dto/location.dto.ts, src/components/location/dto/update-location.dto.ts, src/components/location/location.module.ts, src/components/location/location.repository.ts, src/components/location/location.resolver.ts, src/components/location/location.service.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/4227010405) by [Unito](https://www.unito.io)
=> Add `Location.mapImage` file

src/components/location/location.module.ts, src/components/location/migrations/add-location-map-image.migration.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/4234346779) by [Unito](https://www.unito.io)
=> Migrate db to add location map image nodes

src/components/authorization/policies/by-role/financial-analyst.policy.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/4259501556) by [Unito](https://www.unito.io)
=> Added read rights for FAs to view organizations

.github/workflows/test.yml, docker-compose.yml
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/4265952603) by [Unito](https://www.unito.io)
=> Bump CI & local compose to use neo4j 4.4

src/components/periodic-report/periodic-report.repository.ts, src/components/periodic-report/periodic-report.service.ts, src/components/progress-report/resolvers/progress-report-engagement-connection.resolver.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/4265553361) by [Unito](https://www.unito.io)
=> Add `Engagement.progressReport` by date

src/components/product/product.resolver.ts, src/components/scripture/labels.test.ts, src/components/scripture/labels.ts
Fixes https://github.com/SeedCompany/cord-api-v3/issues/2345
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/4185236236) by [Unito](https://www.unito.io)
=> Configurable scripture range label collapsing

src/common/util.ts, src/components/progress-report/workflow/events/workflow-updated.event.ts, src/components/progress-report/workflow/handlers/index.ts, src/components/progress-report/workflow/handlers/progress-report-workflow-notification.handler.ts, src/components/progress-report/workflow/progress-report-workflow.module.ts, src/components/progress-report/workflow/progress-report-workflow.repository.ts, src/components/progress-report/workflow/progress-report-workflow.service.ts, src/components/progress-report/workflow/transitions.ts, src/core/config/config.service.ts, src/core/config/environment.service.ts, src/core/database/cypher.factory.ts, src/core/email/templates/formatted-date-time.tsx, src/core/email/templates/progress-report-status-changed.template.tsx, src/core/email/templates/project-step-changed.template.tsx, src/core/email/templates/user-ref.tsx
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/4084609702) by [Unito](https://www.unito.io)
=> Feature: Email notifcations for qtrly report status changes

src/components/file/bucket/composite-bucket.ts, src/core/logger/formatters.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/4403889146) by [Unito](https://www.unito.io)
=> Bug fixes for CompositeBucket

src/components/progress-report/variance-explanation/variance-explanation.resolver.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/4443083276) by [Unito](https://www.unito.io)
=> clamp actual and planned progress summary values

src/components/progress-summary/progress-summary.resolver.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/4445354198) by [Unito](https://www.unito.io)
=> clamp planned and actual value for progress summary

.github/workflows/test.yml, docker-compose.yml, package.json, src/components/admin/admin.repository.ts, src/components/admin/admin.service.ts, src/components/changeset/commit-changeset-props.query.ts, src/components/changeset/reject-changeset-props.query.ts, src/components/engagement/handlers/apply-finalized-changeset-to-engagement.handler.ts, src/components/partnership/handlers/apply-finalized-changeset-to-partnership.handler.ts, src/components/progress-summary/progress-summary.repository.ts, src/components/project/project.repository.ts, src/components/user/user.repository.ts, src/core/config/config.service.ts, src/core/database/cypher.factory.ts, src/core/database/errors.ts, src/core/database/indexer/indexer.module.ts, src/core/database/query/create-relationships.ts, src/core/database/query/deletes.ts, src/core/database/query/matching.ts, src/core/exception/exception.filter.ts, src/core/graphql/graphql-logging.plugin.ts, yarn.lock
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/4136628009) by [Unito](https://www.unito.io)
=> Neo4j 5 Support

dbschema/language.esdl, dbschema/migrations/00004.edgeql, dbschema/migrations/00005.edgeql
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/4806395168) by [Unito](https://www.unito.io)
=> Add engagements and projects backlinks to Language object.

package.json, src/core/logger/formatters.ts, yarn.lock
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/4847177953) by [Unito](https://www.unito.io)
=> Use colors from nestjs

src/core/database/cypher.factory.ts, src/core/database/transaction.ts
In a lot of places we blindly throw a nicer exception wrapping the original, which gives the nicer message to the API caller.
Here's an example:
https://github.com/SeedCompany/cord-api-v3/blob/71d27115f7bcdbbe4e6d5d2f9088c3f8a2317117/src/components/project/project.service.ts#L183-L183
This is a problem when the error is transient database error, which the transaction executor should retry.
To work around this, we need to also check if the exception thrown wraps a _retriable_ database error.
We previously did this by digging into the neo4j lib and monkey patched the "should retry" check to look at our "previous" exceptions.
This is invasive and doesn't work with ESM where module exports are immutable.
Instead, we can change our transaction handling logic.
Now when an error is thrown, …
=> Refactor how we adjust the neo4j retry logic

package.json, yarn.lock
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/4870768416) by [Unito](https://www.unito.io)
=> Bump data loader lib for bug fix

src/components/organization/dto/create-organization.dto.ts, src/components/organization/dto/organization.dto.ts, src/components/organization/dto/update-organization.dto.ts, src/components/organization/migrations/add-acronym.migration.ts, src/components/organization/organization.module.ts, src/components/organization/organization.repository.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/4872259478) by [Unito](https://www.unito.io)
=> Add `Organization.acronym`

src/components/language/dto/language.dto.ts, src/components/partner/dto/create-partner.dto.ts, src/components/partner/dto/partner.dto.ts, src/components/partner/dto/update-partner.dto.ts, src/components/partner/partner.repository.ts, src/components/partner/partner.resolver.ts, src/components/partner/partner.service.ts
https://seed-company-squad.monday.com/boards/3451697530/pulses/4788456611
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/4872260317) by [Unito](https://www.unito.io)
=> Add `Partner.languageOfWiderCommunication`

package.json, src/components/project/project.rules.ts, tsconfig.json, yarn.lock
Better grouping of options.
Defaulting to strictest settings published, and backing off from there.
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/4878846481) by [Unito](https://www.unito.io)
=> Refactor tsconfig

.github/workflows/test.yml, docker-compose.yml, package.json, src/core/config/config.service.ts, src/core/database/cypher.factory.ts, src/core/database/database.service.ts, yarn.lock
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/4909176383) by [Unito](https://www.unito.io)
=> Drop neo4j v4 support

docker-compose.yml
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/4913662664) by [Unito](https://www.unito.io)
=> Tweak local neo4j config to ignore auth

src/components/authorization/policies/by-role/consultant-manager.policy.ts, src/components/authorization/policies/by-role/consultant.policy.ts, src/components/progress-report/variance-explanation/variance-explanation.dto.ts, src/components/prompts/prompt-variant-response.repository.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/4918890424) by [Unito](https://www.unito.io)
=> Consultant (Manager) Policy - Add Progress Report Reads

src/components/authorization/policies/by-feature/read-util-objects.policy.ts, src/components/authorization/policy/executor/policy-dumper.ts, src/components/post/dto/post.dto.ts, src/components/post/dto/postable.dto.ts, src/components/post/post.loader.ts, src/components/post/post.repository.ts, src/components/post/post.service.ts, src/components/post/postable.resolver.ts
Superseding #2821. I added more clean up and tightened security for posts by ID functionality.
I believe [this](https://github.com/SeedCompany/cord-api-v3/pull/2867/commits/5fe7ad1407489bcf69f77f709d342f71b960339b) was the biggest missing piece.
Here we can see the read perms for `Project.posts`, which is checked first.
Then we can see that `Post.*` properties are always available to read.
<pre class="term-container">
<span class="term-fgi90">┌─────────────────────────────────────────────────────────────────────────────────────┐</span>
<span class="term-fgi90">│</span>                                     <span class="term-fgi95">Permissions</span>                                     <span class="term-fgi90">│</span>
<span class="term-fgi90">│</span> <span class="term-fgi95">Role</span> …
=> Migrate posts to use privileges

src/common/xlsx.util.ts, src/repl.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5047502507) by [Unito](https://www.unito.io)
=> `loadPnp` for easy REPL usage

src/components/file/media/detect-existing-media.migration.ts, src/components/file/media/media.dto.ts, src/components/file/media/media.repository.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5117536505) by [Unito](https://www.unito.io)
=> Fix 3x media bugs

src/common/db-label.decorator.ts, src/common/db-label.helpers.ts, src/components/file/dto/node.ts, src/components/file/media/media.dto.ts, src/core/database/query/create-node.ts, src/core/database/query/create-relationships.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5094862149) by [Unito](https://www.unito.io)
=> Fix BaseFile being a label in the DB / Other small refactors

src/components/file/media/media.repository.ts
Idk how this got through
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5124670706) by [Unito](https://www.unito.io)
=> Fix Media.save query

src/components/file/file.service.ts, src/core/database/database.module.ts, src/core/database/index.ts, src/core/database/rollback-manager.ts, src/core/database/transactional-mutations.interceptor.ts
This:
- Standardizes the hack that was in `FileService`
- Decouples from Neo4j, allowing transition to EdgeDB
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5186089356) by [Unito](https://www.unito.io)
=> Abstract away rollback management

src/core/database/common.repository.ts, src/core/database/dto.repository.ts, src/core/database/query/index.ts, src/core/database/query/properties/update-relation-list.ts
(when children are not scoped under)
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5202959206) by [Unito](https://www.unito.io)
=> Add abstraction to update one-to-many relations

src/core/database/common.repository.ts, src/core/database/dto.repository.ts, src/core/database/query/properties/update-relation-list.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5260770354) by [Unito](https://www.unito.io)
=> Add CommonRepository.getBaseNodes

src/components/field-region/dto/field-region.dto.ts, src/components/partner/dto/create-partner.dto.ts, src/components/partner/dto/partner.dto.ts, src/components/partner/dto/update-partner.dto.ts, src/components/partner/partner.repository.ts, src/components/partner/partner.resolver.ts, src/components/partner/partner.service.ts, src/core/database/changes.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5074239434) by [Unito](https://www.unito.io)
=> Add Partner.fieldRegions

src/common/secured-mapper.ts, src/components/changeset/enforce-changeset-editable.pipe.ts, src/components/partner/partner.resolver.ts, src/components/product-progress/progress-report-connection.resolver.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5289221361) by [Unito](https://www.unito.io)
=> A couple data loader helpers

src/components/partner/dto/partner.dto.ts, src/components/partner/dto/update-partner.dto.ts, src/components/partner/partner.repository.ts, src/components/partner/partner.service.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5290575971) by [Unito](https://www.unito.io)
=> Allow null for Partner.pointOfContact to clear it

src/components/project/project.rules.ts
https://seed-company-squad.monday.com/boards/3451697530/pulses/5119151173
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5309056082) by [Unito](https://www.unito.io)
=> Added ProjectManger to approve PendingChangeToPlanApproval

src/components/location/dto/location.dto.ts, src/components/partner/dto/create-partner.dto.ts, src/components/partner/dto/partner.dto.ts, src/components/partner/dto/update-partner.dto.ts, src/components/partner/partner.repository.ts, src/components/partner/partner.resolver.ts, src/components/partner/partner.service.ts
https://seed-company-squad.monday.com/boards/3451697530/pulses/5037868084
@bryanjnelson here is that draft PR for you to look at.
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5124319112) by [Unito](https://www.unito.io)
=> Add `Partner.countries`

src/components/progress-report/variance-explanation/migrations/rename.migration.ts, src/components/progress-report/variance-explanation/reason-options.ts, src/components/progress-report/variance-explanation/variance-explanation.module.ts, src/components/progress-report/variance-explanation/variance-explanation.service.ts
To be considered with [Cord-Field PR](https://github.com/SeedCompany/cord-field/pull/1486)
[Ticket explaining changes](https://seed-company-squad.monday.com/boards/3451697530/pulses/5123136460)
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5320368981) by [Unito](https://www.unito.io)
=> Update Variance Reason Options (and add deprecations)

src/common/generate-id.ts, src/common/resource.dto.ts, src/components/budget/budget.repository.ts, src/components/budget/budget.service.ts, src/components/engagement/engagement.repository.ts, src/components/location/location.repository.ts, src/components/partnership/partnership.repository.ts, src/core/database/database.service.ts, src/core/database/query/create-node.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5394309064) by [Unito](https://www.unito.io)
=> Fix types from recent changes

src/common/email-field.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5427575228) by [Unito](https://www.unito.io)
=> Forward null email instead of null coalescing to undefined

.github/actions/edgedb-setup/action.yml
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5429442045) by [Unito](https://www.unito.io)
=> Use edgedb cli v3 for now until v4 is stabilized

src/common/date-filter.input.ts, src/components/periodic-report/dto/list-periodic-reports.dto.ts, src/components/periodic-report/periodic-report.repository.ts, src/core/database/query/filters.test.ts, src/core/database/query/filters.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5290575399) by [Unito](https://www.unito.io)
=> Allow filtering of periodic reports by start/end dates

Dockerfile
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5434044289) by [Unito](https://www.unito.io)
=> Switch to new node install commands for docker image

dbschema/project.esdl
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5488021633) by [Unito](https://www.unito.io)
=> [EdgeDB] Add some constraints for project's own context

dbschema/location.esdl
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5488035870) by [Unito](https://www.unito.io)
=> [EdgeDB] Create `Location` schema

dbschema/field-region.esdl, dbschema/field-zone.esdl
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5490937335) by [Unito](https://www.unito.io)
=> [EdgeDB] Create `FieldRegion` and `FieldZone` schemas

dbschema/engagement.esdl, dbschema/file.esdl, dbschema/location.esdl, dbschema/project.esdl
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5490627911) by [Unito](https://www.unito.io)
=> [EdgeDB] First WIP pass at file schema to get something for other places

dbschema/migrations/00022.edgeql, dbschema/migrations/00023.edgeql
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5493568135) by [Unito](https://www.unito.io)
=> [EdgeDB] create migrations from latest changes

dbschema/migrations/00024.edgeql, dbschema/user.esdl
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5505043074) by [Unito](https://www.unito.io)
=> [EdgeDB] Make `User.timezone` required, default to CST

src/components/user/dto/create-person.dto.ts, src/components/user/dto/update-user.dto.ts, src/components/user/dto/user.dto.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5505002191) by [Unito](https://www.unito.io)
=> Correctly mark User phone, about, title as nullable

dbschema/funding-account.esdl
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5508396647) by [Unito](https://www.unito.io)
=> [EdgeDB] Create `FundingAccount` schema

src/core/edgedb/edgedb.service.ts, src/core/edgedb/generator/query-builder.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5509250909) by [Unito](https://www.unito.io)
=> Few tweaks/fixes for EdgeDB app interaction

dbschema/authentication.esdl, dbschema/migrations/00025.edgeql, dbschema/resource.esdl, dbschema/z.timestamped.esdl, src/components/admin/admin.edgedb.repository.ts, src/components/admin/admin.module.ts, src/components/admin/admin.service.ts, src/components/authentication/authentication.edgedb.repository.ts, src/components/authentication/authentication.module.ts, src/components/user/user.edgedb.repository.ts, src/components/user/user.module.ts, src/components/user/user.repository.ts, src/components/user/user.service.ts, src/core/edgedb/error.util.ts, src/core/edgedb/index.ts, src/core/edgedb/withScope.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5509296807) by [Unito](https://www.unito.io)
=> EdgeDB Auth Schema & Queries / Admin & User Queries

.github/actions/edgedb-setup/action.yml, .github/workflows/edgedb-schema.yml
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5517822729) by [Unito](https://www.unito.io)
=> [EdgeDB] Add PR workflow to check if migrations are in sync

dbschema/language.esdl, dbschema/migrations/00026.edgeql
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5519638108) by [Unito](https://www.unito.io)
=> [EdgeDB] Restore Language.projects schema link

dbschema/location.esdl, dbschema/migrations/00027.edgeql
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5588320743) by [Unito](https://www.unito.io)
=> [EdgeDB] Location links

dbschema/migrations/00029.edgeql, dbschema/organization.esdl, dbschema/partner.esdl
[Monday story](https://seed-company-squad.monday.com/boards/3451697530/pulses/5452830216)
=> [EdgeDB] Create `Organization` and `Partner` schemas

dbschema/budget.esdl, dbschema/engagement.esdl, dbschema/migrations/00030.edgeql, dbschema/migrations/00031.edgeql, dbschema/project.esdl
[Monday story](https://seed-company-squad.monday.com/boards/3451697530/pulses/5452828843)
NOTE:  Wait to merge until Org/Partner schemas are complete.
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5512960148) by [Unito](https://www.unito.io)
=> [EdgeDB] Create `Budget` and `BudgetRecord` schemas and associated triggers

.yarn/patches/edgedb-npm-1.4.0-902d833279.patch, package.json, src/common/temporal/calendar-date.ts, src/common/temporal/date-time.ts, src/core/edgedb/generator/query-builder.ts, yarn.lock
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5595320064) by [Unito](https://www.unito.io)
=> [EdgeDB] Fix luxon scalars within Ranges & QB literals

dbschema/migrations/00032.edgeql, dbschema/user.esdl
[Monday Story](https://seed-company-squad.monday.com/boards/3451697530/pulses/5452830669)
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5558073015) by [Unito](https://www.unito.io)
=> [EdgeDB] Create `Education` & `Unavailability` types in `User` schema

src/components/budget/budget.service.ts, src/components/ceremony/ceremony.service.ts, src/components/engagement/engagement.service.ts, src/components/ethno-art/ethno-art.service.ts, src/components/field-region/field-region.service.ts, src/components/field-zone/field-zone.service.ts, src/components/file/file.repository.ts, src/components/film/film.service.ts, src/components/funding-account/funding-account.service.ts, src/components/language/language.service.ts, src/components/location/location.service.ts, src/components/organization/organization.service.ts, src/components/partner/partner.service.ts, src/components/partnership/partnership.service.ts, src/components/product/product.service.ts, src/components/project-change-request/project-change-request.service.ts, src/components/project/project.service.ts, src/components/story/story.service.ts, src/components/user/user.repository.ts, src/components/user/user.service.ts, src/core/database/common.repository.ts, src/core/database/database.service.ts, test/engagement-changeset-aware.e2e-spec.ts, test/engagement.e2e-spec.ts, test/partner.e2e-spec.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5601024713) by [Unito](https://www.unito.io)
=> Migrate to new delete permission check

src/components/authorization/policies/by-role/project-manager.policy.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5706380829) by [Unito](https://www.unito.io)
=> Added BTL Role in FPM policy

src/components/periodic-report/periodic-report.repository.ts
Addresses [Monday Task 0915](https://seed-company-squad.monday.com/boards/3451697530/pulses/5731437304)
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5731531635) by [Unito](https://www.unito.io)
=> Add type filtering in `PeriodicReportRepository.list` query

src/components/partner/dto/create-partner.dto.ts, src/components/partner/dto/partner.dto.ts, src/components/partner/dto/update-partner.dto.ts, src/components/partner/partner.repository.ts
[Monday Task](https://seed-company-squad.monday.com/boards/3451697530/views/78801638/pulses/5592448716)
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5735781203) by [Unito](https://www.unito.io)
[UI related PR](https://github.com/SeedCompany/cord-field/pull/1503)
=> Add Partner.startDate

src/components/periodic-report/periodic-report.repository.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5773347397) by [Unito](https://www.unito.io)
=> Fix PeriodicReports `type` filter

dbschema/funding-account.esdl, dbschema/migrations/00034.edgeql, dbschema/migrations/00035.edgeql, dbschema/migrations/00036.edgeql, dbschema/project.esdl, src/components/project/handlers/set-department-id.handler.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5786036475) by [Unito](https://www.unito.io)
=> [EdgeDB] departmentId

src/components/funding-account/funding-account.edgedb.repository.ts, src/components/funding-account/funding-account.module.ts, src/components/funding-account/funding-account.repository.ts, src/components/funding-account/funding-account.service.ts
[Monday Task](https://seed-company-squad.monday.com/boards/3451697530/pulses/5587667061)
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5589534725) by [Unito](https://www.unito.io)
=> [EdgeDB] Create `Funding Account` queries

dbschema/language.esdl, dbschema/migrations/00040.edgeql, dbschema/seeds/004.users.edgeql, dbschema/seeds/005.languages.edgeql, dbschema/seeds/006.translation-projects.edgeql, dbschema/seeds/007.language-engagements.edgeql, dbschema/seeds/008.project-members.edgeql
[Monday Task](https://seed-company-squad.monday.com/boards/3451697530/pulses/5611462853)
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5822607374) by [Unito](https://www.unito.io)
=> [EdgeDB] Add seed data for `User`, `Language`, `TranslationProject`, and `LanguageEngagement`

src/components/authorization/policies/by-role/intern.policy.ts, src/components/authorization/policies/by-role/marketing.policy.ts, src/components/authorization/policies/by-role/mentor.policy.ts, src/components/authorization/policies/by-role/translator.policy.ts, src/components/project/dto/create-project.dto.ts, src/components/project/dto/project.dto.ts, src/components/project/dto/update-project.dto.ts, src/components/project/project.repository.ts, src/components/project/project.resolver.ts, src/components/project/project.service.ts
https://seed-company-squad.monday.com/boards/3451697530/pulses/5814829451
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5843591019) by [Unito](https://www.unito.io)
=> Add Project.marketingRegionOverride

dbschema/funding-account.esdl, dbschema/language.esdl, dbschema/migrations/00041.edgeql, dbschema/migrations/00042.edgeql, dbschema/project.esdl, dbschema/scripture.esdl, dbschema/seeds/006.translation-projects.edgeql
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5875344516) by [Unito](https://www.unito.io)
=> [EdgeDB] Workaround some upstream bugs temporarily

package.json, src/common/pagination.input.ts, src/components/field-zone/dto/field-zone.dto.ts, src/components/field-zone/field-zone.edgedb.repository.ts, src/components/field-zone/field-zone.module.ts, src/components/field-zone/field-zone.repository.ts, src/components/field-zone/field-zone.resolver.ts, src/components/field-zone/field-zone.service.ts, src/components/file/file.repository.ts, src/components/prompts/dto/prompt-response.dto.ts, src/core/database/changes.ts, src/core/edgedb/dto.repository.ts, src/core/resources/resource.loader.ts, yarn.lock
Actual changes for FieldZones that should be copy/pasted to other modules:
https://github.com/SeedCompany/cord-api-v3/pull/3053/files/f531e474c19f8c53efc08e9814a7ac567abbd097..47e725a217ed4c5c1f7b6d51752828e022eba56e
=> [EdgeDB] FieldZone Queries

src/core/edgedb/generator/query-builder.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5919122920) by [Unito](https://www.unito.io)
=> [EdgeDB] Removed upstreamed change to generation

src/components/field-region/dto/field-region.dto.ts, src/components/field-region/field-region.edgedb.repository.ts, src/components/field-region/field-region.module.ts, src/components/field-region/field-region.repository.ts, src/components/field-region/field-region.resolver.ts, src/components/field-region/field-region.service.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5879560840) by [Unito](https://www.unito.io)
=> [EdgeDB] Create `Field Region` queries

.github/workflows/edgedb.yml
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5932868980) by [Unito](https://www.unito.io)
=> CI skip clean migration check while PR is draft

dbschema/seeds/004.users.edgeql
Addresses subtask of [Monday Item #0940](https://seed-company-squad.monday.com/boards/3451697530/pulses/5774921596)
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5941896446) by [Unito](https://www.unito.io)
=> Add `Unavailabilities` to `User` seeding

dbschema/migrations/00049.edgeql, dbschema/partner.esdl, dbschema/partnership.esdl, dbschema/project.esdl
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5926613100) by [Unito](https://www.unito.io)
=> [EdgeDB] Partnership schema

dbschema/migrations/00050.edgeql, dbschema/producible.esdl, dbschema/product.esdl, dbschema/scripture.esdl
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5925717215) by [Unito](https://www.unito.io)
=> [EdgeDB] Create `Product` schema

dbschema/migrations/00053.edgeql, dbschema/partnership-producing-medium.esdl
Address the schema portion of [Monday Task #0929](https://seed-company-squad.monday.com/boards/3451697530/pulses/5774743628)
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5973384933) by [Unito](https://www.unito.io)
=> [EdgeDB] Create `PartnershipProducingMedium` schema

src/components/file/dto/node.ts, src/core/database/changes.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/6029688149) by [Unito](https://www.unito.io)
=> Fix a couple types: FileId / changes to nullable links

src/components/authorization/policies/by-role/marketing.policy.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/6035730523) by [Unito](https://www.unito.io)
=> Enabled displayNamePronunciation edit rights for marketing role

src/components/language/dto/list-language.dto.ts, src/components/language/language.repository.ts, src/components/partner/partner.module.ts, src/components/partner/partner.resolver.ts, src/components/partner/partner.service.ts
Adds languages as a field on a partner
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/6032097031) by [Unito](https://www.unito.io)
for Monday 4843004068
=> Add Partner.languages

dbschema/seeds/010.internship-engagements.edgeql
https://seed-company-squad.monday.com/boards/3451697530/pulses/5850633765
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/6074307408) by [Unito](https://www.unito.io)
=> [EdgeDB] Add seed data for Internship Engagements

dbschema/migrations/00056.edgeql, dbschema/prompt-variant-response.esdl
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/6066857331) by [Unito](https://www.unito.io)
=> [EdgeDB]: PromptVariantResponse schema

src/components/field-region/field-region.repository.ts, src/components/field-region/field-region.service.ts, src/components/field-zone/field-zone.repository.ts, src/components/field-zone/field-zone.service.ts, src/components/funding-account/funding-account.repository.ts, src/components/funding-account/funding-account.service.ts, src/components/user/user.repository.ts, src/components/user/user.service.ts, src/core/edgedb/dto.repository.ts
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/6165454374) by [Unito](https://www.unito.io)
=> [EdgeDB] Convert DefaultRepo.update to single parameter

dbschema/seeds/011.product.edgeql
https://seed-company-squad.monday.com/boards/5989610236/pulses/5793006654
While this is being reviewed I will continue working on the seed data for `DerivativeScriptureProduct` and `OtherProduct`.
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/6160636235) by [Unito](https://www.unito.io)
=> [EdgeDB] DirectScriptureProduct seeds

package.json, src/core/edgedb/dto.repository.ts, src/core/edgedb/query-util/easy-insert.ts, yarn.lock
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/6177367353) by [Unito](https://www.unito.io)
=> Bump edgedb libs & normalize types

dbschema/seeds/009.organizations.edgeql, dbschema/seeds/010.partners.edgeql
[Monday Task](https://seed-company-squad.monday.com/boards/5989610236/pulses/5792999898)
=> [EdgeDB] Add seed data for `Organization` and `Partner`

dbschema/media.esdl, dbschema/migrations/00060.edgeql
[Monday Task](https://seed-company-squad.monday.com/boards/5989610236/views/132288519/pulses/5799662499)
Created Media Schema for EdgeDB
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/6157904435) by [Unito](https://www.unito.io)
=> [EdgeDB] Media schema

src/core/edgedb/dto.repository.ts
Now customized DTO repo classes can use `this.defaults` to access the default methods.
```ts
.customize((cls) => {
return class extends cls {
async create(input: X) {
return await this.defaults.create({
...
});
}
};
})
```
=> [EdgeDB] Access default methods when customizing

dbschema/migrations/00061.edgeql, dbschema/product-progress.esdl
https://seed-company-squad.monday.com/boards/5989610236/pulses/5792959117
=> EdgeDb - product progress schema

dbschema/comments.esdl, dbschema/migrations/00068.edgeql, dbschema/project.esdl, src/components/comments/dto/comment-thread.dto.ts, src/components/comments/dto/comment.dto.ts, src/components/comments/dto/commentable.dto.ts
https://seed-company-squad.monday.com/boards/5989610236/pulses/5792954463
=> [EdgeDB] Comment Schema

src/components/progress-report/variance-explanation/variance-explanation.dto.ts, src/components/progress-report/variance-explanation/variance-explanation.edgedb.repository.ts, src/components/progress-report/variance-explanation/variance-explanation.module.ts, src/components/progress-report/variance-explanation/variance-explanation.repository.ts, src/components/progress-report/variance-explanation/variance-explanation.service.ts
[Monday](https://seed-company-squad.monday.com/boards/5989610236/views/131962501/pulses/5799623085)
=> [EdgeDB] Create `Variance Explanation` queries / refactor service/repo layers appropriately

package.json, src/core/edgedb/dto.repository.ts, src/core/edgedb/query-util/map-to-set-block.ts, yarn.lock
Also a couple query tweaks using object casts on multiple IDs
=> Bump edgedb lib for object cast on expression fix

src/core/edgedb/dto.repository.ts
This provides a way to omit default methods when customizing without providing a replacement method.
```ts
.customize((cls, { defaults }) => {
return class extends cls {
static omit = [defaults.create, defaults.update, defaults.delete];
};
})
```
=> [EdgeDB] Repo.customize allow omitting default methods

src/components/progress-summary/dto/progress-summary.dto.ts, src/components/progress-summary/progress-summary.edgedb.repository.ts, src/components/progress-summary/progress-summary.loader.ts, src/components/progress-summary/progress-summary.module.ts, src/components/progress-summary/progress-summary.repository.ts
Added the Progress Summary queries. Can't find a way to test it locally though since we don't have projects setup in EdgeDB.
=> [EdgeDB] ProgressSummary queries

src/components/admin/admin.edgedb.repository.ts, src/components/authentication/authentication.edgedb.repository.ts, src/components/authentication/authentication.repository.ts, src/components/authentication/authentication.service.ts, src/core/edgedb/codecs/register-codecs.ts, src/core/edgedb/edgedb.service.ts, src/core/edgedb/index.ts, src/core/edgedb/query-util/disable-access-policies.option.ts, src/core/edgedb/transaction.context.ts
This follows up on #2960
https://seed-company-squad.monday.com/boards/5989610236/pulses/6374337425
=> [EdgeDB] Authentication queries v2

dbschema/migrations/00076.edgeql, dbschema/project.esdl, src/common/instance-maps.ts, src/components/file/handlers/attach-project-root-directory.handler.ts, src/components/project/dto/project.dto.ts, src/components/project/project.edgedb.repository.ts, src/components/project/project.module.ts, src/components/project/project.repository.ts, src/components/project/project.resolver.ts, src/components/project/project.service.ts, src/core/edgedb/dto.repository.ts
Added Project queries for EdgeDB
=> [EdgeDB] Project queries

dbschema/seeds/017.partnerships.edgeql
Seeding for Partnerships in EdgeDB
=> [EdgeDB] Partnership seeds

src/components/user/education/education.edgedb.repository.ts, src/components/user/education/education.module.ts, src/components/user/education/education.repository.ts, src/components/user/education/education.service.ts
[Monday Task](https://seed-company-squad.monday.com/boards/5989610236/views/131962501/pulses/5792981500)
Create EdgeDB UserEducation repository
=> [EdgeDB] User Education Queries

src/components/language/dto/language.dto.ts, src/components/language/dto/update-language.dto.ts, src/components/language/ethnologue-language/ethnologue-language.edgedb.repository.ts, src/components/language/ethnologue-language/ethnologue-language.repository.ts, src/components/language/ethnologue-language/ethnologue-language.service.ts, src/components/language/language.edgedb.repository.ts, src/components/language/language.module.ts, src/components/language/language.repository.ts, src/components/language/language.service.ts, src/components/project/dto/list-projects.dto.ts, src/components/project/list-filter.query.ts, src/components/project/project.edgedb.repository.ts
[Monday Task](https://seed-company-squad.monday.com/boards/5989610236/pulses/5792968862)
=> [EdgeDB] Create Language queries | refactor service/repo layers appropriately

src/components/progress-report/workflow/dto/workflow-event.dto.ts, src/components/progress-report/workflow/handlers/progress-report-workflow-notification.handler.ts, src/components/progress-report/workflow/progress-report-workflow.edgedb.repository.ts, src/components/progress-report/workflow/progress-report-workflow.module.ts, src/components/progress-report/workflow/progress-report-workflow.repository.ts, src/components/progress-report/workflow/progress-report-workflow.service.ts, src/components/progress-report/workflow/resolvers/progress-report-workflow-event.resolver.ts
[Monday](https://seed-company-squad.monday.com/boards/5989610236/views/131962501/pulses/5799644779)
=> [EdgeDB] ProgressReport Workflow Queries

src/components/authentication/session.resolver.ts
We were using the _impersonatee's_ perms to load the _impersonator_.
So when the impersonatee couldn't view the impersonator, the UI would not be able to **stop impersonating** because it didn't know the impersonator's roles (to conditionally show the toggle).
I think EdgeDB would've thrown a not found error here too.
=> Fix permissions for `SessionOutput.impersonator`

.github/workflows/test.yml, src/common/and-call.ts, src/common/index.ts, src/core/edgedb/edgedb.module.ts, test/utility/create-app.ts, test/utility/edgedb-setup.ts
https://seed-company-squad.monday.com/boards/5989610236/pulses/6334761231
=> [EdgeDB] E2E Tests

src/components/scripture/dto/scripture-collection.dto.ts, src/components/scripture/scripture-collection.resolver.ts, src/components/scripture/scripture-range.resolver.ts, src/components/scripture/scripture.module.ts, src/components/scripture/verse-equivalents.ts
=> Expose scripture parsing to GQL query as an adhoc util

dbschema/language.esdl, dbschema/migrations/00004.edgeql, dbschema/organization.esdl, dbschema/seeds/004.users.edgeql, dbschema/user.esdl, src/components/authentication/authentication.service.ts, src/components/project/project.edgedb.repository.ts, test/partnership.e2e-spec.ts, test/project.e2e-spec.ts, test/utility/edgedb-setup.ts
Now that the test suite is running, it has identified things we missed.
Notably:
- Add missing `location` links (974adee)
- Fix `Unavailability` dates to be `DateTimes` (7c8eeec)
The remaining errors, so far, are just from un-ported queries.
=> Small EdgeDB tweaks/fixes/refactors

src/components/user/unavailability/dto/unavailability.dto.ts, src/components/user/unavailability/unavailability.edgedb.repository.ts, src/components/user/unavailability/unavailability.module.ts, src/components/user/unavailability/unavailability.repository.ts, src/components/user/unavailability/unavailability.service.ts
Create EdgeDB User Unavailability Queries
=> [EdgeDB] User Unavailability Queries

src/components/ceremony/ceremony.edgedb.repository.ts, src/components/ceremony/ceremony.module.ts, src/components/ceremony/ceremony.repository.ts, src/components/ceremony/ceremony.resolver.ts, src/components/ceremony/ceremony.service.ts, src/components/ceremony/dto/ceremony.dto.ts, src/components/ceremony/dto/create-ceremony.dto.ts, src/components/ceremony/dto/update-ceremony.dto.ts, src/components/ceremony/handlers/create-engagement-default-ceremony.handler.ts
=> [EdgeDB] - Ceremony queries

src/components/project/handlers/send-step-change-notification-on-change-request-approved.ts, src/components/project/handlers/step-changed-notification.handler.ts, src/components/project/project-step.resolver.ts, src/components/project/project.rules.ts, src/components/project/project.service.ts
[Monday task](https://seed-company-squad.monday.com/boards/3451697530/views/78801638/pulses/5934478741)
Create simplified project workflow for Multiplication projects
=> Update Project Workflow for Multiplication Projects

src/components/product/dto/producible.dto.ts, src/components/scripture/edgedb.utils.ts, src/components/scripture/scripture-reference.service.ts, src/components/story/story.edgedb.repository.ts, src/components/story/story.repository.ts, src/components/story/story.service.ts
https://seed-company-squad.monday.com/boards/5989610236/pulses/5792978206 ?
=> [EdgeDB] Story queries & scripture helpers

src/components/admin/admin.edgedb.repository.ts
Error in local dev environment because of a modifying user not being set
- [N/A] Change the task url above to the actual Monday task
=> fix: fixing ghost user bug

src/components/budget/handlers/sync-budget-records-to-funding-partners.handler.ts, src/components/partnership/dto/partnership.dto.ts, src/components/partnership/partnership.edgedb.repository.ts, src/components/partnership/partnership.module.ts, src/components/partnership/partnership.repository.ts, src/components/partnership/partnership.resolver.ts, src/components/partnership/partnership.service.ts, src/core/database/results/parse-base-node.ts
https://seed-company-squad.monday.com/boards/5989610236/pulses/5792970379
@CarsonF Still work to be done but would love to get your eyes on these changes while working on the rest.
=> [EdgeDB] Create Partnership queries

src/components/film/film.edgedb.repository.ts, src/components/film/film.module.ts, src/components/film/film.repository.ts, src/components/film/film.service.ts
Implementing the EdgeDB Query Updates for the Film data
- [n/a] Add/update tests if needed
=> [EdgeDB] Film queries

src/core/edgedb/generator/query-builder.ts
Currently the QB doesn't map types correctly for overloaded properties/links that are declared above the direct parent.
This works around that by manually fixing the shapes for our schema.
=> [EdgeDB] Workaround QB typing overloads from ancestors

dbschema/engagement.esdl, dbschema/migrations/00009-m1bzq66.edgeql
Add `position` & `methodology` to `Engagement` schema
- [N/A] Change the task url above to the actual Monday task
=> Add `position` & `methodology` to `Engagement` schema

src/components/pin/pin.edgedb.repository.ts, src/components/pin/pin.module.ts
https://seed-company-squad.monday.com/boards/5989610236/pulses/5792971662
=> [EdgeDB] Pin Queries

.gitignore, .vscode/launch.json
Remove personal settings file from being tracked in Git.
- [N/A] Change the task url above to the actual Monday task
=> Modify gitignore for vscode

src/common/filter-field.ts, src/components/budget/dto/list-budget.dto.ts, src/components/ceremony/dto/list-ceremony.dto.ts, src/components/engagement/dto/list-engagements.dto.ts, src/components/ethno-art/dto/list-ethno-art.dto.ts, src/components/field-region/dto/list-field-region.dto.ts, src/components/field-zone/dto/list-field-zone.dto.ts, src/components/file/dto/list.ts, src/components/film/dto/list-film.dto.ts, src/components/language/dto/list-language.dto.ts, src/components/location/dto/list-locations.dto.ts, src/components/organization/dto/list-organization.dto.ts, src/components/partner/dto/list-partner.dto.ts, src/components/partnership/dto/list-partnership.dto.ts, src/components/post/dto/list-posts.dto.ts, src/components/product/dto/list-product.dto.ts, src/components/project-change-request/dto/project-change-request-list.dto.ts, src/components/project/dto/list-projects.dto.ts, src/components/project/project-member/dto/list-project-members.dto.ts, src/components/story/dto/list-story.dto.ts, src/components/user/dto/list-users.dto.ts, src/components/user/education/dto/list-education.dto.ts, src/components/user/unavailability/dto/list-unavailabilities.dto.ts
To avoid circular dependencies on initialization
=> Declare list `FilterField` type lazily

src/components/product/migrations/backfill-empty-mediums.migration.ts, src/components/product/product.module.ts
https://seed-company-squad.monday.com/boards/3451697530/pulses/6779103249
=> Script to backfill empty mediums

src/components/project/workflow/handlers/project-workflow-notification.handler.ts
Also, a quick optimization to skip hydrating email props if not needed
=> Don't notify the user executing the project transition

src/components/partnership/dto/partnership.dto.ts, src/components/partnership/index.ts, src/components/partnership/partnership-by-project-and-partner.loader.ts, src/components/partnership/partnership.edgedb.repository.ts, src/components/partnership/partnership.module.ts, src/components/partnership/partnership.repository.ts, src/components/partnership/partnership.service.ts, src/components/project/project.resolver.ts
[Monday task](https://seed-company-squad.monday.com/boards/3451697530/views/78801638/pulses/7046940396)
=> Add Project.partnership(partner: id)

dbschema/language.esdl, dbschema/migrations/00012-m1ah2np.edgeql, dbschema/seeds/005.languages.edgeql, src/components/authorization/policies/by-role/consultant-manager.policy.ts, src/components/authorization/policies/by-role/financial-analyst.policy.ts, src/components/authorization/policies/by-role/fundraising.policy.ts, src/components/authorization/policies/by-role/intern.policy.ts, src/components/authorization/policies/by-role/investor-common.policy.ts, src/components/authorization/policies/by-role/mentor.policy.ts, src/components/authorization/policies/by-role/staff-member.policy.ts, src/components/language/dto/create-language.dto.ts, src/components/language/dto/language.dto.ts, src/components/language/dto/list-language.dto.ts, src/components/language/dto/update-language.dto.ts, src/components/language/ethnologue-language/ethnologue-language.repository.ts, src/components/language/language.module.ts, src/components/language/language.repository.ts, src/components/language/language.resolver.ts, src/components/language/language.service.ts, src/components/language/migrations/rename-rod-to-rolv.migration.ts, test/utility/create-language.ts, test/utility/fragments.ts
https://seed-company-squad.monday.com/boards/5989610236/views/132288519/pulses/7114997013
=> RegistryOfDialects (ROD) -> RegistryOfLanguageVarieties (ROLV)

src/common/date-filter.input.ts, src/components/project/dto/list-projects.dto.ts, src/components/project/project-filters.query.ts, src/core/database/query/filters.ts
=> ProjectFilters.mouStart/End.isNull

dbschema/migrations/00013-m1wi5kt.edgeql, src/components/authorization/policies/by-role/marketing.policy.ts
https://seed-company-squad.monday.com/boards/3451697530/pulses/7278495086
=> Allow Marketing to start news/stories when the FPM has not

src/components/progress-summary/dto/schedule-status.enum.ts
[Monday](https://seed-company-squad.monday.com/boards/3451697530/pulses/6697704384?doc_id=6697712363)
This PR is connected to the following front end [PR](https://github.com/SeedCompany/cord-field/pull/1589)
=> Changed percentage variance for "ahead"

src/components/progress-report/dto/progress-report-list.dto.ts, src/components/progress-report/progress-report.module.ts, src/components/progress-report/progress-report.repository.ts, src/components/progress-report/progress-report.service.ts, src/components/progress-report/resolvers/progress-report.resolver.ts
https://seed-company-squad.monday.com/boards/5989610236/pulses/7125526862
=> Expose progressReports GQL query

src/app.module.ts, src/components/notifications/dto/index.ts, src/components/notifications/dto/mark-notification-read.args.ts, src/components/notifications/dto/notification-list.input.ts, src/components/notifications/dto/notification.dto.ts, src/components/notifications/notification.module.ts, src/components/notifications/notification.resolver.ts
https://seed-company-squad.monday.com/boards/5989610236/pulses/7542832281
=> Notifications GQL schema

src/components/pnp/verifyEngagementDateRangeMatches.ts, src/components/progress-report/migrations/reextract-all-progress-reports.migration.ts
I was wrong about the PnP not having the exact days. It does, it is just the formatted label that doesn't include it.
=> Fix engagement/pnp date match to exact match days exactly

src/components/product-progress/handlers/extract-pnp-progress.handler.ts
'Step Is Not Planned' was missing wiki link, this remedies that.
=> Add Wiki to 'Step Is Not Planned'

src/components/location/location.repository.ts, src/components/location/location.service.ts
This provides functionality to include an update for the location map image.
=> Fix UpdateLocation.mapImage regression

src/components/authorization/policies/by-role/project-manager.policy.ts
Allow edit permission on `paratextRegistryId` for fpm's
=> Update paratextRegistryId policy

src/components/engagement/engagement.repository.ts, src/components/user/dto/list-users.dto.ts, src/components/user/user.gel.repository.ts, src/components/user/user.repository.ts, src/core/database/query/sorting.ts
This is adding filter functionality to roles and title on users as well as creating full name sorting.
=> User Role/Title Filter and FullName Sort

src/common/validators/short-id.validator.ts
The validator calls the validate method once for each item in the array. This would normally be good, but we're abusing it to dynamically resolve the input to different IDs.
In doing this we were clobbering the array into the first item.
Now we handle this array case specifically and do the resolution once for the entire list.
=> Adjust ID validator to handle arrays with the `each` option.

src/components/project/dto/update-project.dto.ts, src/components/project/project.service.ts
Following up on #3368 to allow same thing on existing projects
=> Allow admins to set departmentId on existing projects

src/components/partner/dto/list-partner.dto.ts, src/components/partner/partner.repository.ts
Add the `startDate` field to the Partner filters
=> Add PartnerFilters.startDate

src/components/partner/dto/list-partner.dto.ts, src/components/partner/partner.repository.ts
Add `createdAt` to Partner filters
=> Add PartnerFilters.createdAt 

src/common/disabled.decorator.ts, src/common/index.ts, src/common/required-when.ts, src/components/engagement/dto/engagement.dto.ts, src/components/engagement/engagement.repository.ts, src/components/engagement/engagement.service.ts, src/components/project/dto/project.dto.ts, src/components/project/project.service.ts, src/components/project/workflow/project-workflow.service.ts, test/project-changeset-aware.e2e-spec.ts
I don't really think this is a long term solution but it at least is something for now.
=> Require certain Project fields when not in development

src/common/required-when.ts, src/components/engagement/engagement.service.ts, src/components/project/project.service.ts
This allows us to fill these missing data points on our bad data.
Hopefully this is temporary.
=> Allow updates to objects that have missing fields if the update reduces the missing number

dbschema/engagement.gel, dbschema/migrations/00019-m132fze.edgeql, dbschema/progress-report.gel, dbschema/project-workflow.gel, dbschema/project.gel, dbschema/seeds/001.funding-accounts.edgeql, dbschema/seeds/002.field-zones-regions.edgeql, dbschema/seeds/003.locations.edgeql, dbschema/seeds/004.users.edgeql, dbschema/seeds/005.languages.edgeql, dbschema/seeds/006.organizations.edgeql, dbschema/seeds/007.partners.edgeql, dbschema/seeds/010.project-members.edgeql, dbschema/seeds/011.language-engagements.edgeql, dbschema/seeds/012.internship-engagements.edgeql, dbschema/seeds/014.direct-scripture-products.edgeql, dbschema/seeds/015.derivative-scripture-products.edgeql, dbschema/seeds/016.other-scripture-products.edgeql, dbschema/seeds/017.partnerships.edgeql, dbschema/seeds/018.ceremonies.edgeql, dbschema/seeds/019.pins.edgeql, dbschema/z.stamped.gel
This will allow all modifications to be grouped by a single timestamp for a specific GQL mutation.
=> [Gel] Change timestamps to be when transaction started

src/components/user/dto/list-users.dto.ts, src/components/user/user.repository.ts
Expose filtering on user status.
=> Add User Status Filter

src/components/product/dto/product-medium.enum.ts
Fixing the product labels to align with business rules.
=> Adjust Product Medium Labels
